### PR TITLE
RHPAM-2036 :Group cannot be added in Business central integrated with…

### PR DESCRIPTION
**Pull request by RishiRajAnand**
… RHSSO integration

- The error message was displayed since method setScopeParamRequired is no longer present in keycloak version 4.8.3.
- Upgraded keycloak version to 4.8.3.
- Upgrade was needed due to change in some method signatures in latest version that were causing conflicts with our current version.
- PR for keycloak upgrade in kie-parent  - https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1003.

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Business-central.war can be downloaded here https://drive.google.com/open?id=1OAlVgddmvL2MsxiLw2V8wRXIy55_HP5w

**Comment by ederign** [comment]
@tomasdavidorg just added you here because you are the original reporter.

@domhanak or @tomasdavidorg could you guys please take a look at this?

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by ederign** [comment]
jenkins execute full downstream build please

**Comment by ederign** [comment]
Hi  @domhanak, is it possible to review this before end of sprint?

**Pull request merged**
