### PR TITLE
[7.52.x] AF-2822: Thread starvation while indexing fixed

### PR DESCRIPTION
**Pull request by adrielparedes**
Original: https://github.com/kiegroup/appformer/pull/1129

Backport:
* https://github.com/kiegroup/appformer/pull/1161
* https://github.com/kiegroup/kie-wb-common/pull/3655

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]

**Comment by adrielparedes** [comment]
jenkins run fdb

**Review by RishiRajAnand — APPROVED** [review]

**Comment by adrielparedes** [comment]
@mbiarnes the FDB still fails due to random reasons. Now it is just a timeout, are the servers overloaded?

**Review by ederign — APPROVED** [review]

**Pull request merged**
