### PR TITLE
AF-2444 : Fixed failing test for prod build

### PR DESCRIPTION
**Pull request by akumar074**
* changed to fetch existing File System when setting up JGit repo

### CODE REVIEW

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this

**Comment by akumar074** [comment]
> Please link here existing JIRA to know what is this change related

The change is related to prod build failure for a test in Jenkins. Currently, there is no JIRA. Do we need to raise JIRA for this?

**Comment by ederign** [comment]
Yes @akumar074  please create a jira! Thank you soo much for this.

**Comment by akumar074** [comment]
> Yes @akumar074 please create a jira! Thank you soo much for this.

Created JIRA [AF-2444](https://issues.redhat.com/browse/AF-2444) and linked the PR

**Pull request merged**
