### PR TITLE
[7.67.x-blue] Updating mysql connector

### PR DESCRIPTION
**Pull request by LightGuard**
Updating mysql connector gav

Related PRs:
https://github.com/kiegroup/droolsjbpm-integration/pull/3053
https://github.com/kiegroup/kie-wb-distributions/pull/1244
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2484
https://github.com/kiegroup/jbpm/pull/2433

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by baldimir** [comment]
Jenkins run cdb

**Comment by baldimir** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins do cdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins do cdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins do cdb

**Comment by baldimir** [comment]
jenkins do cdb

**Review by baldimir — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Comment by LightGuard** [comment]
jenkins do cdb

**Comment by yesamer** [comment]
jenkins do cdb

**Comment by yesamer** [comment]
jenkins do fdb

**Comment by yesamer** [comment]
jenkins do cdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by baldimir** [comment]
Closing this in favor of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2488 . There were more places that have to be updated, so @yesamer created a new PR chain, so it can be tested together.

**Pull request closed without merging**
