### PR TITLE
RHPAM-2933 log4j dependencies

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

https://issues.redhat.com/browse/RHPAM-2933

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by almope** [comment]
@Ginxo Enforcer is complaining in the checks about not having those deps managed

> 2021-03-01T14:17:39.0519236Z [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (no-managed-deps) @ dashbuilder-runtime ---
2021-03-01T14:17:39.0566013Z [WARNING] Rule 0: org.commonjava.maven.enforcer.rule.EnforceManagedDepsRule failed with message:
2021-03-01T14:17:39.0567877Z The following 2 dependencies are NOT using a managed version:
2021-03-01T14:17:39.0572163Z 
2021-03-01T14:17:39.0573282Z   - org.apache.logging.log4j:log4j-api:jar
2021-03-01T14:17:39.0574329Z   - org.apache.logging.log4j:log4j-core:jar

**Review by almope — APPROVED** [review]
lgtm, thanks!

**Comment by mareknovotny** [comment]
jenkins do product fdb

**Comment by Ginxo** [comment]
FD is in warning state

**Review by mareknovotny — APPROVED** [review]
lgtm and I downloaded https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdbp/job/appformer-master.fdbp/1/artifact/dashbuilder/dashbuilder-runtime/target/dashbuilder-runtime.war where the log4j seems correct on 2.13.2 version

**Pull request merged**
