### PR TITLE
Wires Removal

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by manstis** [comment]
Goodbye my dear friend; you served me well.

**Comment by ederign** [comment]
@manstis added you as reviewed to say the last words.

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
@ederign Could you please rebase? FDB failures are unrelated so I think we can merge this.

**Comment by domhanak** [comment]
jenkins execute compile downstream build

**Comment by ederign** [comment]
let's try this for the third time :)

**Pull request merged**
