### PR TITLE
[AF-2214] User confirmation when closing the workbench with unsaved stuff

### PR DESCRIPTION
**Pull request by caponetto**
JIRA task: [AF-2214](https://issues.jboss.org/browse/AF-2214)

If the user has unsaved changes and closes the browser, then they lost all changes without being warned about. Thus, as a last resort, in this PR the browser will ask the user for confirmation when closing the tab, closing the browser or refreshing the page.

**DEMO**
AF-2214-2019-09-10

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by dgutierr** [comment]
@caponetto  mind to add @lclay2 as a reviewer please and not merge under she approves?

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by lclay2** [comment]
The added warning message when closing the browser tab (X) seems to satisfy the conditions of the jira. 
* Please note that UX is working on a future design enhancement for the "Unsaved changes" dialog message at: https://issues.jboss.org/browse/AF-2249

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins execute full downstream build

**Pull request merged**
