### PR TITLE
DROOLS-4791: [DMN Designer] Not able to edit by double click after scroll

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-4791

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins execute compile downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Code looks fine, started build to get the war.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
