### PR TITLE
AF-1201: [CMS perspective] IE11 Adding tile navigation component for custom trees causes error

### PR DESCRIPTION
**Pull request by dgutierr**
@kkufova I managed to reproduce/fix it on a Win7/IE11 machine. Notice no test case is provided as this is a view only fix. IMO proper coverage must be provided by means of UI integration tests.

### CODE REVIEW

**Comment by jhrcek** [comment]
Just FYI: this is already covered in our selenium tests. In fact that's how I found this bug.

**Comment by kkufova** [comment]
@dgutierr, could you please check the fix or reassign the issue to somebody else?

**Comment by domhanak** [comment]
@jhrcek @dgutierr @ederign Do we want to merge this and backport?

**Comment by domhanak** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
@domhanak we don't want to merge this before the issue raised by @kkufova have been fixed.

**Comment by adrielparedes** [comment]
@dgutierr @jhrcek @kkufova @domhanak what is the status of this? Is this issue out dated, or do we still need to merge something?

**Comment by kkufova** [comment]
@adrielparedes, no, this should not be merged. I don't think the issue is fixed.

**Comment by dgutierr** [comment]
@jhrcek @kkufova are we still supporting IE11 :-P,  I think this is under consideration right now, isn't it?

**Comment by kkufova** [comment]
@dgutierr, my understanding is that IE is still supported.

**Comment by ederign** [comment]
I'm closing this PR due to inactivity. If necessary and I'll reopen it again, just let me know.

**Pull request closed without merging**
