### PR TITLE
RHPAM-2532: removing git write access and disabling by default the git protocol

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by manstis** [comment]
OOI Does this remove the ability to `git push` into Business Central completely?

**Comment by porcelli** [comment]
don't worry @manstis - this remove the git protocol push, ssh and http/https are the way to go.

the git protocol do not have any security mechanism.

**Comment by manstis** [comment]
You know me @porcelli.. I like to worry ;-)

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
@tomasdavidorg @domhanak can you please prioritise this? This is an important thing to have on 7.6.

The test for this:

Should keep working:
- git clone http://user:password@localhost:8080/business-central-7.29.0.Final-wildfly14/git/space/repo
- git clone ssh://dora@localhost:8001/space/repo


What should not work: 
- git clone git://localhost/space/repo

An extreme test would be to enable org.uberfire.nio.git.daemon.enabled (not a supported option on bc - because we don't support git clones any more, only via http(s) and ssh):
- git clone git://localhost/space/repo
and then try to do a git push in order to make sure that this will not work (pull also will not work)

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
@ederign @porcelli Additional PR backporting to 7.30.x branch is also required.

**Comment by domhanak** [comment]
@porcelli @ederign Could the following, be tested in unit tests?
```
The test for this:

Should keep working:

    git clone http://user:password@localhost:8080/business-central-7.29.0.Final-wildfly14/git/space/repo
    git clone ssh://dora@localhost:8001/space/repo

What should not work:

    git clone git://localhost/space/repo

```

**Comment by domhanak** [comment]
@porcelli You targeted `disable-git-push` branch, build checks won't work

**Pull request closed without merging**
