### PR TITLE
RHPAM-2867: Pie chart return error when a column use integer number (#1070)

### PR DESCRIPTION
**Pull request by akumar074**
* Added check for possible cast to number

(cherry picked from commit e6366b5956cae80c923e5f7e18a58ebe7e52b546)

**JIRA**: [RHPAM-2867](https://issues.redhat.com/browse/RHPAM-2867)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by jesuino — APPROVED** [review]
LGTM

**Comment by sthundat** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Review by sthundat — APPROVED** [review]
LGTM

**Pull request merged**
