### PR TITLE
[7.52.x] AF-2862: Decoupled REST Request Executor Service

### PR DESCRIPTION
**Pull request by adrielparedes**
Cherry Picked from: https://github.com/kiegroup/appformer/pull/1151

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by tomasdavidorg** [comment]
@adrielparedes Shouldn't this be also cherry pick for AF-2822 (https://github.com/kiegroup/appformer/pull/1129)? I think some of the changes are missing.

**Comment by adrielparedes** [comment]
@tomasdavidorg yes, I need to do some other cherry-picks, and I will do them today

**Comment by adrielparedes** [comment]
This PR is wrong, I will send a new PR

**Pull request closed without merging**
