### PR TITLE
[7.5.1] Backport: JBPM-8780, JBPM-8825, JBPM-8784

### PR DESCRIPTION
**Pull request by caponetto**
**Jira**: [RHPAM-2308](https://issues.jboss.org/browse/RHPAM-2308)

**Backport**: 
- [JBPM-8780](https://issues.jboss.org/browse/JBPM-8780)
- [JBPM-8825](https://issues.jboss.org/browse/JBPM-8825)
- [JBPM-8784](https://issues.jboss.org/browse/JBPM-8784)

**Related PRs**:
- https://github.com/kiegroup/appformer/pull/816
- https://github.com/kiegroup/kie-wb-common/pull/2938

### CODE REVIEW

**Comment by caponetto** [comment]
Hi @marcuscarvalho 
I've backported your fixes to branch 7.26.x
Can you please take a look?

**Comment by marcuscarvalho** [comment]
Hi @caponetto 
Looks good to me. Thank you.

**Comment by caponetto** [comment]
Jenkins retest this please

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Can you guys take a look at this backport, please?
@adrielparedes 
@domhanak

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@tomasdavidorg Could you please take a look at this?  Are there two separate issues backported here or am I missing something?

**Comment by caponetto** [comment]
@domhanak 
All three issues are related to [RHPAM-2308](https://issues.jboss.org/browse/RHPAM-2308).
If you prefer, I can close the PRs and open 3 separated ones.

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unrelated test failure.

**Pull request merged**
