### PR TITLE
[DROOLS-4083] After asset renaming, column width is automatically changed

### PR DESCRIPTION
**Pull request by yesamer**
To resolve the issue, I changed the `SaveAndRenameCommandBuilder` to launch a command BEFORE the saveAndRename call is invoked. In this way, it's possibile to add a command witch synchronizes the columns widths from front-end model to back-end model.

@jomarko @gitgabrio @danielezonca

Related PR: https://github.com/kiegroup/drools-wb/pull/1227

### CODE REVIEW

**Comment by yesamer** [comment]
> See my review [kiegroup/drools-wb#1227 (review)](https://github.com/kiegroup/drools-wb/pull/1227#pullrequestreview-285927658)



> See my review [kiegroup/drools-wb#1227 (review)](https://github.com/kiegroup/drools-wb/pull/1227#pullrequestreview-285927658)

@jomarko You can find my reply in the same link :)

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by danielezonca** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Hi, can you please merge it in master? Thanks!

**Pull request merged**
