### PR TITLE
AF-1900: Make jest-junit report more jenkins friendly

### PR DESCRIPTION
**Pull request by domhanak**
@tiagobento @ederign please take a look and merge if ok

### CODE REVIEW

**Comment by domhanak** [comment]
Basically, the problem is the current `names` and `classnames` and `testsuitenames` won't get recognized by our tooling.

**Comment by tiagobento** [comment]
@domhanak I'd just put a comment on "titleTemplate" function telling what the names look like now and what the added code does to them. Other than that, looks good to me :)

**Comment by ederign** [comment]
@tiagobento can you please take a look on this?

**Comment by domhanak** [comment]
@tiagobento @ederign added the comment, merge asap please

**Pull request merged**
