### PR TITLE
[AF-2151] Modify asset Save button behavior and presentation

### PR DESCRIPTION
**Pull request by gabriel376**
**[AF-2151](https://issues.jboss.org/browse/AF-2151) Modify asset Save button behavior and presentation**

Peek 2019-08-29 21-34

* Depends on https://github.com/kiegroup/kie-wb-common/pull/2849
* Depends on https://github.com/kiegroup/jbpm-designer/pull/864
* Depends on https://github.com/kiegroup/drools-wb/pull/1229

### CODE REVIEW

**Comment by manstis** [comment]
Just a comment - it's not my intention to review, I'll leave that to the foundation team - should the drop-down component have `.dropdown-toggle-split` CSS assigned? See https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns (to reduce the _width_ of the dropdown component).

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hi @gabriel376, I can see the change only for Data object asset. Is it intended or all assets should have the two options how to save them?

**Comment by gabriel376** [comment]
Hi @tomasdavidorg, I think the two save buttons should be present for all assets. Let me know which assets does not have the additional save button.

@ederign please confirm this information.

Thanks!

**Comment by gabriel376** [comment]
Hi @tomasdavidorg ,
I confirmed with Eder that all assets must have these two Save buttons.
Please let me know what assets does not have this new feature.

Thank you

**Comment by tomasdavidorg** [comment]
Hi @gabriel376,

image
Assets which have two save buttons:
- Data object

image
Assets which have only one save button (All assets with exception of Data object):
- Business Process
- Business Processes (legacy)
- DMN
- DRL
- DSL Definition
- Enumeration
- Form Modeler
- Globals Definitions
- Guided Decision Tables
- Guided-Decision-Table-Graphs
- Guided Decision Trees
- Guided-Rules
- Guided Rule Templates
- Guided Score Cards
- Solver configuration
- Test Scenarios
- Test Scenarios (Legacy)
- Work Item Definitions

**Comment by gabriel376** [comment]
PR updated with following changes:
* implement dual save button for all assets
* add margin-right to save button

Peek 2019-09-11 20-06

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
@gabriel376 I think the css class `dropdown-toggle-split` wasn't applied as expected, could you check that please?

**Comment by dgutierr** [comment]
@gabriel376 mind to add @lclay2 as a reviewer please and not merge under she approves?

**Comment by gabriel376** [comment]
Pushed new commit to remove CSS class `dropdown-toggle-split` as it is not part of patternfly

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by lclay2** [comment]
Thanks for the video above, adding space. Looks consistent with my understanding of the changes.

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
@gabriel376 Looks like the test failures are related with these changes, could you check please?

**Comment by gabriel376** [comment]
@paulovmr the broken test cases are fixed, see https://github.com/kiegroup/drools-wb/pull/1229/commits/a55268a9661d091744cedb380b1afc65a364402c

**Comment by gabriel376** [comment]
@tomasdavidorg, thanks for pointing it out!

I pushed a new commit to implement the same feature for Restore Button.
Please test, review and let me know if I missed anything.

Thank you!

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
Hi @tomasdavidorg can you please take a look at this?

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
@gabriel376 There is an error during full downstream build
`15:54:57 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project drools-wb-guided-dtable-editor-client: Compilation failure
15:54:57 [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/appformer-downstream-pullrequests/downstream-repos/drools-wb/drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java:[722,37] method restoreToCurrentVersion in class org.uberfire.ext.editor.commons.client.history.VersionRecordManager cannot be applied to given types;
15:54:57 [ERROR]   required: boolean
15:54:57 [ERROR]   found: no arguments
15:54:57 [ERROR]   reason: actual and formal argument lists differ in length`

Could you please take a look?

**Comment by gabriel376** [comment]
Hi @tomasdavidorg 
I fixed this by pushing a new commit to https://github.com/kiegroup/drools-wb/pull/1229
Thank you!

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hello @gabriel376,
there is another error during the full downstream build.
`[ERROR] /home/tdavid/Data/Projects/kiegroup/jbpm-designer/jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java:[165,25] cannot find symbol
[ERROR]   symbol:   variable saveWithComments
[ERROR]   location: class org.jbpm.designer.client.DesignerPresenter
[ERROR] /home/tdavid/Data/Projects/kiegroup/jbpm-designer/jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java:[169,75] incompatible types: org.uberfire.mvp.ParameterizedCommand<java.lang.Boolean> cannot be converted to org.uberfire.mvp.Command
[ERROR] /home/tdavid/Data/Projects/kiegroup/jbpm-designer/jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java:[796,38] cannot find symbol
[ERROR]   symbol:   variable saveWithComments
[ERROR]   location: class org.jbpm.designer.client.DesignerPresenter
`

**Comment by gabriel376** [comment]
Hi @tomasdavidorg,

Where did you get this error message ?
Everything is working fine for me.
There are 4 pull requests in different branches, so the build just work if all repositories are in sync:
* https://github.com/kiegroup/appformer/pull/783
* https://github.com/kiegroup/kie-wb-common/pull/2849
* https://github.com/kiegroup/jbpm-designer/pull/864
* https://github.com/kiegroup/drools-wb/pull/1229

**Comment by tomasdavidorg** [comment]
Hi @gabriel376,
sorry I didn't notice that the jbpm-designer repo is not rebased. I was able to build it locally. The two problems are fixed now. Thanks.

I have found another "hidden" editors which don't have two buttons. If you open Project explorer you will find these files:
- project.imports (External imports) - Only Save button is visible but after click dialog 'Save with Comments' is displayed
- pom.xml (Text editor) - Only Save button is visible but after click dialog 'Save with Comments' is displayed

I go through the workbench and that should be all I hope.

One more thing is Settings tab in project view. If you click on the Save button, you will see the 'Save with Comments' dialog. Is it intended? The history of the settings is saved and visible only if the repository is cloned, so this is probably ok. Just asking if this should be somehow involved.

**Comment by gabriel376** [comment]
Hi @tomasdavidorg,

Thanks for your exhaustive tests!
Could you please provide more details about how to access these "hidden" editors on Project Explorer ?
Regarding the Save Pop Up on Settings screen, this is correct, since we changed the pop up style.

**Comment by tomasdavidorg** [comment]
Hi @gabriel376,

to access the Project Explorer you must have at least one asset inside your project. Then open the asset and on the left side of the screen you will see a hidden dock.

Screenshot from 2019-10-11 10-31-52

Open the dock, click on the cog icon and select Repository view.

Screenshot from 2019-10-11 10-33-04

Then you can see the assets.

Screenshot from 2019-10-11 10-33-13

**Comment by gabriel376** [comment]
Hi @tomasdavidorg,
I just pushed https://github.com/kiegroup/kie-wb-common/pull/2849/commits/17fd992e3fd676037a5f1eedcea5377a7d21ec09 to impl that
Thank you!

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
@tomasdavidorg can you please review this and reply it on JIRA? https://issues.jboss.org/browse/AF-2151

**Comment by tomasdavidorg** [comment]
Thanks @gabriel376. Looks good to me.

**Comment by tomasdavidorg** [comment]
One more thing. There are some test failures (not the selenium). Could you please take a look at them. They seem to be related.

**Comment by gabriel376** [comment]
@tomasdavidorg,
Broken test cases are fixed, see https://github.com/kiegroup/drools-wb/pull/1229/commits/039d176ad59c94e3e6f2e39d2f91c60827fc95f6

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Pull request merged**
