### PR TITLE
Sonar blocker fixes round 1

### PR DESCRIPTION
**Pull request by domhanak**
Fixes couple of blockers from - https://sonarcloud.io/project/issues?id=org.uberfire%3Auberfire-parent&open=AWQnNkiDbXXTsx7OMm_N&resolved=false&severities=BLOCKER&types=BUG
to start increasing our mark from E to something green.

@triceo @ederign @tomasdavidorg @barboras7 
Please take a look.

### CODE REVIEW

**Comment by ederign** [comment]
@domhanak I would gently ask this to wait until we have the full downstream working again.

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
`org.jbpm.executor.cdi.CDISimpleExecutorTest.org.jbpm.executor.cdi.CDISimpleExecutorTest` is the only failure and it fails for some time. Imho this is OK to merge.

**Comment by domhanak** [comment]
@ederign see my previous comment

**Pull request merged**
