### PR TITLE
JBPM-6824: Forms & Stunner - Improve the usability for task' actors fields

### PR DESCRIPTION
**Pull request by pefernan**
This PR adds the ability to add dynamically new entries to the LiveSearchDropDown by setting a new type of LiveSearchService.

A video demo (in Stunner): https://issues.jboss.org/secure/attachment/12433115/actors-form-field.mp4

@dgutierr @jsoltes could you please review?

This PR is a part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/253
https://github.com/kiegroup/kie-wb-common/pull/1525

### CODE REVIEW

**Comment by ederign** [comment]
@jsoltes can you please take a look on this?

**Comment by pefernan** [comment]
@ederign it still nets some time to get reviewed. Thanks to this PR we found a big issue on stunner that needs to be fixed too (on the kie-wb-common PR)

**Comment by ederign** [comment]
@pefernan please mention me here as soon as this is ready for review!

**Comment by pefernan** [comment]
@ederign now it should be ready. The only problem is the downstream build that breakes because of unrelated issues :S

**Comment by pefernan** [comment]
@ederign ready to merge!

**Comment by pefernan** [comment]
@ederign could you please merge this PR and also https://github.com/kiegroup/kie-wb-common/pull/1525

See you after my PTO :)

**Pull request merged**
