### PR TITLE
AF-2789 | update logic to remove 'refs/' from file tree so that it do…

### PR DESCRIPTION
**Pull request by lukearmitage**
…esn't split branch names containing `/`

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://issues.redhat.com/browse/AF-2789)

I would appreciate if someone would help find a test I can modify to prove this fix 🙂

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by ederign — CHANGES_REQUESTED** [review]
Hi @lukearmitage thanks for your contribution! 

Before reviewing it, can you please add test coverage for your change?

Thanks

**Comment by lukearmitage** [comment]
> Hi @lukearmitage thanks for your contribution!
> 
> Before reviewing it, can you please add test coverage for your change?
> 

Hi Eder,

I was unable to find any tests that directly call the method I changed - I'll take another look but I would appreciate any pointers towards test classes that test this functionality.

Thanks

**Comment by adrielparedes** [comment]
@lukearmitage but I still think that we need a few tests for that `removeRefsFromTree` method. You can convert it to protected and create a single test just to that one.

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@lukearmitage something we will also need is to have the commits squashed please

**Comment by barboras7** [comment]
jenkins run fdb

**Comment by barboras7** [comment]
jenkins run fdb

**Comment by barboras7** [comment]
jenkins run fdb

**Comment by barboras7** [comment]
jenkinse execute fdb

**Comment by barboras7** [comment]
jenkins execute fdb

**Comment by FireBurn** [comment]
Does that look ok?

**Comment by barboras7** [comment]
Hi @lukearmitage,

I tried to reproduce this issue but I was not able to. Is this issue related to Business Central or Eclipse tooling as well? Please, provide the exact steps to reproduce for this issue.

**Comment by FireBurn** [comment]
How did you try and reproduce this issue?

**Comment by FireBurn** [comment]
To clarify, GibLab is our source or truth, it's set to sync to out BC when changes are pushed to it

https://*****:*****@{bcurl}/business-central/git/{group}/{project}

Most of our branches contain "/", either "team/" or "feature/" when these are sync'd to an extra branch is created in BC  

For example is we had "example/branch1" updated in GitLab and sync'd to BC an almost empty branch would be created with the name "branch1"

 It would have the following commits:

```
commit fd8c000fa92de5b76c6a64be2d0df4cfb492452f (remote/branch1, branch1)

Author: system <>

Date:   Tue Jan 26 13:08:48 2021 +0000

 

   

{/project.repositories}
 

commit 8509e6eb4c765e8eaaa00370d49f7276242405e0

Author: system <>

Date:   Tue Jan 26 13:08:42 2021 +0000

 

    Creating PathImpl{uri='default://branch1@project.name.bpm/name-of-kjar/project.repositories', fileName='project.repositories', attrs={}}...

```


The newly created project.repositories file would only contain:

 
`<project-repositories> <repositories/></project-repositories>`

You said you couldn't reproduce this, could you step me through how you're trying to reproduce it?

**Comment by barboras7** [comment]
Thank you @FireBurn for your explanation. I understand the issue that you are struggling with. I have one question still regarding "To clarify, GibLab is our source or truth, it's set to sync to out BC when changes are pushed to it". How is it set to sync to the BC? 

AFAIK, business central is able to use githooks to push the changes to the remote repositore after a commit/push but has no capacity to pull the changes from a remote repository. What is your setup?

**Comment by FireBurn** [comment]
The bit that doesn't work is the push from Gitlab

From a repo in GitLab:

Settings > Repository > Mirroring repositories 

Enter the repo address of BC project with the user name Infront of the server name 

e.g. https://githuser@{bcurl}/business-central/git/{group}/{project}

Mirror direction: Push

Authentication method: Password

Password: gituser password

The click mirror repository

Once this is set up, and changes made to GitLab will be automatically pushed to BC, there is a 5 minute cool down between pushes though 

If a branch contains a ”/" in the name, when it's pushed to BC you'll see the extra branch being created

**Comment by barboras7** [comment]
Thank you for the explanation @FireBurn.

@adrielparedes @ederign the issue seems to be fixed by this pull request. Could anyone from Engineering take a look at the changes in the code? 

It is possible to reproduce the issue also without GitLab and with business central running locally. I provided the steps to reproduce in the original Jira.

**Review by barboras7 — APPROVED** [review]

**Comment by adrielparedes** [comment]
For me is ok now, but lets make FDB to work, I will run the tests now, thanks @FireBurn and @barboras7

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
Jenkins run cdb

**Comment by lukearmitage** [comment]
hey, any movement on this? :)

**Comment by adrielparedes** [comment]
Sorry @lukearmitage I will get this moving again. Lets start with the tests

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
There is one FDB test failing that could be potentially related with your code. Could you please check it?

` org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
 Error Details
Cannot deploy business-monitoring-webapp.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"business-monitoring-webapp.war\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@49696dbd
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@49696dbd
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@1556bd7c
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://system/system) found."}}}}`

**Comment by lukearmitage** [comment]
@adrielparedes yep, can do. I'm assuming that test is in a downstream project as I can't find it in the AF workspace, and I can't see any of the Checks listed on this PR. Do you know which project I should be taking a look at?

**Comment by adrielparedes** [comment]
@lukearmitage here is the Starcktrace we got: https://gist.github.com/adrielparedes/1b2a6dcdf06c9fb6d61b5bad38776148

And the project is business-monitoring-webapp in kie-wb-distribution. 

Thanks!

**Comment by FireBurn** [comment]
> There is one FDB test failing that could be potentially related with your code. Could you please check it?
> 
> ```
>  org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
>  Error Details
> Cannot deploy business-monitoring-webapp.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"business-monitoring-webapp.war\".WeldStartService" => "Failed to start service
>     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@49696dbd
>     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@49696dbd
>     Caused by: java.lang.reflect.InvocationTargetException
>     Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@1556bd7c
>     Caused by: java.lang.reflect.InvocationTargetException
>     Caused by: org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://system/system) found."}}}}
> ```

Is that a new failure?

**Comment by adrielparedes** [comment]
@FireBurn I didn't see that around before, but we need to confirm

**Comment by FireBurn** [comment]
Was the failing test new?

**Comment by adrielparedes** [comment]
@lukearmitage @FireBurn any news?

**Comment by FireBurn** [comment]
@adrielparedes news? No we've not heard anything back since the last time. I'm still entirely unsure if the regression mentioned above was even related to this change or cause by something newer being added elsewhere 

It's now been 4 month since this pull request was submitted, we're running this patch locally and it's prevented a pretty annoying bug

**Comment by adrielparedes** [comment]
@FireBurn That is why I'm asking for news. If you see FDB, and Downstream compile are red. I asked you and @lukearmitage to confirm because idk if that problem is from the code you wrote or if it came from any other place, but still no answer, and tests are still red. I can't merge something that is not ok until we are sure that regression is not related. If you guys can make those test green or demonstrate the problem is not related to your code I will merge.

**Comment by lukearmitage** [comment]
Hi @adrielparedes, I will try to get some time to run the affected test in the next week or so.

**Comment by adrielparedes** [comment]
@lukearmitage great, once you confirm everything is ok we will be ready to merge, thanks!

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
Jenkins run cdb

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
Jenkins run cdb

**Comment by adrielparedes** [comment]
jenkins run fdb

**Comment by adrielparedes** [comment]
@lukearmitage just checking why FDB didn't work, once it is green or errors not related will merge. Keep you posted

**Review by adrielparedes — APPROVED** [review]

**Comment by adrielparedes** [comment]
@ederign this is ready to merge, the failing tests are not related.

**Pull request merged**
