### PR TITLE
[7.59.x] RHPAM-3845 : Imported projects not visible after migration from RHPAM 6.4 to 7.11

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Cherry-pick of: https://github.com/kiegroup/appformer/pull/1190

[RHPAM-3462](https://issues.redhat.com/browse/RHPAM-3462)
[RHPAM-3845](https://issues.redhat.com/browse/RHPAM-3845)

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
jenkins do cdb

**Comment by tomasdavidorg** [comment]
jenkins do fdb

**Comment by tomasdavidorg** [comment]
jenkins do cdb

**Comment by tomasdavidorg** [comment]
jenkins do cdb

**Review by RishiRajAnand — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
@RishiRajAnand @dgutierr CDB passed. FDB error is not related. I think it is ready to merge.

**Pull request merged**
