### PR TITLE
[7.14.x] JBPM-7990: Missing filters after redirection between Manage screens

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/appformer/pull/546

@nmirasch @cristianonicolai @ederign could any of you take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@domhanak who is the best qe for this?

**Comment by nmirasch** [comment]
Just in case the full downstream fails, I have put the generated wars including the fix,  to be able to verify at least the behaviour  in https://drive.google.com/drive/folders/18UzmGAlcL_F28OMn7PBNqVx7wz0yoeXM?usp=sharing 
@jsoltes I hope this helps to check navigation between console screens works again (for example "View tasks" from a process instance have to add a filter "Process Instance Id:X" ),  Thanks!

**Comment by jsoltes** [comment]
@nmirasch thank you! going to try this out with Selenium tests that were failing on this.

**Comment by mbiarnes** [comment]
@jsoltes Please let me know when this was tested and we can merge this.

**Comment by jsoltes** [comment]
@mbiarnes @pefernan Selenium tests passed. Now just waiting for Pere to add unit tests...

**Comment by pefernan** [comment]
@jsoltes thanks! working...

**Comment by pefernan** [comment]
@ederign @jsoltes @nmirasch @cristianonicolai added missing test!

**Comment by jsoltes** [comment]
Just wanted to add my approval, but I see it's already merged. :D Anyway, the tests look good as well.  :+1:

**Pull request merged**
