### PR TITLE
[DO NOT MERGE] AF-2832: Conscious language initiative appformer

### PR DESCRIPTION
**Pull request by akumar074**
**Thank you for submitting this pull request**

**JIRA**: 
[AF-2832](https://issues.redhat.com/browse/AF-2832)
[AF-2829](https://issues.redhat.com/browse/AF-2829)

**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-soup/pull/217
* https://github.com/kiegroup/kie-wb-playground/pull/116
* https://github.com/kiegroup/optaplanner-wb/pull/400
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1708
* https://github.com/kiegroup/kie-wb-common/pull/3661
* https://github.com/kiegroup/drools-wb/pull/1508
* https://github.com/kiegroup/jbpm-designer/pull/912
* https://github.com/kiegroup/jbpm-wb/pull/1508
* https://github.com/kiegroup/kie-wb-distributions/pull/1117

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run cdb

**Review by tiagobento — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Pull request closed without merging**
