### PR TITLE
updated to use jboss-ip-bom 8.1.0.CR2

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
merge together with
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/812
https://github.com/kiegroup/kie-soup/pull/51

**Comment by mareknovotny** [comment]
@mbiarnes is errai upgraded to 8.1.0.CR2 too?

**Comment by mbiarnes** [comment]
@mareknovotny it is: https://github.com/errai/errai/pull/356

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@kris @mareknovotny @ederign tests fail also in kieAllBuild master 
nothing to do with the update

**Pull request merged**
