### PR TITLE
AF-2689: Implement internal components structure

### PR DESCRIPTION
**Pull request by jesuino**
**JIRA**:

[AF-2689](https://issues.redhat.com/browse/AF-2689)

Part of an ensemble. Merge with:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1522

Internal Components Structure
--

In this PR we introduce the capability of providing internal components. Internal components are built using the same external API, but it is served from inside Dashbuilder/Business Central, from server side in a JAR!

The goal is provide something that we will and maintain in future releases, like heatmap. For now we only provide a small component called "logo", which allow users to place images on a page.

Check the internal component in action:

internal_Components

For more information please check the JIRA associated with this PR.

Thanks!

### CODE REVIEW

**Comment by jesuino** [comment]
Hello @caponetto and @sthundat 

Could you please verify this big PR? 

@tiagobento would you please check the Javascript project and provide guidance about it? Please see dashbuilder/dashbuilder-shared/dashbuilder-js - it was based on appformer-js

@Ginxo Hello! I know that it appformer-js a plugin you created was used (locktt) I removed this from this project because it was leading me to different problems. Kindly bear in mind that this project exists and you may have to use your plugin here as well. 


Thank you all!

**Comment by barboras7** [comment]
Hi @jesuino,
after a discussion with Savitha, who is quite busy with some other tasks, I reassigned the review to myself. I should be able to start reviewing this PR later this week. I hope that's fine for you :slightly_smiling_face:

**Comment by jesuino** [comment]
Hello @barboras7 

That's fine. 

I finished the JS API and added to this PR - it presents no functional change, but it will be the base for the heatmap component, which I am working on right now!

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by barboras7** [comment]
jenkins execute fdb

**Comment by barboras7** [comment]
Hi @jesuino,
I started looking into the code but also wanted to do the manual verification at the same time. I am having issues with building the .war file locally, it's failing on some dependencies and I was not able to fix them. Do you, by any chance, have a working .war file with this feature? Thanks

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
Hello @barboras7 

I triggered a new build and if tomorrow it is not done I will build a local one and send you both BC and DB

Thanks!

**Comment by barboras7** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by Ginxo** [comment]
@jesuino sorry, I missed this PR. Did you finally remove `locktt` here? 
Please don't merge until we clarify this ^

**Comment by jesuino** [comment]
Hello @Ginxo ,

Thanks for the comment. 

Yes, I removed for now so I could proceed with the review process. 

I will add tomorrow and let you know the issues I was facing. Could the errors in CI servers be caused by the absence of `locktt`?

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdb/job/appformer-master.fdb/57/console

Tomorrow I will take a closer look.

**Comment by barboras7** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
Hi @Ginxo 

I added locktt again. The issue I have is that I can only build using maven and locktt when the repository is empty (node_modules deleted)  -and when I build with maven it breaks some modules. I really don't know why, but after building with maven some modules are empty and then I can't re-build. Is this an expected behavior? 

Thanks!

**Comment by jesuino** [comment]
Hello @barboras7  - I will build this anyway today to have bits for testing by Monday - I hope it is fine. Sorry the delay, I think that the build in CI servers will not happen due the absence of locktt, which I added only now.

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by barboras7** [comment]
Hello @jesuino,

no problem at all. Tomorrow is public holiday in Czech Republic, I'll take a look on Wednesday. Sorry for the trouble, I would have built the .war files myself but I am having issues with the build failing on my local with this PR.

**Comment by jesuino** [comment]
Hello @barboras7 

Thanks for your patience on this.

I built Business Central WebApp and Dashbuilder Runtime. The WAR files are available in:

https://drive.google.com/drive/folders/1WyqnYhcTxpAoCuCydorb4yPHb0TQG2nG?usp=sharing

I am also attaching a very sample dashboard with an internal component on it. Internal components are in "Components" group in Page Editor, but this will change when we introduce heatmaps, where we will place logo under Core components and create a new components category for Heatmaps.
[export_with_internal_comp.zip](https://github.com/kiegroup/appformer/files/5548973/export_with_internal_comp.zip)

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
With the help from @tiagobento we found that the issue is when installing lerna:

```
[INFO] npm ERR! code ECONNREFUSED
[INFO] npm ERR! errno ECONNREFUSED
[INFO] npm ERR! FetchError: request to https://registry.yarnpkg.com/lerna failed, reason: connect ECONNREFUSED 104.16.19.35:443
[INFO] npm ERR!     at ClientRequest.<anonymous> (/opt/tools/graalvm/languages/js/npm/node_modules/node-fetch-npm/src/index.js:68:14)
[INFO] npm ERR!     at ClientRequest.emit (events.js:223:5)
[INFO] npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:415:9)
[INFO] npm ERR!     at TLSSocket.emit (events.js:223:5)
[INFO] npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
[INFO] npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[INFO] npm ERR!     at process.processTicksAndRejections (internal/process/task_queues.js:81:21)
[INFO] npm ERR!  FetchError: request to https://registry.yarnpkg.com/lerna failed, reason: connect ECONNREFUSED 104.16.19.35:443
[INFO] npm ERR!     at ClientRequest.<anonymous> (/opt/tools/graalvm/languages/js/npm/node_modules/node-fetch-npm/src/index.js:68:14)
[INFO] npm ERR!     at ClientRequest.emit (events.js:223:5)
[INFO] npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:415:9)
[INFO] npm ERR!     at TLSSocket.emit (events.js:223:5)
[INFO] npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
[INFO] npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[INFO] npm ERR!     at process.processTicksAndRejections (internal/process/task_queues.js:81:21) {
[INFO] npm ERR!   message: 'request to https://registry.yarnpkg.com/lerna failed, reason: connect ECONNREFUSED 104.16.19.35:443',
[INFO] npm ERR!   type: 'system',
[INFO] npm ERR!   errno: 'ECONNREFUSED',
[INFO] npm ERR!   code: 'ECONNREFUSED',
[INFO] npm ERR!   stack: 'FetchError: request to https://registry.yarnpkg.com/lerna failed, reason: connect ECONNREFUSED 104.16.19.35:443\n' +
[INFO] npm ERR!     '    at ClientRequest.<anonymous> (/opt/tools/graalvm/languages/js/npm/node_modules/node-fetch-npm/src/index.js:68:14)\n' +
[INFO] npm ERR!     '    at ClientRequest.emit (events.js:223:5)\n' +
[INFO] npm ERR!     '    at TLSSocket.socketErrorListener (_http_client.js:415:9)\n' +
[INFO] npm ERR!     '    at TLSSocket.emit (events.js:223:5)\n' +
[INFO] npm ERR!     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
[INFO] npm ERR!     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
[INFO] npm ERR!     '    at process.processTicksAndRejections (internal/process/task_queues.js:81:21)'
[INFO] npm ERR! }
[INFO] npm ERR!
[INFO] npm ERR! If you are behind a proxy, please make sure that the
[INFO] npm ERR! 'proxy' config is set properly.  See: 'npm help config'
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/jenkins/.npm/_logs/2020-11-17T17_56_26_937Z-debug.log
[INFO] Install for [ 'lerna@latest' ] failed with code 1
```

We are working to fix it.

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Review by barboras7 — COMMENTED** [review]
Hi @jesuino,

sorry for the delay, we had some PRs for 7.9.1. I reviewed the PR and the feature seems to work well, I only have two observations and some small comments:

1. In the gif demonstrating the feature, in the properties that you can set, I can see width and height. In the .war file you provided, the Logo component has "CSS" instead of those two. Is this intentional or you just built the .war accidentally with other properties for the component?
Screenshot from 2020-11-20 13-44-34

2. I tried to put some other image instead of the Dashbuilder logo. This did not work for me. I used a svg image from the following link: [Red Hat logo](https://www.redhat.com/cms/managed-files/Brand_Standars-Red_Hat-_color_on-white.svg). Is this a bug or should this work differently?

**Comment by jesuino** [comment]
Hello @barboras7,

Thank you so much for your review. Indeed I think the WAR had the wrong component version packaged with it. Kindly check again the built Business Central WebApp from the FDB. With this you should be able to use the component in the final version, see:

image

Also, thanks for your suggestions, they all look good and I will be working on them on Monday.

**Comment by jesuino** [comment]
Hello @barboras7 I made the requested changes - thanks!

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute cdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by barboras7** [comment]
Hi William,

> Thank you so much for your review. Indeed I think the WAR had the wrong component version packaged with it. Kindly check again the built Business Central WebApp from the FDB. With this you should be able to use the component in the final version, see:
> 
> image
> 
> Please bear in mind that this logo component is simple an "img" tag, where the URL should be a public image URL and the width and height are the same CSS properties for the component.

I found out what was the issue with the component properties. To test the business central, I wanted to work both with external components and internal components, that's why I started the business central & dashbuilder runtime using:
`./standalone.sh -c standalone-full.xml -Ddashbuilder.components.dir=<pathToLocalCloneOfDashbuilderComponents> -Ddashbuilder.components.enable=true -Ddashbuilder.export.dir=/tmp/dashbuilder/models -Ddashbuilder.runtime.location=http://localhost:8080 -Ddashbuilder.runtime.multi=true` where pathToLocalCloneOfDashbuilderComponents is the path to the clone of [components](https://github.com/jesuino/dashbuilder-components). These components also have a "Logo" component and this situation was not handled properly (this explained why the URL for image did not work for me and I did not see the Heigth and Weight properties because I saw the properties of the Logo component from external components). Is there a way you could fix this? 

When I start the business central with `./standalone.sh -c standalone-full.xml -Ddashbuilder.export.dir=/tmp/dashbuilder/models -Ddashbuilder.runtime.location=http://localhost:8080 -Ddashbuilder.runtime.multi=true`, everything works fine.

**Review by caponetto — COMMENTED** [review]
Hi @jesuino, thanks for the PR and sorry for the delay!
I've left some comments, please check if they make sense.

**Comment by jesuino** [comment]
Hello @caponetto 

Welcome back - np about the delay, last weeks I struggled to fix JS build in CI server. Thanks for you review! I made all the changes, please let me know if I am missing something.

Hello @barboras7 

What a great catch, thanks! The issue is that we were loading external component first in the properties page and provided component asset in asset provider, resulting in a messed component. I made the following changes to prevent such problem:

1) Made sure that provided components is always loaded first - before external components - both in asset loader and in properties loader;
2) Changed provided component "logo" to "logo-provided" to reduce the risk of name conflcits.

If users still tries to override provided components using the same ID then the behavior is that internal components will be used instead their external one.

Notice that in my next PR I will be organizing provided components group: Logo will be in Core components and the new heatmaps components will have their own category.

Thanks again!

**Review by caponetto — APPROVED** [review]
LGTM!

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
Hello @barboras7 

Finally the build is ready - kindly me know our findings:

Business Central
 https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdb/job/appformer-master.fdb/69/artifact/kiegroup_kie-wb-distributions/business-central-parent/business-central-distribution-wars/business-central/target/business-central-7.47.0-SNAPSHOT-wildfly19.war

Dashbuilder Runtime
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/fdb/job/appformer-master.fdb/69/artifact/dashbuilder/dashbuilder-runtime/target/dashbuilder-runtime.war

**Comment by barboras7** [comment]
Thanks, @jesuino! Great job :tada:

**Review by barboras7 — APPROVED** [review]

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by barboras7** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
The test failures in FDB are not related:


```
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeDoesNotRequiresDeletionConfirmation
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeDoesNotRequiresDeletionConfirmation
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeDoesNotRequiresDeletionConfirmation
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeRequiresDeletionConfirmation
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeRequiresDeletionConfirmation
org.kie.workbench.common.dmn.client.canvas.controls.toolbox.DMNDeleteNodeToolboxActionTest.testOnMouseClickWhenNodeRequiresDeletionConfirmation
```

**Pull request merged**
