### PR TITLE
JBPM-7990: Missing filters after redirection between Manage screens

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@pefernan @cristianonicolai  I added this quick fix, restoring the previous PlaceRequest management to avoid the console screens broken navigation issue. Could you take a look? Thanks!

**Comment by pefernan** [comment]
Jenkins execute full downstream build please

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@cristianonicolai @nmirasch before merging this, we need qe approval and also tests. :(

**Pull request merged**
