### PR TITLE
AF-1875-Add string cut for breadcrumb Links and toolbar title

### PR DESCRIPTION
**Pull request by ohonchar**
Added string cut for breadcrumb Links to avoid breaking html layout due long names

### CODE REVIEW

**Comment by ederign** [comment]
@paulovmr could you please take a look on this?

**Comment by domhanak** [comment]
@tomasdavidorg could you please review this?

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by ohonchar** [comment]
Jenkins (please) execute full downstream build

**Comment by paulovmr** [comment]
@ohonchar Could you check if it is possible to use a more specific selector to avoid the '!important' usage?

**Comment by ohonchar** [comment]
> @ohonchar Could you check if it is possible to use a more specific selector to avoid the `!important` usage?

@paulovmr Yes you are right, it this selector it is enough to not specify `! important`

**Pull request merged**
