### PR TITLE
AF-2066: Project is not visible after more projects are created at the same time

### PR DESCRIPTION
**Pull request by pefernan**
Adding missing locks

Could you please review?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/740
https://github.com/kiegroup/kie-wb-common/pull/2753

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by ederign** [comment]
@pefernan you will update this PR right?

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
Aparently the test failures are unrelated, waiting for the review to merge

**Pull request merged**
