### PR TITLE
JBPM-8529: Designer - Migration path from the legacy process designer

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys , would you mind review this PR.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi @ederign would you mind add @hasys and @romartin or @cristianonicolai as reviewers for this PR please, sine nor of us has rights to set the reviwers in this repository.

Thanks!

**Comment by wmedvede** [comment]
looks like full downstream build is not taking last commits from related PRs, same error is happening

**Comment by wmedvede** [comment]
will rebase with master and do a forced push just for trying something different, the other alterntive suggested by @mbiarnes was to close this PR and open it again

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
@ederign please can you review this? it's urgent for our delivery for next release... thanks!

**Comment by ederign** [comment]
fails are not related.

**Pull request merged**
