### PR TITLE
AF-497:Latest Version selector set to "Version -1"

### PR DESCRIPTION
**Pull request by jsoltes**
This is a cherry-pick from master: https://github.com/kiegroup/appformer/pull/132.

@ederign @tomasdavidorg can you please review?

### CODE REVIEW

**Comment by ederign** [comment]
@jsoltes there is a comment from @manstis https://github.com/kiegroup/appformer/pull/132. Could you please take a look?

**Comment by jsoltes** [comment]
@manstis @ederign updated

**Comment by jsoltes** [comment]
@etirelli @krisv guys, what do you think? can we put this on 7.5 (master already merged)?

**Comment by krisv** [comment]
@jsoltes 7.5.x is locked down currently for blockers only.  This does not seem to be one imho, I would suggest we close this, given the fix is already on master.

**Pull request closed without merging**
