### PR TITLE
AF-553: Appformer showcase doesn't build

### PR DESCRIPTION
**Pull request by pefernan**
@ederign here you have

### CODE REVIEW

**Comment by ederign** [comment]
thanks @pefernan waiting for the build

**Comment by ederign** [comment]
java.lang.OutOfMemoryError

**Comment by ederign** [comment]
jenkins rebuild this

**Comment by ederign** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this please.

**Comment by ederign** [comment]
@pefernan as soon as I finish what I'm doing. i'll try and build it locally

**Comment by pefernan** [comment]
@ederign ok. It builds well on my computer. I think that jenkins needs a bigger ship.

**Comment by ederign** [comment]
@psiroky we are getting out of memory here. Maybe we need a bigger jenkins.

**Pull request merged**
