### PR TITLE
AF-574 : [Layout editor] Components disappear after moving

### PR DESCRIPTION
**Pull request by akumar074**
* Fixed Component disappear when moved out of ColumnWithComponent to its side or in the same column

### CODE REVIEW

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
@kkufova we are waiting for your review ;)

**Comment by kkufova** [comment]
@pefernan, I left QE in August last year, you'll have to manage without me. :-)

**Comment by pefernan** [comment]
@kkufova oh! I wasn't aware of that. I'll search for someone else. Thank you and good luck in your new adventures!

**Comment by barboras7** [comment]
@akumar074 thanks! works as expected :+1:

**Comment by pefernan** [comment]
@akumar074 great job again!

**Pull request merged**
