### PR TITLE
AF-2467 : Commit history in metrics does not get refreshed when using other than master branch

### PR DESCRIPTION
**Pull request by akumar074**
Ensemble:
[kie-soup#136](https://github.com/kiegroup/kie-soup/pull/136)
[kie-wb-common#3264](https://github.com/kiegroup/kie-wb-common/pull/3264)

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by RishiRajAnand** [comment]
@adrielparedes @akumar074  While this implementation associates data sets with current user branch, I suppose there might be several cases where this relation may not be useful.  For example, In space metrics screen,where we show all the metrics irrespective of user branch. IMHO we can also consider maintaining single dataset that contains all the branch metrics and let the clients (UI) filter the records they need. In this way, we can reuse the same data set for space metrics and project metrics (filtered by branch name).

@paulovmr wdyt ^?

**Comment by akumar074** [comment]
@RishiRajAnand I agree with the behavior you suggested for the single dataset. I have a few concerns here. When we create a new branch from a base branch, the new branch has commits of base branch as well. So we get to see a commit message redundantly on the commit history.

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
The implementation is changed so will raise a new PR.

**Comment by akumar074** [comment]
> @adrielparedes @akumar074 While this implementation associates data sets with current user branch, I suppose there might be several cases where this relation may not be useful. For example, In space metrics screen,where we show all the metrics irrespective of user branch. IMHO we can also consider maintaining single dataset that contains all the branch metrics and let the clients (UI) filter the records they need. In this way, we can reuse the same data set for space metrics and project metrics (filtered by branch name).
> 
> @paulovmr wdyt ^?

@RishiRajAnand As you pointed out that we should filter the data set on the client-side, I agree to it, It is a much simple solution than what I wanted to achieve here. I have raised a new PR for this.
About the duplication of commits in space metrics, I have filtered the dataset by master for all projects because it seems more appropriate to show only _"stable"_ commits there. 
@paulovmr WDYT^?
Thanks

**Pull request closed without merging**
