### PR TITLE
Project Cleanup. This test files are changed by ssh tests

### PR DESCRIPTION
**Pull request by ederign**
Pere, this is some leftovers from ssh. After running the tests I got:

image

The changes are related with ssh key last usage timestamp.

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished. 5032 tests run, 11 skipped, 0 failed.

**Comment by pefernan** [comment]
@ederign ouch! The problems is that this files are overwriten during _SSHKeyAuthenticatorImplTest_, we could remove them but also we should remove them after the test to make sure they are no longer there. I think we should change the tests, do you mind if I change the test to clear everything WDYT?

**Comment by ederign** [comment]
@pefernan  thanks for the instructions. I'll update the PR.

**Comment by ederign** [comment]
@pefernan better?

**Comment by ederign** [comment]
please jenkins retest this

**Comment by kiereleaseuser2** [comment]
Build finished. 5038 tests run, 11 skipped, 0 failed.

**Pull request merged**
