### PR TITLE
RHPAM-2317 - Users cannot find the properties menu unless it's pointed out to them

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/RHPAM-2317

This adds the possibility of having different labels and tooltips for the docks which was not supported.

Video (Updated - Tooltip shows Properties instead of Open properties panel):
https://drive.google.com/file/d/1AbYsbhHG2RfZJjtSz3Kb2cKyQJG6tLsB/view?usp=sharing

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by kywalker-rh** [comment]
@Josephblt Please include a video or screenshots showing the implementation, and tag myself and @lclay2 as reviewers so we can make sure to review it.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @romartin. @jomarko asked to be included in PR review, can you do that for us? Thanks.

**Comment by kywalker-rh** [comment]
Hello @Josephblt. This looks great, but after seeing it live the "Open Properties Panel" tooltip on the icon seems a bit awkward when the panel is already open. Can you change it back to "Properties Panel"? That way it works for both the open and the closed state. If you let me know when that's done I'll approve it. Thanks!

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hey @kywalker-rh. Changed the tooltip back to Properties. New video in the PR description. Thx

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @jomarko @kywalker-rh 

Thanks for reviewing and approving this ticket! Anyway, plz it's also missing your review feedback in the following PR, both are related -> https://github.com/kiegroup/kie-wb-common/pull/2993

Can you please also check it? 

Thx in advance!

**Comment by romartin** [comment]
hey @ederign , missing your review here, you want to collaborate? Otherwise we'll merge this soon as it's starting to be urgent. Thx!

**Comment by ederign** [comment]
@romartin sorry for the delay! feel free to merge it

**Pull request merged**
