### PR TITLE
[AF-2328] Removing BasicAuthorizationPrincipal from user's groups

### PR DESCRIPTION
**Pull request by caponetto**
**Task**: [AF-2328](https://issues.jboss.org/browse/AF-2328)

**Related PRs**:

- https://github.com/kiegroup/appformer/pull/837
- https://github.com/kiegroup/droolsjbpm-integration/pull/1936
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1101

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
I'm checking the failures.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
Green, yay!

**Pull request merged**
