### PR TITLE
JBPM-9688 Popup window for user/password not opened while executing b…

### PR DESCRIPTION
**Pull request by bxf12315**
…usiness-central REST API through swagger

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[JBPM-9688](https://issues.redhat.com/browse/JBPM-9688)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

*https://github.com/kiegroup/kie-wb-distributions/pull/1093
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by barboras7** [comment]
jenkins run fdb

**Review by barboras7 — APPROVED** [review]

**Review by akumar074 — APPROVED** [review]
LGTM. Thanks for the PR @bxf12315

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by nmirasch — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Review by cristianonicolai — CHANGES_REQUESTED** [review]
As discussed, https://github.com/kiegroup/kie-wb-distributions/pull/1093 would be a better alternative to simply protect the endpoint

**Pull request closed without merging**
