### PR TITLE
[AF-1221]: Modified elastic search get mapping to avoid NPE

### PR DESCRIPTION
**Pull request by adrielparedes**
Mappings were not loaded ok, I changed some mapper, to have the correct mapping from elasticsearch.

@ederign @jhrcek would you mind to review it?

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@ederign @jhrcek https://drive.google.com/drive/folders/1Qj3cNioSJf8mmR6n72fSljXiD9K1nhte?usp=sharing

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@jhrcek changes done, let's wait for full build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@jhrcek yes I did, I test it completely, let me try it again but that is really weird!

**Comment by jhrcek** [comment]
Full dowstream build should now be fixed, so 
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@jhrcek actually it fails with lucene too, and I didn't modified any Lucene class... I will try to check this with master, to be sure that master is not broken

**Comment by ederign** [comment]
@jhrcek the error is fixed here: https://github.com/kiegroup/kie-wb-common/pull/1892

**Comment by jhrcek** [comment]
@adrielparedes now that Eder's PR is merged, could you please rebase on master and rerun the build?

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
There are 3 kinds of failures in the full downstream build job:

1) Most are from org.jbpm.test and org.kie.server.integrationtests - these have recently very rich failure history - basically [most of the red stuff](http://janhrcek.cz/random-failures/#/) in my report. I saw Karel created PR in droolsjbpm-integration with attempt to stabilize this. @sutaakar can you please share what's the progress of that PR?

2) [KieDefaultMavenCompilerTest.buildWithAllDecoratorsTest](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/appformer-downstream-pullrequests/128/testReport/org.kie.workbench.common.services.backend.compiler.nio.kie/KieDefaultMavenCompilerTest/buildWithAllDecoratorsTest/) - most tests from this class [have been recently stabilized](http://janhrcek.cz/random-failures/#/class/org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest) by @cnicolai (good job!). The failure in this build seems to be fresh, comming [from this line](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/compiler/nio/kie/KieDefaultMavenCompilerTest.java#L365) but not sure if it might be related to this PR. @desmax any idea about why this one is failing?

3) [ScorecardReaconCodeTest](https://github.com/kiegroup/drools/blob/master/drools-scorecards/src/test/java/org/drools/scorecards/ScorecardReasonCodeTest.java#L218) seems to started failing just now [failure history](http://janhrcek.cz/random-failures/#/class/org.drools.scorecards.ScorecardReasonCodeTest/method/testReasonCodesCombinations) . I see this was last changed by @tzimanyi - Tibor could you please take a look at why this started failing?

**Comment by sutaakar** [comment]
@jhrcek The PR on master branch is merged. However some other issues still persist. Recently @MarianMacik  looks on this trying to stabilize remaining tests.
It seems that the profile skipping unstable tests is still missing in downstream build despite of being merged in https://github.com/kiegroup/kie-jenkins-scripts/pull/234.

**Comment by jhrcek** [comment]
@adrielparedes So tested this locally and it seems to work fine. I executed one library-heavy selenium test suite and only found one difference in behaviour (compared to standard Lucene indexing), which is causing test failures.

Steps: Import "Employee Rostering" example project and enter "Employee.java" (with extension). With Lucene this finds the asset, but with ELS it doesn't. But when you write just "Employee" (without extension) it works the same in both (finds all assets with Employee in name). What do you think about this behaviour?

indexing_els
indexing_lucene

**Comment by adrielparedes** [comment]
@jhrcek thanks for the review! Yes please, open a new Jira for that, it seems like an issue with Analyzers in ES.

**Comment by jhrcek** [comment]
@adrielparedes FYI reported here https://issues.jboss.org/browse/RHPAM-1249

**Comment by ederign** [comment]
@adrielparedes this is good to go?

**Comment by adrielparedes** [comment]
@ederign yes, there is another issue that is not a blocker and is going to be solved in other PR

**Pull request merged**
