### PR TITLE
AF-1678: Fix illegal transitive dependencies errors

### PR DESCRIPTION
**Pull request by jhrcek**
@ederign please check. There are tons of enforcer errors about illegal transitive dependencies.
Apart from spamming build console, the real issue with these missing dependencies is, that you can't really reliably build individual modules in separation (unless you did so before, which may not be the case when you checkout a different branch).

EDIT: I consider this ready for review. See individual commit messages (click the `...` after the commit message in the list below) for details about warnings being fixed. The PR build and full downstream are passing (with couple of unrelated kie-server integration test failures). I'm willing to rebase this (after Adriels wildfly and infinispan PRs are merged). The only thing I'm not sure about are dependency scopes (I'm sure I should have used `provided` scope at certain points, but not sure when - please point it out in the review).

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Only one test failure:
```
org.junit.ComparisonFailure: expected:<476871[68000]L> but was:<476871[92576]L>
	at org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest.simpleTests(SimpleUnixFileStoreTest.java:42)
```
This test has [a history of failures](http://janhrcek.cz/random-failures/#/class/org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest/method/simpleTests) due to these tining issues.

jenkins retest this

**Comment by jhrcek** [comment]
Rebased onto master and fixed enforcer errors introduced by experimental feature framework changes (CC @pefernan - see my last commit - but no worries, in this PR I'm enabling automated check that will prevent these kinds of mistakes in the future)

**Comment by ederign** [comment]
@jhrcek it's ok to you to wait for next sprint do merge this?

**Comment by jhrcek** [comment]
@ederign sure, no problem. I consider this lower priority compared to other tasks (EAP 7.2 testing et.)

**Comment by jhrcek** [comment]
Rebased onto master and fixed enforcer errors introduced by infinispan indexing changes (CC @adrielparedes - see my last commit - but no worries, in this PR I'm enabling automated check that will prevent these kinds of mistakes in the future)

**Comment by ederign** [comment]
thanks @jhrcek. I just want to avoid more rebases :-)

**Comment by jhrcek** [comment]
Rebased onto master and fixed enforcer errors introduced by ssh keystore stuff

**Comment by jhrcek** [comment]
Rebased onto master after wildfly14 merged. Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
PR build passed with green.
Full downstream only has couple of failures that are currently on master + couple of "classical" kie-server integration test failures.

@ederign could you please review this?

**Comment by jhrcek** [comment]
I had to rebase onto master again, because merging Max's last PR introduced new enforcer errors about illegal transitive dependencies. @ederign or @porcelli could you please merge this before any other PR? Because without the enforcer check enabled in the main pom, almost every PR merged introduces new errors :-)

**Pull request merged**
