### PR TITLE
Sonar blocker fixes round 2

### PR DESCRIPTION
**Pull request by domhanak**

### CODE REVIEW

**Comment by domhanak** [comment]
jenins execute compile downstream build

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
@ederign Hi, what do you want me to add so it is mergable?
I am working on adding some coverage where missing when I have time.

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by ederign** [comment]
Closing due to inactivity. @domhanak feel free to reopen it if necessary.

**Pull request closed without merging**
