### PR TITLE
AF-2760 : Permission configured in business-central is not applied when doing git clone from outside of BC

### PR DESCRIPTION
**Pull request by RishiRajAnand**
(cherry picked from commit e8a33e7cd2d5d9c4bcfcdeb20e9e69a67cac70bf)

**Thank you for submitting this pull request**

**RHPAM-3375**: _https://issues.redhat.com/browse/RHPAM-3375_ 
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/kie-wb-common/pull/3681/files
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by Srihari1192 — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Ensemble PR https://github.com/kiegroup/kie-wb-distributions/pull/1123

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by adrielparedes — APPROVED** [review]

**Comment by adrielparedes** [comment]
@RishiRajAnand let me know when FDB is green so I can merge

**Pull request merged**
