### PR TITLE
[7.39.x] DROOLS-5442: Asume column visibility during keyboard navigation

### PR DESCRIPTION
**Pull request by jomarko**
This is a cherry-pick of #998

### CODE REVIEW

**Comment by jomarko** [comment]
TODO include also #1006 cherry-pick

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
failed tests:
```
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testGetKieServerState
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testSignalToProcess
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testGetProcessIds
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testInsertGetDeleteFact
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testSetGetGlobal
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testFireAllRules
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testRuleEvaluationService
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testGetKieServerInfo
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testGetKieServerInfo
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testGetKieServerInfo
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testDeactivateActivateContainer
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testDeactivateActivateContainer
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testDeactivateActivateContainer
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testListContainers
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testListContainers
org.kie.camel.container.integration.tests.remote.KieServicesClientIntegrationTest.testListContainers
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.hacep.RemoteKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithClassTypeTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithNamedQueryTest
org.kie.hacep.SnapshotOnDemandTest.createSnapshotOnDemandTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askAKafkaConsumerWithoutServerUpTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askASnapshotWithoutServerUpTest
org.kie.hacep.core.infra.utils.ConsumerUtilsCoreTest.lastEventWithoutKafkaUpTest
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.spring.tests.KieSpringEnvironmentTest.org.kie.spring.tests.KieSpringEnvironmentTest
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryEnvTest.testPersistenceTimer2
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryEnvTest.testPersistenceWorkItemsUserTransaction
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryEnvTest.testPersistenceWorkItems
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryEnvTest.testPersistenceSubProcess
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryTest.testPersistenceTimer2
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryTest.testPersistenceWorkItemsUserTransaction
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryTest.testPersistenceSubProcessWithListeners
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryTest.testPersistenceWorkItems
org.kie.spring.tests.persistence.JPASingleSessionCommandServiceFactoryTest.testPersistenceSubProcess
org.kie.spring.tests.persistence.VariablePersistenceStrategyEnvTest.testPersistenceVariables
org.kie.spring.tests.persistence.VariablePersistenceStrategyEnvTest.testTransactionsRollback
org.kie.spring.tests.persistence.VariablePersistenceStrategyTest.testPersistenceVariables
org.kie.spring.tests.persistence.VariablePersistenceStrategyTest.testTransactionsRollback
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testSignalToProcess
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testGetProcessIds
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testInsertGetDeleteFact
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testSetGetGlobal
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testFireAllRules
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testRuleEvaluationService
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testGetProcessDefinition
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.ProcessClientIntegrationTest.testStartProcess
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
failed tests:
```
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.hacep.RemoteKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithClassTypeTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithNamedQueryTest
org.kie.hacep.SnapshotOnDemandTest.createSnapshotOnDemandTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askAKafkaConsumerWithoutServerUpTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askASnapshotWithoutServerUpTest
org.kie.hacep.core.infra.utils.ConsumerUtilsCoreTest.lastEventWithoutKafkaUpTest
```

**Comment by jomarko** [comment]
@mareknovotny the failed test `org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT` seems be unrelated . Could we please merge? What is your opinion?

**Comment by Rikkola** [comment]
We had green in master. Can't really see how this change breaks anything here.

**Comment by mareknovotny** [comment]
the relevant jobs are:

- Linux - Full Downstream Build — Build finished. 64671 tests run, 693 skipped, 1 failed. 
- Pull Request Execution — Build finished. 6160 tests run, 15 skipped, 1 failed.

**Pull request merged**
