### PR TITLE
KOGITO-2076: Open File API

### PR DESCRIPTION
**Pull request by caponetto**
**Task**: [KOGITO-2076](https://issues.redhat.com/browse/KOGITO-2076)

**Related PRs**:
- https://github.com/kiegroup/appformer/pull/961
- https://github.com/kiegroup/kogito-tooling/pull/151

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Test failures are unrelated
```
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testReadinessCheck
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testLivenessCheck
```

**Comment by manstis** [comment]
My only comment would be that @pefernan started [this](https://github.com/kiegroup/appformer/tree/ea7f7bd119dc1cca1f02fbe362c9c4f5f42e1aab/appformer-client-api) module for (kogito) client services.

**Pull request merged**
