### PR TITLE
AF-1452 Backend of Dynamic POM Dependencies framework [Broken]

### PR DESCRIPTION
**Pull request by desmax74**
replaced by https://github.com/kiegroup/appformer/pull/521

### CODE REVIEW

**Comment by domhanak** [comment]
What is the difference from #489 ?

**Comment by desmax74** [comment]
@domhanak is the AF-1451, with the additions/changes of the AF-1452, like a set of types (JPS, TEST, OPTAPLANNER....) and the rules about versions of deps explained in the AF-1452

**Comment by domhanak** [comment]
@desmax74 Ah okay, thanks :) Where do we want to handle this then? I would really like to see af-1451 finished before we go  over next issue.

**Comment by desmax74** [comment]
@domhanak Are aligned but this is to avoid stop in the progress on this DynamicPomDependencies

**Comment by jhrcek** [comment]
@desmax74 26 000 added lines? This PR seems broken. Maybe a merge problem?

**Comment by desmax74** [comment]
@jhrcek yep a wrong nightly merge :(

**Pull request closed without merging**
