### PR TITLE
AF-2887: Test failure on daily-build on main branch

### PR DESCRIPTION
**Pull request by akumar074**
* Fixed host in GeneralPathImpl

**JIRA**: 
[AF-2887](https://issues.redhat.com/browse/AF-2887)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
@akumar074 This is the fix for 
`org.kie.workbench.common.services.datamodel.backend.server.ModuleDataModelConcurrencyTest.testConcurrentResourceUpdates` ?

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
> @akumar074 This is the fix for
> `org.kie.workbench.common.services.datamodel.backend.server.ModuleDataModelConcurrencyTest.testConcurrentResourceUpdates` ?

Yes, This is the fix.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
@tiagobento fdb test failure unrelated to the change.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
