### PR TITLE
BAPL-1148: upgraded jboss-ip-bom

### PR DESCRIPTION
**Pull request by mbiarnes**
updated to org.dom4j
upgraded to jboss-jaxrs-api_2.1_spec

### CODE REVIEW

**Comment by mbiarnes** [comment]
merge together..:
https://github.com/errai/errai/pull/378
https://github.com/kiegroup/kie-soup/pull/82
https://github.com/kiegroup/appformer/pull/648
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/933
https://github.com/kiegroup/optaplanner/pull/488
https://github.com/kiegroup/jbpm/pull/1450
https://github.com/kiegroup/droolsjbpm-integration/pull/1749
https://github.com/kiegroup/kie-wb-common/pull/2501
https://github.com/kiegroup/jbpm-wb/pull/1305
https://github.com/kiegroup/jbpm-work-items/pull/97
https://github.com/kiegroup/kie-docs/pull/1414
https://github.com/kiegroup/kie-wb-distributions/pull/883
https://github.com/kiegroup/optaweb-employee-rostering/pull/229

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@ederign IMO the failed tests have nothing to do with appformer
@mareknovotny  wdyt?

**Comment by mareknovotny** [comment]
I would agree with @mbiarnes 

What changes are you requesting, @ederign ?

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@ederign @mareknovotny 
the two test that fail here are from org.kie.server.integrationtests.router.rest.KieServerRouterUnavailabilityIntegrationTest.testReactToUnavailableServersInRouterContainerBasedOperationsInvalidHost
This is not related to appformer.
The Linux and compile downstream worked - they are green. 
Can't this PR be merged? WdyT?

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@ederign we have another run with different test failures:
New test from faiure from https://github.com/kiegroup/kie-wb-common/commit/26882ab1b4835895381ed4ac8a525310235c706f author @elguardian fails:    

> org.kie.workbench.common.screens.server.management.backend.StandaloneControllerMultinodeIT.testAvailableRestEndpoint
This could be caused by not connected instance in CI test.

And

> org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.className: kie-page (tried for 30 second(s) with 500 milliseconds interval)

which doesn't seem related to jax-rs upgrade as all other REST endpoint tests ran ok.

I think we are ready to merge this and all related PRs.

**Comment by mbiarnes** [comment]
@mareknovotny @ederign +1

**Comment by ederign** [comment]
Could be, let's do another try: Jenkins execute full downstream build

**Comment by pszubiak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
I would say don't hold this merging, tests for Karaf are now fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1777.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
ok, so 2 fixed and previously failed tests disappeared and exchanged to just 1 failed which we haven't seen before here:
```
org.kie.server.common.rest.NoEndpointFoundException: No available endpoints found
	at org.kie.server.integrationtests.common.KieServerContainerListFilteringIntegrationTest.setupKieServer(KieServerContainerListFilteringIntegrationTest.java:75)
```
I will merge the set of PRs if anyone objects again it.   @ederign ?

**Comment by mbiarnes** [comment]
+1 for merging them

**Pull request merged**
