### PR TITLE
AF-2418: Add logic for editor page index computation

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:
https://github.com/kiegroup/kie-wb-common/pull/3123

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko I'll test manually, was there a scenario where the setup failed that I could try out?

**Comment by jomarko** [comment]
@Rikkola thank you for checking

The scenario this PR ensemble fixes is:
- Open a dmn file
- Save more than 7 versions
- Expand version dropdown from toolbar
- Click view all

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
