### PR TITLE
[7.52.x] AF-2859: Exclude D3 Geo conflicting dependencies

### PR DESCRIPTION
**Pull request by almope**
**Thank you for submitting this pull request**

https://issues.redhat.com/browse/AF-2859

Backport into 7.52.x for https://github.com/kiegroup/appformer/pull/1147

### CODE REVIEW

**Comment by almope** [comment]
jenkins execute fdb

**Comment by almope** [comment]
jenkins retest this

**Comment by almope** [comment]
jenkins execute fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
merging as the KafkaProxySampleTest is random flaky test

**Pull request merged**
