### PR TITLE
DROOLS-5128: Update com.google.elemental2 and com.google.jsinterop versions

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble:
- kiegroup/droolsjbpm-build-bootstrap#1259
- kiegroup/kie-wb-common#3256

For more details see https://issues.redhat.com/browse/DROOLS-5128

### CODE REVIEW

**Comment by yesamer** [comment]
@jomarko Therefore... API is changed for google.elemental2. Excellent work, I'll check it.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by ederign** [comment]
@jesuino  can you please take a look at this?

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Hello,

I tried in the past to update Elemental as well, see [1].

I found that a few refact would be required, in the FDB we can see some of it:

```
15:03:15 [INFO]       [ERROR] Errors in 'jar:file:/home/jenkins/.m2/repository/com/google/elemental2/elemental2-dom/1.0.0-RC1/elemental2-dom-1.0.0-RC1.jar!/elemental2/dom/Element.java'
15:03:15 [INFO]          [ERROR] Line 326: The method asBoolean(Element.SetAttributeNSValueUnionType) is undefined for the type Js
15:03:15 [INFO]          [ERROR] Line 331: The method asDouble(Element.SetAttributeNSValueUnionType) is undefined for the type Js
15:03:15 [INFO]          [ERROR] Line 364: The method asBoolean(Element.SetAttributeValueUnionType) is undefined for the type Js
15:03:15 [INFO]          [ERROR] Line 260: The method asString(Element.ReplaceWithNodesUnionType) is undefined for the type Js
15:03:15 [INFO]          [ERROR] Line 374: The method asString(Element.SetAttributeValueUnionType) is undefined for the type Js
15:03:15 [INFO]          [ERROR] Line 336: The method asString(Element.SetAttributeNSValueUnionType) is undefined for the type Js
```

So, in another words, updating it would require some refactor in many different projects. If FBD is green and the BC app looks good after the PR so I would approve it.

[1] https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/913

**Comment by yesamer** [comment]
> There are errors in the FDB, would you please check it ?

@jesuino I checked, the reason of the errors are explained here https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1259

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute compile downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Ready for re-review

**Comment by jomarko** [comment]
@jesuino @barboras7 @ederign just a friendly reminder, if you have a moment to review this ensemble. We overcame  kogito dev preview cut off so the risk shouldn't be high now.

**Comment by jomarko** [comment]
@ederign please could you take a look on this PR?

**Pull request merged**
