### PR TITLE
AF-1184: [Layout editor] Moving any component on canvas breaks Layout editor

### PR DESCRIPTION
**Pull request by pefernan**
@kkufova @dgutierr could you please take a look?

### CODE REVIEW

**Comment by dgutierr** [comment]
@pefernan Can you please rename it to https://issues.jboss.org/browse/AF-1184

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
unrelated tests failure

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
