### PR TITLE
[7.67.x-blue] RHPAM-4315: EventSource yarn.lock update (#1277)

### PR DESCRIPTION
**Pull request by akumar074**
(cherry picked from commit d0e73ada766de16de27ce9b91edd0d538ced1006)

**Thank you for submitting this pull request**

**JIRA**: [RHPAM-4315](https://issues.redhat.com/browse/RHPAM-4315)

**referenced Pull Requests**: 
* https://github.com/kiegroup/appformer/pull/1294

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me when the build is green.

**Comment by mareknovotny** [comment]
fdb was timed out

jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
[org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest.org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x-blue/job/fdb/job/appformer-7.67.x-blue.fdb/12/testReport/org.kie.wb.test.rest.functional/SpacesScreenServiceIntegrationTest/org_kie_wb_test_rest_functional_SpacesScreenServiceIntegrationTest/) failed

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Hi @adrielparedes We have green build and QE approval on this PR. Can you please take a look and merge if it's okay?
Thanks

**Pull request merged**
