### PR TITLE
[AF-1250] False positive conflict Error dialog shown every time when …

### PR DESCRIPTION
**Pull request by ederign**
…page is deleted

### CODE REVIEW

**Comment by ederign** [comment]
@jhrcek thanks for reporting this.

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
I think this PR is safe to merge - the three failures are unrelated: 
-2 failures in downstream job are jbpm related
-1 is related to maven compiler tests

<details>
  <summary>details</summary>
  <pre>
Unexpected HTTP response code when requesting URI 'http://localhost:43611/kie-server-services/services/rest/server/containers/definition-project/tasks/1131/states/completed?auto-progress=true'! Error code: 500, message: "Unexpected error during processing: Unable to commit transaction"

org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://localhost:43611/kie-server-services/services/rest/server/containers/definition-project/tasks/1131/states/completed?auto-progress=true'! Error code: 500, message: "Unexpected error during processing: Unable to commit transaction"
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.createExceptionForUnexpectedResponseCode(AbstractKieServicesClientImpl.java:617)
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPutRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:379)
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPutRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:357)
	at org.kie.server.client.impl.UserTaskServicesClientImpl.completeAutoProgress(UserTaskServicesClientImpl.java:118)
	at org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest.testSLAonProcessViolated(SLAComplianceIntegrationTest.java:79)
----------------------------
 org.kie.server.integrationtests.jbpm.admin.ProcessInstanceAdminServiceIntegrationTest.testErrorHandlingFailedToSignal[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43611/kie-server-services/services/rest/server'}]
 Error Details

Unexpected HTTP response code when requesting URI 'http://localhost:43611/kie-server-services/services/rest/server/containers/definition-project/processes/definition-project.signalprocess/instances'! Error code: 500, message: "Unable to create response: Unable to commit transaction"

 Stack Trace

java.lang.AssertionError: Unexpected HTTP response code when requesting URI 'http://localhost:43611/kie-server-services/services/rest/server/containers/definition-project/processes/definition-project.signalprocess/instances'! Error code: 500, message: "Unable to create response: Unable to commit transaction"
	at org.junit.Assert.fail(Assert.java:88)
	at org.kie.server.integrationtests.jbpm.admin.ProcessInstanceAdminServiceIntegrationTest.testErrorHandlingFailedToSignal(ProcessInstanceAdminServiceIntegrationTest.java:313)
----------------------------
 org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithAllDecoratorsTest
 Stack Trace

java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithAllDecoratorsTest(KieDefaultMavenCompilerTest.java:365
  </pre>
</details>

In the meantime I'm going to troubleshoot KieDefaultMavenCompilerTest as that one has been failing quite often recently.

**Comment by ederign** [comment]
thanks @jhrcek

**Pull request merged**
