### PR TITLE
JBPM-6108 ObjectSelector should not appear in Form-modeler editor

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING**: to be merged with https://github.com/kiegroup/kie-wb-common/pull/1024 and https://github.com/kiegroup/kie-wb-common/pull/1025

Added ObjectSelector related code, which was removed from kie-wb-common

@pefernan @jsoltes can you give a look?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
merge after https://github.com/kiegroup/appformer/pull/94

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by ederign** [comment]
the build is broken. this should be merged first https://github.com/kiegroup/appformer/pull/96

**Comment by pefernan** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this

**Comment by pefernan** [comment]
@manstis could you merge this please? this will be one more free beer on Bcn for you ;)

**Comment by manstis** [comment]
@pefernan As far as I can tell I've merged all applicable PRs.

**Pull request merged**
