### PR TITLE
AF-2150: updating freemarker to 2.3.28

### PR DESCRIPTION
**Pull request by mareknovotny**
related PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1028

https://issues.jboss.org/browse/AF-2150

### CODE REVIEW

**Comment by mareknovotny** [comment]
@ederign yes, I am aware of AF-600. So far we tried to use in product the version without that patch and haven't seen those symptoms. It could be more about we reduced also the parallel threads on our CI

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Standard tests run failed on
`org.uberfire.java.nio.fs.jgit.JGitFileSystemProviderConcurrentOperationsTest.testConcurrentGitCreation`, not sure if this is related to Freemarker

Compile downstream complains about several enforcer errors:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-direct-dependencies) @ kie-server-spring-boot-sample ---
[INFO] Analyze dependencies of artifact 'org.kie:kie-server-spring-boot-sample:jar:7.26.0-SNAPSHOT'.
[INFO] Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/kie-server-spring-boot-sample/7.26.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/kie-server-spring-boot-sample/7.26.0-SNAPSHOT/maven-metadata.xml (1.7 kB at 8.6 kB/s)
[INFO] Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/kie-server-spring-boot-sample/7.26.0-SNAPSHOT/kie-server-spring-boot-sample-7.26.0-20190805.151323-1.jar
[INFO] Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/kie-server-spring-boot-integ-tests-sample/7.26.0-SNAPSHOT/kie-server-spring-boot-integ-tests-sample-7.26.0-20190805.151506-1.jar (106 MB at 5.6 MB/s)
[WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 26 illegal transitive type dependencies in artifact 'org.kie:kie-server-spring-boot-integ-tests-sample:jar:7.26.0-SNAPSHOT':
1.) org.kie.server.services.api.KieServer
2.) org.slf4j.Logger
3.) org.slf4j.LoggerFactory
4.) org.springframework.beans.factory.annotation.Autowired
5.) org.springframework.boot.CommandLineRunner
6.) org.springframework.boot.SpringApplication
7.) org.springframework.boot.autoconfigure.SpringBootApplication
8.) org.springframework.context.ConfigurableApplicationContext
9.) org.springframework.context.annotation.Bean
10.) org.springframework.context.annotation.Configuration
11.) org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder
12.) org.springframework.security.config.annotation.authentication.configurers.provisioning.InMemoryUserDetailsManagerConfigurer
13.) org.springframework.security.config.annotation.authentication.configurers.provisioning.UserDetailsManagerConfigurer
14.) org.springframework.security.config.annotation.authentication.configurers.provisioning.UserDetailsManagerConfigurer$UserDetailsBuilder
15.) org.springframework.security.config.annotation.web.HttpSecurityBuilder
16.) org.springframework.security.config.annotation.web.builders.HttpSecurity
17.) org.springframework.security.config.annotation.web.configuration.EnableWebSecurity
18.) org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
19.) org.springframework.security.config.annotation.web.configurers.CsrfConfigurer
20.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$AuthorizedUrl
21.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$ExpressionInterceptUrlRegistry
22.) org.springframework.security.config.annotation.web.configurers.HttpBasicConfigurer
23.) org.springframework.security.crypto.factory.PasswordEncoderFactories
24.) org.springframework.security.crypto.password.PasswordEncoder
25.) org.springframework.security.web.firewall.HttpFirewall
26.) org.springframework.security.web.firewall.StrictHttpFirewall

[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-blacklisted-dependencies) @ kie-server-spring-boot-integ-tests-sample ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) @ kie-server-spring-boot-integ-tests-sample ---
[INFO] Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/kie-server-spring-boot-sample/7.26.0-SNAPSHOT/kie-server-spring-boot-sample-7.26.0-20190805.151323-1.jar (108 MB at 5.6 MB/s)
[WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 19 illegal transitive type dependencies in artifact 'org.kie:kie-server-spring-boot-sample:jar:7.26.0-SNAPSHOT':
1.) org.springframework.beans.factory.annotation.Autowired
2.) org.springframework.boot.SpringApplication
3.) org.springframework.boot.autoconfigure.SpringBootApplication
4.) org.springframework.context.ConfigurableApplicationContext
5.) org.springframework.context.annotation.Configuration
6.) org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder
7.) org.springframework.security.config.annotation.authentication.configurers.provisioning.InMemoryUserDetailsManagerConfigurer
8.) org.springframework.security.config.annotation.authentication.configurers.provisioning.UserDetailsManagerConfigurer
9.) org.springframework.security.config.annotation.authentication.configurers.provisioning.UserDetailsManagerConfigurer$UserDetailsBuilder
10.) org.springframework.security.config.annotation.web.HttpSecurityBuilder
11.) org.springframework.security.config.annotation.web.builders.HttpSecurity
12.) org.springframework.security.config.annotation.web.configuration.EnableWebSecurity
13.) org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
14.) org.springframework.security.config.annotation.web.configurers.CsrfConfigurer
15.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$AuthorizedUrl
16.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$ExpressionInterceptUrlRegistry
17.) org.springframework.security.config.annotation.web.configurers.HttpBasicConfigurer
18.) org.springframework.security.crypto.factory.PasswordEncoderFactories
19.) org.springframework.security.crypto.password.PasswordEncoder

[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-blacklisted-dependencies) @ kie-server-spring-boot-sample ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) @ kie-server-spring-boot-sample ---
[INFO] Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/kie/keycloak-kie-server-spring-boot-sample/7.26.0-SNAPSHOT/keycloak-kie-server-spring-boot-sample-7.26.0-20190805.151410-1.jar (111 MB at 4.6 MB/s)
[WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 29 illegal transitive type dependencies in artifact 'org.kie:keycloak-kie-server-spring-boot-sample:jar:7.26.0-SNAPSHOT':
1.) org.keycloak.adapters.KeycloakConfigResolver
2.) org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver
3.) org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationProvider
4.) org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter
5.) org.kie.server.services.api.KieServer
6.) org.slf4j.Logger
7.) org.slf4j.LoggerFactory
8.) org.springframework.beans.factory.annotation.Autowired
9.) org.springframework.boot.CommandLineRunner
10.) org.springframework.boot.SpringApplication
11.) org.springframework.boot.autoconfigure.SpringBootApplication
12.) org.springframework.context.ConfigurableApplicationContext
13.) org.springframework.context.annotation.Bean
14.) org.springframework.context.annotation.Configuration
15.) org.springframework.security.authentication.AuthenticationProvider
16.) org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder
17.) org.springframework.security.config.annotation.web.HttpSecurityBuilder
18.) org.springframework.security.config.annotation.web.builders.HttpSecurity
19.) org.springframework.security.config.annotation.web.configuration.EnableWebSecurity
20.) org.springframework.security.config.annotation.web.configurers.CsrfConfigurer
21.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$AuthorizedUrl
22.) org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer$ExpressionInterceptUrlRegistry
23.) org.springframework.security.config.annotation.web.configurers.HttpBasicConfigurer
24.) org.springframework.security.core.authority.mapping.GrantedAuthoritiesMapper
25.) org.springframework.security.core.authority.mapping.SimpleAuthorityMapper
26.) org.springframework.security.core.session.SessionRegistry
27.) org.springframework.security.core.session.SessionRegistryImpl
28.) org.springframework.security.web.authentication.session.RegisterSessionAuthenticationStrategy
29.) org.springframework.security.web.authentication.session.SessionAuthenticationStrategy
```

So there were some troubles with cargo duplicated classes too and it is fixed in https://github.com/kiegroup/droolsjbpm-integration/pull/1889 so I will try to trigger tests again

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
```
Test Result ("2 neúspěšných / +2")

    org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
    org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest
```
First one fails on lucene classes not on classpath and second on some wrong setup of the test I believe. I contacted @jiripetrlik  to look at latter.

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@ederign just looking at old PRs and to support my upgrade please look at the previous discussion of Petr and ddekany. We don't need the forked freemarker version anymore as Freemarker 2.3.27 was fixed with workaround to java issues too, https://github.com/apache/freemarker/pull/37

**Comment by mareknovotny** [comment]
I think we are ready to merge this, the failed test was not related to the upgrade

**Comment by domhanak** [comment]
@mareknovotny I am not 100% sure that 29953 tests in FDB are all that needed to run. I can't check now, so I will rerun this. 
it should be ` Linux - full downstream — Build finished. 50555 tests run, 756 skipped, 0 failed.`
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@domhanak not sure what did you mean by that comment about  above ;)

> it should be Linux - full downstream — Build finished. 50555 tests run, 756 skipped, 0 failed.

you can for sure rerun the FDB.

**Comment by domhanak** [comment]
@mareknovotny I mean that the build stopped in the middle and didn't finish properly, If ti does the message here should look as mentioned before.

**Comment by domhanak** [comment]
FDB failed because of:
`ERROR] Failed to execute goal on project jira-workitem: Could not resolve dependencies for project org.jbpm.contrib:jira-workitem:jar:7.28.0-SNAPSHOT: Failure to find com.atlassian.jira:jira-rest-java-client:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
19:20:24 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jira-workitem: Could not resolve dependencies for project org.jbpm.contrib:jira-workitem:jar:7.28.0-SNAPSHOT: Failure to find com.atlassian.jira:jira-rest-java-client:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`

**Comment by domhanak** [comment]
@mbiarnes Could you please take a look at above FDB?

**Comment by domhanak** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by winklerm** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Pull request merged**
