### PR TITLE
RHPAM-4525 ElasticSearchIndexProvider few tests removed

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/RHPAM-4525

**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
what about finally removing ES completely @adrielparedes how big effort it would be?
Issues related to that dependency and its dependencies are more than just few. It could be even enough if we remove it from build and do not include in sources later.

**Comment by adrielparedes** [comment]
@mareknovotny I think the effort is minimal, something you and @Ginxo can do is to remove all dependencies from pom where that elasticsearch provider is included. Also there is an attribute to select which provider to use (is system property the user can set with the different providers: lucene, elastic, infinispan). 

But If you have the time I would vote to remove it from the code
@ederign wdyt?

**Comment by mareknovotny** [comment]
well, if the effort is minimal it is good to remove it now, because we saw repeated questions what and how it is used if not, we can spend time on something else ;)

So @Ginxo could you please remove it instead of tests, the modules from build reactor and then later also files from github?

**Comment by adrielparedes** [comment]
@Ginxo ping me anything you need!

**Pull request merged**
