### PR TITLE
JBPM-8127: TreeItem - support inserting child item at a given index

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , this pull request is to support the changes in PR [JBPM-8127](https://github.com/kiegroup/kie-wb-common/pull/2420#discussion_r250812567). Added the logic to insert an `item` in a given `index` in the `TreeItem`. Thanks.

**Comment by xiezhang7** [comment]
ok to test

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
@ederign can you do a quick review please? thanks!

**Pull request merged**
