### PR TITLE
[7.52.x] AF-2862: Decoupled REST Request Executor Service (#1151)

### PR DESCRIPTION
**Pull request by adrielparedes**
Backport from https://github.com/kiegroup/appformer/pull/1151

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by adrielparedes** [comment]
Jenkins retest this

**Comment by tiagobento** [comment]
jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]

**Comment by adrielparedes** [comment]
FDB Failing tests are not related
```
org.kie.server.integrationtests.optaplanner.OptaplannerIntegrationTest.initializationError
org.kie.server.integrationtests.optaplanner.jms.OptaPlannerJmsResponseHandlerIntegrationTest.initializationError
org.jbpm.workitem.springboot.samples.KafkaProxySampleTest.testKafkaWIHReconnect[0: SINGLETON]
```

**Review by RishiRajAnand — APPROVED** [review]

**Pull request merged**
