### PR TITLE
AF-2154: remove unnecessary OSGi support of uberfire-commons module

### PR DESCRIPTION
**Pull request by porcelli**
dependency:
 - https://github.com/kiegroup/drools/pull/2506

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins execute a full downstream build

**Comment by domhanak** [comment]
jenkins execute compile downstream build

**Comment by domhanak** [comment]
jenkins execute a full downstream build

**Comment by porcelli** [comment]
can we merge this?

**Comment by domhanak** [comment]
@porcelli I do not know much about this issue, but given the checks are green I can formally approve.

**Pull request merged**
