### PR TITLE
AF-1621: Import & index only specified branches when Importing remote repository

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/687
* https://github.com/kiegroup/kie-wb-common/pull/2597

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@paulovmr do you already fixed https://issues.jboss.org/browse/AF-1930 ?

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Hi @barboras7 , thanks for the review! 

About the master branch, I tried doing what you said, but disabling the option field that contains the master branch (which is what is possible to do with this component) gives the select an awkward behaviour, because when you try to click in a disabled option, the select dropdown just closes, which might be interpreted as a bug. With that said, I think it is more clear to let all options with the same behaviour, and validate if the master is selected.

I've added a title to the branch icon in the card, which shows what branches are selected when the mouse goes over it.

About having this feature when duplicating projects, I don't think it is necessary, because in this case the source project is already inside business central, so it makes sense for it to be fully copied.

jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unrelated test failure (selenium).

**Pull request merged**
