### PR TITLE
AF-1181: A tweak over sutaakar solution for AF-1181 issue. Now it may…

### PR DESCRIPTION
**Pull request by porcelli**
… use Artemis direct remote connection OR JNDI

### CODE REVIEW

**Comment by sutaakar** [comment]
Tried on EAP 7.1.1 with activemq-rar-5.15.3.rar against JBoss AMQ 7.1.0 and it seems to be working.
Just noticed one error message when logging into the Workbench - `Unable to complete your request. The following exception occurred: java.lang.NoSuchMethodError:org.uberfire.commons.cluster.ClusterParameters.isAppFormerClustered()Ljava/lang/Boolean;.`

**Comment by ederign** [comment]
@porcelli @sutaakar if this PR gets merged, can you please also update this [doc](https://docs.google.com/document/d/1oauuPcRhZtw6RldyAMBvF05y86ber8_EGnapuW24KwI/edit#heading=h.pg9bd4kyc61j) ?

**Comment by porcelli** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
@porcelli When I used Workbench from downstream build then I didn't see any error message, everything seems to be working.

**Comment by sutaakar** [comment]
Tried with both JNDI and REMOTE modes. Tested locks on process designer and it is working.

**Comment by porcelli** [comment]
failed test doesn't look like something impacted by this change

**Pull request merged**
