### PR TITLE
[7.67.x] apache.activemq.artemis moved to 2.19.1 (#1251)

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
`@github-actions Build Chain / ubuntu-latest - Java 11 - Maven (pull_request)` failed due to `gwt-maven-plugin` execution memory leak 
FDB test failure at `droolsjbpm-integration` not related with the change

**Comment by Ginxo** [comment]
@mareknovotny remove `do_not_merge` label whenever you consider

**Comment by mareknovotny** [comment]
that will happen after the branch is open for 7.13.1 bug fixes

**Comment by Ginxo** [comment]
Java 11 gwt memory issue

droolsjbpm-integration test failure at `org.kie.server.services.taskassigning.planning.TaskAssigningPlanningKieServerExtensionTest.initRuntimeClientWithKeyStore` 
```
Argument(s) are different! Wanted:
```

I would say it's not related with the change. @jesuino @RishiRajAnand @adrielparedes can you please confirm? Thanks.

**Comment by adrielparedes** [comment]
@Ginxo this will require an HA test, will come back with answers ASAP

**Comment by Ginxo** [comment]
thanks @adrielparedes

**Review by RishiRajAnand — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Hello @Ginxo @adrielparedes 
I tried the Artemis update available on the latest main(7.70). Running it on HA env, I did some basic sanity testing and it works fine. I could not see any issue in BC. I ran the mentioned failing test locally and it also passed.

**Comment by Ginxo** [comment]
> Hello @Ginxo @adrielparedes I tried the Artemis update available on the latest main(7.70). Running it on HA env, I did some basic sanity testing and it works fine. I could not see any issue in BC. I ran the mentioned failing test locally and it also passed.
thanks @akumar074!! :cupid: 

@adrielparedes @AntStephenson @rgdoliveira ok to merge?

**Comment by mareknovotny** [comment]
no, do not merge. the branch is not open for anything outside of coming release

**Comment by adrielparedes** [comment]
thanks @akumar074 and @tomasdavidorg for the testing, now we wait until we can merge

**Comment by Ginxo** [comment]
@mareknovotny can it be merged?
otherwise this https://github.com/kiegroup/appformer/pull/1274 has to be reverted

**Comment by mareknovotny** [comment]
we still need to wait for reopening the branch for merging. Is that #1274 related ? i think it is postgresl dependency uograde or not ?

**Pull request merged**
