### PR TITLE
[AF-1718] NullPointerException is thrown while creating multiple projects through curl command

### PR DESCRIPTION
**Pull request by elguardian**
Establishing order between workbench indexing and file system indexing

### CODE REVIEW

**Comment by elguardian** [comment]
@Rikkola wdyt ? problem here is that they are colliding.

**Comment by Rikkola** [comment]
Asking around for someone to test and review.

**Comment by Rikkola** [comment]
Ok @tomasdavidorg volunteered.

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
Hello @elguardian could you please give me more details of the issue and also on your solution?

it's not clear what you mean by: 

"Establishing order between workbench indexing and file system indexing" 

"problem here is that they are colliding."

**Comment by elguardian** [comment]
I am sequencing BatchIndex and the first time and setupWatchService is otherwise they clash in the beginning during fs creation as they manipulate the indexes at the same time.
The deletion event mentioned in the jira https://issues.jboss.org/browse/RHPAM-1713 is coming from the watch service.

**Comment by porcelli** [comment]
if @tomasdavidorg can't see it on master anymore, we should avoid merge this

**Pull request closed without merging**
