### PR TITLE
DROOLS-5521: Handle pressing TAB when editing last cell

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/DROOLS-5521

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
failed tests:
```
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
org.jbpm.kie.services.test.FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Failed tests

```
org.kie.maven.plugin.ExecModelParameterTest.testNoMavenWithoutDroolsModelCompilerOnClassPathDoNotRunExecModel[3.3.9]
org.kie.maven.plugin.ExecModelParameterTest.testNoMavenWithDroolsModelCompilerOnClassPathDoNotRunExecModel[3.5.0]
org.kie.maven.plugin.ExecModelParameterTest.testDefaultMavenWithDroolsModelCompilerOnClassPathRunsExecModel[3.5.0]
org.kie.server.integrationtests.common.KieServerIntegrationTest.initializationError
org.kie.karaf.itest.DecisionTablesIntegrationTest.testBasic
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[1]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[2]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[3]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[4]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[5]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[6]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[7]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[8]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[9]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[10]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[11]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[13]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[14]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[15]
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[18]
org.kie.karaf.itest.KieDMNKarafIntegrationTest.testDMNbasic
org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManagerWithPersistence
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.RuntimeManagerFeatureKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSession
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieBase
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSessionDefaultType
org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest.buildKieBaseFromSimpleGuidedDTable
org.kie.karaf.itest.WorkbenchModelsKarafIntegrationTest.buildKieBaseFromAdvancedDTableUsingFQCN
org.kie.karaf.itest.blueprint.KieBlueprintDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieElementsExistTest
org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieSessionOldPersonTest
org.kie.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieSessionYoungPersonTest
org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest.testStartProcess
org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest.testKieBaseUpdatedByScanNow
org.kie.karaf.itest.blueprint.KieBlueprintScannerReimportIntegrationTest.testKieBaseUpdatedByTimer
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest.testYoungPerson
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintCommandIntegrationTest.testOldPerson
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest.testFavouriteCheese
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintDTIntegrationTest.testNonFavouriteCheese
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest.testYoungPerson
org.kie.karaf.itest.camel.kiecamel.KieCamelBlueprintIntegrationTest.testOldPerson
org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest.testExecuteCommand
org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest.testGetProcessDefinition
org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest.testStartProcess
org.kie.karaf.itest.camel.kiecamel.KieCamelRemoteIntegrationTest.testListContainers
org.kie.karaf.itest.pmml.KiePmmlIntegrationTest.testSetup1
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jstastny-cz** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
failed tests:
```
org.kie.server.integrationtests.common.KieServerIntegrationTest.org.kie.server.integrationtests.common.KieServerIntegrationTest
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.server.integrationtests.taskassigning.TaskAssigningIntegrationTest.org.kie.server.integrationtests.taskassigning.TaskAssigningIntegrationTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
failed tests:
```
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46272/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46272/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46272/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.testTransactionExceptionHandlerInSubprocess[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
```

**Comment by jstastny-cz** [comment]
Failed tests are unrelated to the change - checking with the BC that has been built during the FDB.

**Comment by jstastny-cz** [comment]
Verified the fix in FDB too. Safe to merge.

**Pull request merged**
