### PR TITLE
AF-2424 : Issue with the group permissions for the Pages    

### PR DESCRIPTION
**Pull request by akumar074**
- Adding HomePage read access after a group is created.

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
Hi @akumar074 @barboras7, what's the expected behavior, please?
I've tested locally and it seems the issue still persists. Am I missing something?

**Comment by romartin** [comment]
Hey @caponetto @akumar074 @manstis 

I've created the PR that fixes the failed test case: https://github.com/kiegroup/lienzo-tests/pull/81

Sorry for the inconveniences!

**Comment by akumar074** [comment]
> Hi @akumar074 @barboras7, what's the expected behavior, please?
> I've tested locally and it seems the issue still persists. Am I missing something?

Hi @caponetto , the expected behaviour is that when you create a new group, it should have read permission to "Home" page by default. Currently newly created group does not have read permission for home page in the editor.

**Comment by barboras7** [comment]
@akumar074,
any estimate when the requested changes from @caponetto will be in? If the PR should be merged today, please run the FDB as soon as you push a commit with the changes

**Comment by barboras7** [comment]
As another PR for this issue was created [PR-896](https://github.com/kiegroup/appformer/pull/896) please, close this one.

**Pull request closed without merging**
