### PR TITLE
RHPAM-4315: EventSource yarn.lock update

### PR DESCRIPTION
**Pull request by akumar074**
<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Hi @adrielparedes @jesuino 
I tried direct updates in yarn.lock but that breaks the dashbuilder. Now, I updated the `webpack-cli` and `webpack-dev-server` version which uses the fixed versions of eventsource (1.1.1 & 2.0.2) separately. While testing locally I was able to create pages without error.
Please take a look once FDB is complete.
Thanks

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by jesuino** [comment]
Hello @akumar074 

Looks like the build is breaking on `dashbuilder-js`, but I could not find the root cause. I will fire a new build, please let me know if you see errors when build with full profile locally.

Thanks!

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@akumar074 I think there must be a problem with the PR because you are updating all the packages versions, can you please check?

**Comment by akumar074** [comment]
Okay, looks like some commits are slipped in the PR when I rebased the branch.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Hello @tomasdavidorg The FDB is green. Please take a look.

**Comment by tomasdavidorg** [comment]
@akumar074 there are conflict with the main branch.

**Review by tomasdavidorg — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by mareknovotny** [comment]
fdb passed so we can merge, right? cdb is not necessary needed to be green if FDB is ;)

**Comment by akumar074** [comment]
@jesuino @adrielparedes The QE has approved this PR, can we go ahead and merge this?

**Review by adrielparedes — APPROVED** [review]

**Pull request merged**
