### PR TITLE
AF-2116: Verify Async load of Projects and Spaces Cards

### PR DESCRIPTION
**Pull request by pefernan**
- Added listener to get notifications when the project indexing has started or finished

This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/755
https://github.com/kiegroup/kie-wb-common/pull/2794

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
@mareknovotny @ederign 
I saw this SonarCloud complaining about a new param in a constructor, but I think in this case is fine to have it as it is now.

In fact we already have other classes with larger num of args in constructor we do use to @Inject all the required components/services needed. Take a look on the related PR on kie-wb-common to see an example (which is not failing)

**Comment by adrielparedes** [comment]
+1 I think that code smell doesn't apply to our context. Also our code style is based in constructor parameters, so if we need to create a Parameters class, we will also have 8 parameters for its constructor

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
@tomasdavidorg thanks!

**Pull request merged**
