### PR TITLE
DROOLS-4319: [DMN Designer] Search feature - Implement search feature in the GDT graphs editor

### PR DESCRIPTION
**Pull request by danielzhe**
Part of an ensemble. This is are new PRs since the older was broken.
https://github.com/kiegroup/kie-wb-common/pull/2801
https://github.com/kiegroup/appformer/pull/759
https://github.com/kiegroup/drools-wb/pull/1206

### CODE REVIEW

**Comment by danielzhe** [comment]
@karreiro I guess is good now. I was investigating the minX and minY and I think that is not really required anymore. I didn't found any issue related to that.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by danielzhe** [comment]
@karreiro I think is good now.

**Pull request merged**
