### PR TITLE
AF-546: Reduce startup time of AppFormer apps and workbenches

### PR DESCRIPTION
**Pull request by mbarkley**
* Remove PlaceManagerActivityService
* Replace @AfterInitialization methods with @PostConstruct

### CODE REVIEW

**Comment by mbarkley** [comment]
Relates to:
* https://github.com/errai/errai/pull/267
* https://github.com/AppFormer/uberfire/pull/751
* https://github.com/dashbuilder/dashbuilder/pull/340
* https://github.com/kiegroup/guvnor/pull/464
* https://github.com/kiegroup/kie-wb-common/pull/937
* https://github.com/kiegroup/drools-wb/pull/533
* https://github.com/kiegroup/jbpm-form-modeler/pull/117
* https://github.com/kiegroup/kie-wb-distributions/pull/542
* https://github.com/kiegroup/optaplanner-wb/pull/181
* https://github.com/kiegroup/jbpm-wb/pull/764

**Comment by mbarkley** [comment]
Currently master is building in the repo. Looks like there was a change in kie-wb-common and this repo wasn't updated.

**Comment by pefernan** [comment]
@mbarkley seems that it's my fault. I'll try to fix it today. Sorry

**Comment by ederign** [comment]
I'm looking right now on Appformer build

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
trying locally

**Comment by mbarkley** [comment]
This last failure happened from a timeout while downloading a maven artifact. I have built this PR locally (with the changes in the linked PRs as well) and everything builds correctly.

**Comment by mbarkley** [comment]
Note that even if we try and rebuild this, the PR job won't build the related PRs because this repo is not in the list of blessed repos. So we should not wait for the PR build to go green before merging.

**Comment by ederign** [comment]
The Jenkins instance for appformer is having a bad day. (the last PR from Pere doesn't also build (out of memory)).

@manstis are you ok with merging this?

**Pull request merged**
