### PR TITLE
AF-1774: Removing GChartsRenderer (Google Charts)

### PR DESCRIPTION
**Pull request by jesuino**
Related PRs:

kiegroup/drools-wb#1101
kiegroup/jbpm-wb#1325
https://github.com/kiegroup/kie-wb-common/pull/2549
https://github.com/kiegroup/kie-wb-distributions/pull/903
https://github.com/kiegroup/optaplanner-wb/pull/332

### CODE REVIEW

**Comment by jesuino** [comment]
@ederign Would you please view this PR? It is the removal of gcharts completely from all webapps and showcases, also removing gcharts code.

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
@jesuino Could you please wait for my review? I won't be able to do it today but removing this feature will also impact our Selenium tests so I need to check it before it's merged.

**Comment by jesuino** [comment]
> @jesuino Could you please wait for my review? I won't be able to do it today but removing this feature will also impact our Selenium tests so I need to check it before it's merged.

Sure, no problem, I know the selenium tests checks a table generated by GCharts - let me know if you need any information from my side about C3. It generates the SVG directly, no data table, so you may need to read the chart SVG elements

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@barboras7 would you mind to take a look on this one?

**Comment by jesuino** [comment]
Hello @barboras7 

I added a table that exposed the dataset data. It is added right after the displayer. It should work for all charts. Please let me know if this table structure is fine for your tests, otherwise I can modify it. 

Notice the table is missing the series info (for example, the year) - this could be retrieved from the chart itself - if you want it to be in the table just let me know

image

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @jesuino,

thanks for providing the data table! It would be great if you could just switch the columns and rows of the table (see the attached screenshots). I believe that it is an easy fix and it would save a lot of time (I would not 
Screenshot from 2019-05-03 12-30-26
Screenshot from 2019-05-03 12-10-07

need to modify our testing framework so much). 

Also, if it is not going to take you a lot of time, you can add the above mentioned series info into the table as well.

Otherwise, the PR looks good, so :+1: when these small enhancements are in :blush:

**Comment by jesuino** [comment]
Hello @barboras7 Could you please let me know how should the table look like after adding the series? Thanks!

**Comment by barboras7** [comment]
Hello @jesuino,

I'm sorry, there was a bank holiday in Czech republic yesterday. I was thinking about how to add the series data into the table. Although some options exist, none of them look good enough to me :smile: 

If you just switch the rows and columns for now (as I described in the previous comment), we can merge the PR. If and when we need the series somehow in the future, we can work it out later.

**Comment by jesuino** [comment]
Hello @barboras7 - Thanks for the feedback. I modified the table structure to looks like the following. As we talked this could be merged and next week you would adjust the selenium tests, hence I am checking who could merge this.

image

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
I think this can be merged, @paulovmr - all green!

**Pull request merged**
