### PR TITLE
[AF-1800]: Mockito version downgraded

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins, execute full downstream build

**Comment by pefernan** [comment]
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/918

**Comment by pefernan** [comment]
Jenkins, execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@mbiarnes The errors from downstream build don't seem to be related to mockito or byte-buddy

**Comment by pefernan** [comment]
This is part of an ensemble, please merge with:
https://github.com/kiegroup/jbpm/pull/1428
https://github.com/kiegroup/appformer/pull/620
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/918

**Comment by krisv** [comment]
Already merged to speed up fixing master branch.

**Pull request merged**
