### PR TITLE
AF-1821: Readiness and Liveness endpoints

### PR DESCRIPTION
**Pull request by tiagobento**
This PR adds a init-param to the `BasicAuthSecurityFilter` so that it's possible to configure URIs that should not be authenticated.

Related PRs:
https://github.com/kiegroup/appformer/pull/645
https://github.com/kiegroup/kie-wb-common/pull/2492
https://github.com/kiegroup/kie-wb-distributions/pull/881

### CODE REVIEW

**Comment by tiagobento** [comment]
@domhanak Do you mind reviewing it?

**Comment by tiagobento** [comment]
Jenkins, execute full downstream build.

**Comment by tiagobento** [comment]
Jenkins, execute full downstream build.

**Comment by ederign** [comment]
@domhanak can you please take a look on this or assign to someone else?

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
it is a long time, let's rerun the FDB once more before we merge this.

**Comment by domhanak** [comment]
:green_heart: MY EYES - SO GREEN :green_heart:

**Pull request merged**
