### PR TITLE
[AF-2445] Cleanup credentials

### PR DESCRIPTION
**Pull request by caponetto**
**Related PRs**:
- https://github.com/kiegroup/appformer/pull/921
- https://github.com/kiegroup/kie-wb-common/pull/3219

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
Jenkins execute full downstream build

**Comment by caponetto** [comment]
Unrelated test failures. They have been failing on other PRs as well.
@ederign feel free to merge it

**Pull request merged**
