### PR TITLE
DROOLS-4016: [Guided Rules Editor] Missing toolbar buttons in standalone mode

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/710
* https://github.com/kiegroup/kie-wb-distributions/pull/931

Fixes the JIRAs:
* https://issues.jboss.org/browse/DROOLS-4016
* https://issues.jboss.org/browse/DROOLS-4015
* https://issues.jboss.org/browse/RHPAM-2116

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Thanks @paulovmr, I will look at this with @kkufova on Monday.

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unrelated test failures.

**Pull request merged**
