### PR TITLE
[AF-2363] Be able to create projects from empty repositories

### PR DESCRIPTION
**Pull request by caponetto**
**Task**: [AF-2363](https://issues.redhat.com/browse/AF-2363)

**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1171
- https://github.com/kiegroup/appformer/pull/881
- https://github.com/kiegroup/kie-wb-common/pull/3126
- https://github.com/kiegroup/drools-wb/pull/1293
- https://github.com/kiegroup/optaplanner-wb/pull/353
- https://github.com/kiegroup/jbpm-wb/pull/1410
- https://github.com/kiegroup/kie-wb-distributions/pull/1009

### CODE REVIEW

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @caponetto,
I tested the feature manually and I found out there's an issue when importing an empty repository into the MySpace space (see attached screenshot). Trying to import the same repository in another space was successful. 
Screenshot from 2020-01-30 13-53-40

**Comment by caponetto** [comment]
Hi @barboras7, let me check that.

**Comment by barboras7** [comment]
@caponetto, 
sure, let me know if you're not able to reproduce it.

**Comment by caponetto** [comment]
I needed to rebase the branches.

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
Failed tests are unrelated.
@paulovmr Feel free to merge the PRs.

**Pull request merged**
