### PR TITLE
AF-2936: Check dependabot alerts on appformer repository

### PR DESCRIPTION
**Pull request by akumar074**
**JIRA**: [AF-2936](https://issues.redhat.com/browse/AF-2936)

**This PR includes the following fixes for security alerts by dependabot**
These packages have micro version updates
 - y18n (3.2.1 to 3.2.2)
 - lodash (4.17.11 to 4.17.21)
 - ws (5.2.2 to 5.2.3)
 - tar (2.2.1 to 2.2.2)
 - path-parse (1.0.6 to 1.0.7)
 - tmpl (1.0.4 to 1.0.5)
 - async (2.6.2 to 2.6.4)

These Packages have minor version updates
 - ajv (6.10.0 to 6.12.6)
 - node-fetch (2.3.0 to 2.6.7)
 - hosted-git-info (2.7.1 to 2.8.9)

I have run the sanity checks and found no regression for this update.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
@tomasdavidorg note that these are micro release upgrades and touches appformer-js which needs testing focussed on UI screens, specifically Library screen which uses this module.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by barboras7** [comment]
Hi @akumar074,
@tomasdavidorg has a sick day today. I'll take a look at the built artifacts once they are available. Meanwhile, I'll try to build the business central locally and run the tests, if the build works.

**Comment by barboras7** [comment]
Jenkins run fdb

**Comment by barboras7** [comment]
Hi @akumar074,
just to keep you updated. I ran multiple Selenium test suites with the business-central.war I built locally. Most of them passed without any issues, but there have been some failures. I am investigating the failures and I'll keep you updated.

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
@barboras7 Thanks for taking a look at this. Can you please send me the test failure details?

**Comment by barboras7** [comment]
@akumar074 it seems that the failures were only caused by the instability of Selenium tests. When a business central is available from the FDB, I'll run just some smoke tests but the PR seems to be good to go.

**Comment by akumar074** [comment]
Jenkins run cdb

**Comment by barboras7** [comment]
I am trying to download the business-central from Jenkins but I am not able to access it, getting a timeout.

**Comment by akumar074** [comment]
@barboras7 I am also unable to access the URL for the Jenkins job. Will need to check with the team.

**Comment by RishiRajAnand** [comment]
@Ginxo we can't access the FDB URLs for builds. Do you know what could be wrong there?

**Comment by Ginxo** [comment]
@RishiRajAnand @akumar074 as a workaround you can directly go to https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/appformer-main.fdb/71/console

**Comment by RishiRajAnand** [comment]
thanks @Ginxo for this information. @barboras7 @akumar074 you can download the artifacts for this url [lastSuccessfulBuild](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/appformer-main.fdb/lastSuccessfulBuild/artifact/bc/kiegroup_kie_wb_distributions/business-central-parent/)

**Review by RishiRajAnand — APPROVED** [review]

**Review by barboras7 — APPROVED** [review]

**Pull request merged**
