### PR TITLE
Increase connection timeout and retries

### PR DESCRIPTION
**Pull request by FireBurn**
I fail to connect to a remote server without increasing this timeout

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by adrielparedes** [comment]
@FireBurn Hi, thanks for the PR! But I can't approve the PR as it is. If those parameters need to change please add them as System Properties like those who are in the beginning of the class. Thanks!

**Comment by FireBurn** [comment]
I've change the ping service so variables aren't being reused, added system properties to control the values and updated the default

**Comment by adrielparedes** [comment]
@FireBurn great work, just one more thing, can you squash the commits? So we only have a single one?

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
Jenkins retest this

**Comment by FireBurn** [comment]
I thought you'd want them individually, I'll squash them now

**Comment by FireBurn** [comment]
Also noticed a stupid typo

**Comment by adrielparedes** [comment]
Jenkins retest this

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@FireBurn great, let's wait for tests and the other guys and that is all :) Thanks for the PR!

**Comment by ederign** [comment]
@tomasdavidorg when you have a chance, can you please take a look at this?

and @FireBurn thanks for the contribution!

**Comment by mareknovotny** [comment]
@FireBurn  there are compilation errors referenced TIMEOUT constant which was renamed to PING in https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java#L72 and in https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java#L79 and in https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java#L86

```
14:58:07  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project uberfire-metadata-backend-infinispan: Compilation failure: Compilation failure: 
14:58:07  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-appformer-master.pullrequests/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java:[72,72] cannot find symbol
14:58:07  [ERROR]   symbol:   variable TIMEOUT
14:58:07  [ERROR]   location: class org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingService
14:58:07  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-appformer-master.pullrequests/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java:[77,53] cannot find symbol
14:58:07  [ERROR]   symbol:   variable TIMEOUT
14:58:07  [ERROR]   location: class org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingService
14:58:07  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-appformer-master.pullrequests/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java:[79,72] cannot find symbol
14:58:07  [ERROR]   symbol:   variable TIMEOUT
14:58:07  [ERROR]   location: class org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingService
14:58:07  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-appformer-master.pullrequests/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java:[84,53] cannot find symbol
14:58:07  [ERROR]   symbol:   variable TIMEOUT
14:58:07  [ERROR]   location: class org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingService
14:58:07  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/new-PR-appformer-master.pullrequests/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java:[86,72] cannot find symbol
14:58:07  [ERROR]   symbol:   variable TIMEOUT
14:58:07  [ERROR]   location: class org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingService
14:58:07  [ERROR] -> [Help 1]
14:58:07  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project uberfire-metadata-backend-infinispan: Compilation failure
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
14:58:07      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
14:58:07      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
14:58:07      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
14:58:07      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
14:58:07      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
14:58:07      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
14:58:07      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
14:58:07      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
14:58:07      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
14:58:07      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
14:58:07      at java.lang.reflect.Method.invoke (Method.java:498)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
14:58:07  Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
14:58:07      at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
14:58:07      at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)
14:58:07      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
14:58:07      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
14:58:07      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
14:58:07      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
14:58:07      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
14:58:07      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
14:58:07      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
14:58:07      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
14:58:07      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
14:58:07      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
14:58:07      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
14:58:07      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
14:58:07      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
14:58:07      at java.lang.reflect.Method.invoke (Method.java:498)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
14:58:07      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Review by mareknovotny — CHANGES_REQUESTED** [review]
Please fix also test class at https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-infinispan/src/test/java/org/uberfire/ext/metadata/backend/infinispan/provider/InfinispanPingServiceTest.java

**Comment by FireBurn** [comment]
Sorted

**Comment by adrielparedes** [comment]
Jenkins retest this

**Comment by adrielparedes** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@FireBurn thanks! let's wait for Jenkins :)

**Comment by mareknovotny** [comment]
@FireBurn great update.

Failed tests in FDB seems not related  to the change

org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask   
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort
there is also a cypress js test unit failure.

**Review by tomasdavidorg — APPROVED** [review]
@FireBurn Thanks. Looks good to me.

**Comment by mareknovotny** [comment]
I reported failed unstable tests in https://issues.redhat.com/browse/JBPM-9325

**Review by adrielparedes — APPROVED** [review]
+1

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
