### PR TITLE
AF-1587: a quick try to make the rest tests not lagging on volume, using an ummanaged service executor

### PR DESCRIPTION
**Pull request by porcelli**
A try to improve REST tests reliability

### CODE REVIEW

**Comment by porcelli** [comment]
@jhrcek @Rikkola @ederign let's give this a try before removing the tests :) 

(it might not be work, but it's worth a try)

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by jhrcek** [comment]
attempt 1/10: 17 failures, but no workbench rest test failure so far.
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
attempt 2/10: 11 failures, but no workbench rest test failure so far.
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
attempt 3/10: 15 failures, but no workbench rest test failure so far.
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
attempt 4/10: 21 failures, but no workbench rest test failure so far.
There is a :star2: of hope..
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
attempt 5/10: 14 failures, but no workbench rest test failure so far.
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
LMAO for the amount of failures, but looks good for the rest tests. Good work @porcelli!

**Comment by jhrcek** [comment]
attempt 6/10: 29 failures, but no workbench rest test failure so far (mostly kie-server integration tests) 
Jenkins execute full downstream build

**Comment by porcelli** [comment]
As I originally thought, the managed Executor Service might be too busy running other async tasks, So by switching to an UnManaged one it uses an Executor Service that is likely to be more available.

**Comment by porcelli** [comment]
@jhrcek i understand that you'd prefer execute it 10 times, but with the concurrency that infra has out of weeken, it might take the whole week to finish.
Why not merge as is, and we observe the results? If it fails again, we just remove the tests that we already agreed

**Comment by Rikkola** [comment]
I wonder if even one out of ten would pass the build. With this fix or without it.

**Comment by jhrcek** [comment]
I'm ok with merging this now and finding out the detailed statistics from the build on master. But before merging this please add comment to the code as requested above

**Comment by porcelli** [comment]
@jhrcek mind +1?

**Pull request merged**
