### PR TITLE
AF-2521: Create new home page for dashbuilder webapp

### PR DESCRIPTION
**Pull request by jesuino**
Dashbuilder Webapp home page modernization. 
--
This is a new webpage for dashbuilder-webapp.  You can check on the attached GIF how it looks like.
new_dashbuilder

### CODE REVIEW

**Comment by sthundat** [comment]
Hi @jesuino ,
Please find one of my  suggestion for the new homepage,
can we change the tool name 'Transfer' on homepage to 'Data Transfer' same like  'Data Transfer' under Administration menu.I guess this would be more readable for the user.
Thanks,
Savitha

**Comment by sthundat** [comment]
@jesuino ,
As we discussed while creating samples ,we are getting "java.lang.RuntimeException: java.lang.RuntimeException:Data set not found: salesOpportunities" exception in gallery page.since we are not configure salesOpportunities dataset manually. Can we handle this data set configuration in different way?
Also I am not able to deploy the same dataset manually on wildfly.
Could you please check.

**Comment by jesuino** [comment]
Hello @sthundat 

Thanks again for your feedback. I did change the text for Data Transfer in Home page.

We did decide that we will fixing samples all together in AF-2526 and it includes fixing the available dataset and the samples in general. Since it is only dashbuilder-webapp

https://issues.redhat.com/browse/AF-2526

**Comment by sthundat** [comment]
> Hello @sthundat
> 
> Thanks again for your feedback. I did change the text for Data Transfer in Home page.
> 
> We did decide that we will fixing samples all together in AF-2526 and it includes fixing the available dataset and the samples in general. Since it is only dashbuilder-webapp
> 
> https://issues.redhat.com/browse/AF-2526

Hello @jesuino ,
AF-2526 is looks good for me to fix the other issues later.once i get the latest war for new home page , I will do a final round of testing and can be approve the PR.
Thanks,
Savitha

**Comment by sthundat** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Hello @sthundat Here's the latest WAR version https://drive.google.com/file/d/1eDqtsjHXsfWll_djqvYsYGWeTBXgRJYI/view?usp=sharing

**Pull request merged**
