### PR TITLE
AF-1908: add HTTP protocol support to git

### PR DESCRIPTION
**Pull request by porcelli**
to make it possible, I had to adjust some security-related infra.

related PRs:
https://github.com/kiegroup/appformer/pull/669
https://github.com/kiegroup/kie-wb-distributions/pull/902
https://github.com/kiegroup/kie-wb-common/pull/2551
https://github.com/kiegroup/kie-docs/pull/1487

### CODE REVIEW

**Comment by porcelli** [comment]
@errantepiphany be aware that we'll add a few new properties that enables git access over http/https

**Comment by porcelli** [comment]
jenkins execute full downstream build

**Comment by errantepiphany** [comment]
@porcelli Excellent, thank you.

**Comment by porcelli** [comment]
jenkins execute full downstream build

**Comment by porcelli** [comment]
jenkins execute compile downstream

**Comment by ederign** [comment]
@domhanak can you please take a look on this ?

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hi @porcelli, I downloaded the built war file and I tried these steps:
1. Create space with name `aaa`.
2. Create project with name `bbb`.
3. Copy the http address from project settings.
4. Clone the project by `git clone http://localhost:8080/business-central/git/aaa/bbb`

I got this error: `fatal: http://localhost:8080/business-central/git/aaa/bbb/info/refs not valid: is this a git repository?`

From the code, I see that the `org.uberfire.nio.git.http.enabled` property is enabled by default.

**Comment by porcelli** [comment]
@tomasdavidorg i just updated a few minor things on web.xml, and it works here.

I tested on EAP 7.2 only. And just to make sure, I also disabled git user cache:

git config --global --unset credential.helper
git config --system --unset credential.helper

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
BTW looks like jenkins is failing due to unrelated test failures.

**Pull request merged**
