### PR TITLE
[RHBA-685]: If invocation target exception is catched, target exception is extracted

### PR DESCRIPTION
**Pull request by adrielparedes**
Port to master of this: https://github.com/kiegroup/appformer/pull/328

### CODE REVIEW

**Comment by adrielparedes** [comment]
@ederign the test that uses this is here: @ederign the test is written, sorry I didn't linked it, https://github.com/kiegroup/kie-wb-common/pull/1734, sorry I didn't linked it before. The test is called LibraryPlacesTest.goToLibraryWhenUserIsNotAuthorizedToCreateProjectsTest() and I test that when an UnauthorizedException ocurrs when trying to go to Library, redirects the user to Spaces. This was a problem because if you have a user with no permission to create the default project, an error message appeared and you could do anything.

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@adrielparedes ok, but can you please put a simple example of the mechanism as a test on this repo?

**Comment by adrielparedes** [comment]
@ederign I've added a test that tries that condition with mockito. Mockito creates an InvocationTargetException that made some problems when trying to use the original exception, so that tests ensure that everything works as usual.

**Pull request merged**
