### PR TITLE
AF-2887: Test failure on daily-build on main branch

### PR DESCRIPTION
**Pull request by akumar074**
* Fixed mvn security password on GuvnorM2RepositoryTest

**JIRA**: 
[AF-2887](https://issues.redhat.com/browse/AF-2887)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by tiagobento** [comment]
@akumar074 Any particular reason for changing the password?

**Comment by akumar074** [comment]
@tiagobento The test wasn't able to decrypt the password properly. I kept the same password but re-encrypted the password for it.

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
I have changed the `master-password in settings-security.xml. I'll revert it to previous value.

**Pull request merged**
