### PR TITLE
JBPM-9670 Data type with long name overlaps tooltip area when inspect…

### PR DESCRIPTION
**Pull request by bxf12315**
…ing process variables of a Process instance

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9670](JBPM-9670)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by nmirasch** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
GA build on jdk 11 fails due OOO, not sure if we can increase memory in workflow config or customize it in project pom.xml
Otherwise this PR change is ok from CI POV. Please review @nmirasch @domhanak

**Review by nmirasch — APPROVED** [review]

**Review by domhanak — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Pull request merged**
