### PR TITLE
JBPM-6659 - New layout presenter for handling master/detail navigatio…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…n across screens

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch please take a look. You can see the new layout using the showcase webapp -> Perspectives -> Multi Screen Perspective menu.

**Comment by bsremac** [comment]
@cristianonicolai These buttons _Open TodoListScreen_ and _Open side panel TodoListScreen_, what screens they should correspond to in the context of existing jbpm-wb perspectives?
I assume that _Multi Screen_ drop-down would correspond to the new _Manage_ selector, right?

**Comment by cristianonicolai** [comment]
@bsremac _Open TodoListScreen_ represents a new detail page, it should open taking the entire screen.
_Open side panel TodoListScreen_ represents the current detail pages, in a side panel but using this new layout.
Correct for the _Manage_ selector.

**Comment by cristianonicolai** [comment]
@ederign the side panel was just an interim solution. We're moving to master detail navigation in the manage section which basically stacks screens on top of each other as shown in the _Open TodoListScreen_ example. In terms of design, these are not targetting an editor like approach. Although we support the different layout for the buttons, we will only have one or two actions.
See design for reference: https://rawgit.com/lclay2/bxms-uxd-sandbox/master/design/Manage-section/process_details_existing.html

**Comment by ederign** [comment]
@cristianonicolai thanks for the clarification!

**Pull request merged**
