### PR TITLE
RHPAM-2867: Pie chart return error when a column use integer number

### PR DESCRIPTION
**Pull request by akumar074**
* Added check for possible cast to number

**JIRA**: [RHPAM-2867](https://issues.redhat.com/browse/RHPAM-2867)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Review by jesuino — COMMENTED** [review]
Hello @akumar074 

The changes looks good to me, but I will test the WAR on Tuesday to make sure that it fixes the issue.

Thanks!

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
Hello @jesuino and @sthundat 

FDB is failing due to some unrelated test failures. Artifacts are built and can be used to test.

Thanks!

**Review by jesuino — APPROVED** [review]
It works correctly for me, thanks @akumar074

**Comment by akumar074** [comment]
> It works correctly for me, thanks @akumar074

Thanks @jesuino !

**Review by sthundat — APPROVED** [review]
Hi @akumar074 ,
Fix is working fine.Thank you.
But as part of the verification I found another issue and open a Jira.
[Link](https://issues.redhat.com/browse/RHPAM-3292).
Regards,
Savitha

**Comment by akumar074** [comment]
> Hi @akumar074 ,
> Fix is working fine.Thank you.
> But as part of the verification I found another issue and open a Jira.
> [Link](https://issues.redhat.com/browse/RHPAM-3292).
> Regards,
> Savitha

Thanks Savitha!

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
Tests failure looks unrelated in FDB.

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins execute fdb

**Comment by akumar074** [comment]
jenkins run fdb

**Pull request merged**
