### PR TITLE
[7.18.x] [RHPAM-1904] Some tests are not part of maven build

### PR DESCRIPTION
**Pull request by domhanak**
Only test changes.
This fixes jgit the tests on Windows certifications. 

Cherry-pick of #653

### CODE REVIEW

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by ederign** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by ederign** [comment]
@domhanak we can close this right?

**Comment by domhanak** [comment]
@ederign imho we should merge this, these are just test fixes and it would be valuable to have them fixed on 7.18.x stream too.

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
(waiting for a green build). 
@domhanak sorry for the delay on this.

**Comment by domhanak** [comment]
Closing this, became out of date

**Pull request closed without merging**
