### PR TITLE
[7.52.x] : RHPAM-3557: Slow performance opening assets in projects with large commit history

### PR DESCRIPTION
**Pull request by RishiRajAnand**
(cherry picked from commit 3c80b8735158335ea227f67cd754789cf828b401)

**Thank you for submitting this pull request**

**RHPAM-3557**: _https://issues.redhat.com/browse/RHPAM-3557_ 

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

main PR: https://github.com/kiegroup/appformer/pull/1131

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
FDB failures seems unrelated, retriggering again

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run cdb

**Review by tiagobento — APPROVED** [review]

**Review by adrielparedes — APPROVED** [review]

**Pull request merged**
