### PR TITLE
[7.7.x] RHPAM-994: Stunner - Error popup appears once importing some processes

### PR DESCRIPTION
**Pull request by wmedvede**
- Removes unnecessary ioService.createFile(xxx) invocation for later writing the file content with ioService.write(xxx)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys would you mind review this PR? 
Thanks.

Train for the 7.0.1 is over but we still can get the 7.0.2 one

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
HI @jsoltes,

another PR for your review.

**Comment by jhrcek** [comment]
Just adding info about why FDB job failed:
`Build timed out (after 300 minutes). Marking the build as aborted.`

**Comment by jsoltes** [comment]
It looks like the full downstream build timed out again. Any idea what to do with this?

**Comment by wmedvede** [comment]
@krisv would you mind take a look for the acks https://issues.jboss.org/browse/RHPAM-994
Thanks

**Comment by romartin** [comment]
Jenkins please execute full downstream build

**Comment by wmedvede** [comment]
@romartin @hasys all required acks are now in place, so this can be merged as soon it's approved

**Comment by jhrcek** [comment]
@hasys FYI I recently disabled maven build parallelism from full downstream build, which is expected to slow down the build a bit. I'll tweak the timeout today so this won't happen again.

**Comment by wmedvede** [comment]
Jenkins please execute full downstream build

**Comment by wmedvede** [comment]
now the build failed due to

org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest.testSignalContainer[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:35677/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest.testSignalContainer[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest.testSignalContainer[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest.testSignalContainer[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]

**Comment by wmedvede** [comment]
Jenkins please execute full downstream build

**Comment by wmedvede** [comment]
more fails not related with this PR
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34946/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34946/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34946/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.testErrorHandlingFailedToSignal[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest.testSLAonProcessViolated[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34946/kie-server-

**Comment by wmedvede** [comment]
Jenkins please execute full downstream build

**Comment by wmedvede** [comment]
Hi @romartin , I've been chatting with @hasys and we agreed his is ready for merging.
Would you mind take a look?

**Pull request merged**
