### PR TITLE
AF-2336: Remove deprecated Docker Tests

### PR DESCRIPTION
**Pull request by adrielparedes**
## Intention
Remove deprecated docker tests.

## Related to
* https://github.com/kiegroup/appformer/pull/957
* https://github.com/kiegroup/kie-wb-common/pull/3295
* https://github.com/kiegroup/kie-soup/pull/138

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
The FDB failing tests are not related (KogitoDMNSelenium)

**Comment by barboras7** [comment]
Hi @adrielparedes,
I removed ohonchar from reviewers (he no longer works with us) and I added @nibub17 who is currently working with community tests in QE.

I have one concern about these PRs. You are only removing tests in the PRs but the code with the functionality is not removed. This means that there will be some parts of the code that will have lower code coverage if the PR are merged. Why the code with functionality (if no longer used) is not removed as well?

**Comment by adrielparedes** [comment]
@barboras7 The tests were removed because the code is not supported anymore. It can be used and we will remove those parts with time. But we need the tests running in new RHEL versions that don't support docker and that is why we removed those tests. They are Elasticsearch related tests and ALA tests. I will create a Jira to remove the unused code, but we need a deeper analysis first

**Comment by barboras7** [comment]
Hi Adriel, 
thanks for the explanation. If you could create the Jira for removal of the code, that would be great. :slightly_smiling_face: 

I am leaving the review of the PRs to Nibu as he is working with the community tests in QE.

**Pull request merged**
