### PR TITLE
DROOLS-3665: [DMN Designer] Data Types - Constraints (Range/Enumeration) - Add "Time" component when the type is "Time"

### PR DESCRIPTION
**Pull request by danielzhe**
This PR is required for:
https://github.com/kiegroup/kie-wb-common/pull/2553

### CODE REVIEW

**Comment by danielzhe** [comment]
I had to add a new method here.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by danielzhe** [comment]
Jenkins execute full downstream build.

**Comment by danielzhe** [comment]
Jenkins execute full downstream build.

**Comment by danielzhe** [comment]
@karreiro "Linux - full downstream — Build finished. No test results found. " But there's nothing to test in this PR since it's just some method signature to native code.

**Comment by karreiro** [comment]
The error seems not related to this PR. Can we merge this, @kiegroup/gatekeepers? 

```
Fetching upstream changes from git://github.com/errai/errai.git
 > git --version # timeout=10
 > git fetch --tags --progress git://github.com/errai/errai.git +refs/heads/*:refs/remotes/origin/* --depth=1
Unexpected error while executing the Upstream repositories builder for PR builds! Command "git fetch --tags --progress git://github.com/errai/errai.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 139:
stdout: 
stderr: fatal: The remote end hung up unexpectedly

hudson.plugins.git.GitException: Command "git fetch --tags --progress git://github.com/errai/errai.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 139:
stdout: 
stderr: fatal: The remote end hung up unexpectedly
```

Thanks!

**Pull request merged**
