### PR TITLE
BXMSPROD-494 allow GA build on windows machine

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-494

related to

https://github.com/kiegroup/lienzo-core/pull/133
https://github.com/kiegroup/lienzo-tests/pull/108
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1471
https://github.com/kiegroup/kie-soup/pull/158
https://github.com/kiegroup/appformer/pull/1054
https://github.com/kiegroup/droolsjbpm-knowledge/pull/465
https://github.com/kiegroup/drools/pull/3116
https://github.com/kiegroup/optaplanner/pull/940
https://github.com/kiegroup/jbpm/pull/1758
https://github.com/kiegroup/kie-jpmml-integration/pull/43
https://github.com/kiegroup/droolsjbpm-integration/pull/2243
https://github.com/kiegroup/openshift-drools-hacep/pull/100
https://github.com/kiegroup/droolsjbpm-tools/pull/118
https://github.com/kiegroup/kie-uberfire-extensions/pull/106
https://github.com/kiegroup/kie-wb-playground/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3423
https://github.com/kiegroup/drools-wb/pull/1423
https://github.com/kiegroup/optaplanner-wb/pull/381
https://github.com/kiegroup/jbpm-designer/pull/891
https://github.com/kiegroup/jbpm-wb/pull/1461
https://github.com/kiegroup/jbpm-work-items/pull/153
https://github.com/kiegroup/kie-docs/pull/2849
https://github.com/kiegroup/optaweb-employee-rostering/pull/498
https://github.com/kiegroup/optaweb-vehicle-routing/pull/367
https://github.com/kiegroup/kie-wb-distributions/pull/1062

### CODE REVIEW

**Comment by Ginxo** [comment]
error `Filename too long` while checking out appformer project
```
[ERROR]  command git clone --quiet --shallow-submodules --no-tags --branch master https://github.com/kiegroup/appformer ./appformer failed with code 128. Error Message: error: unable to create file uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/SecurityManagementHomeConstants.properties: Filename too long
```

**Comment by Ginxo** [comment]
PR created to test this change https://github.com/Ginxo/appformer/pull/2 because windows is not even able to merge it with master branch

**Comment by Ginxo** [comment]
`The filename or extension is too long` on `gwt-maven-plugin` execution https://github.com/Ginxo/appformer/pull/2/checks?check_run_id=1153701889
```
2020-09-23T09:03:29.7498128Z [INFO]    Compiling 2 permutations
2020-09-23T09:03:30.6273412Z [INFO]       [ERROR] Unable to start external process
2020-09-23T09:03:30.6286467Z [INFO] java.io.IOException: Cannot run program "C:\hostedtoolcache\windows\jdk\8.0.265\x64\jre\bin\java": CreateProcess error=206, The filename or extension is too long
2020-09-23T09:03:30.6287966Z [INFO] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
2020-09-23T09:03:30.6301103Z [INFO] 	at com.google.gwt.dev.ExternalPermutationWorkerFactory.launchExternalWorker(ExternalPermutationWorkerFactory.java:282)
2020-09-23T09:03:30.6310297Z [INFO] 	at com.google.gwt.dev.ExternalPermutationWorkerFactory.getWorkers(ExternalPermutationWorkerFactory.java:374)
2020-09-23T09:03:30.6316587Z [INFO] 	at com.google.gwt.dev.PermutationWorkerFactory.createWorkers(PermutationWorkerFactory.java:351)
2020-09-23T09:03:30.6319435Z [INFO] 	at com.google.gwt.dev.PermutationWorkerFactory.compilePermutations(PermutationWorkerFactory.java:254)
2020-09-23T09:03:30.6325948Z [INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:211)
2020-09-23T09:03:30.6327339Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:219)
2020-09-23T09:03:30.6331726Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
2020-09-23T09:03:30.6332733Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
2020-09-23T09:03:30.6340716Z [INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
2020-09-23T09:03:30.6341927Z [INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
2020-09-23T09:03:30.6343891Z [INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
2020-09-23T09:03:30.6346549Z [INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
2020-09-23T09:03:30.6347614Z [INFO] Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
2020-09-23T09:03:30.6348494Z [INFO] 	at java.lang.ProcessImpl.create(Native Method)
2020-09-23T09:03:30.6349280Z [INFO] 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
2020-09-23T09:03:30.6350123Z [INFO] 	at java.lang.ProcessImpl.start(ProcessImpl.java:139)
2020-09-23T09:03:30.6355289Z [INFO] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2020-09-23T09:03:30.6356009Z [INFO] 	... 12 more
2020-09-23T09:03:32.5427736Z [INFO] ------------------------------------------------------------------------
2020-09-23T09:03:32.5445678Z [INFO] Reactor Summary for UberFire parent 7.44.0-SNAPSHOT:
2020-09-23T09:03:32.5446118Z [INFO] 
2020-09-23T09:03:32.5925573Z [INFO] UberFire parent .................................... SUCCESS [01:39 min]
...
...
...
2020-09-23T09:03:32.7431302Z [INFO] Dashbuilder All Server Libraries ................... SUCCESS [  1.289 s]
2020-09-23T09:03:32.7446542Z [INFO] Dashbuilder All Libraries .......................... SUCCESS [  1.338 s]
2020-09-23T09:03:32.7447207Z [INFO] Dashbuilder WebApp ................................. FAILURE [05:24 min]
2020-09-23T09:03:32.7447711Z [INFO] Dashbuilder Runtime ................................ SKIPPED
2020-09-23T09:03:32.7448244Z [INFO] Dashbuilder Distribution WARs ...................... SKIPPED
2020-09-23T09:03:32.7448792Z [INFO] AppFormer Client API ............................... SKIPPED
2020-09-23T09:03:32.7449260Z [INFO] AppFormer Kogito Bridge ............................ SKIPPED
2020-09-23T09:03:32.7454439Z [INFO] ------------------------------------------------------------------------
2020-09-23T09:03:32.7465404Z [INFO] BUILD FAILURE
2020-09-23T09:03:32.7475618Z [INFO] ------------------------------------------------------------------------
2020-09-23T09:03:32.7781609Z [INFO] Total time:  01:03 h
2020-09-23T09:03:32.9990992Z [INFO] Finished at: 2020-09-23T09:03:32Z
2020-09-23T09:03:33.0011335Z [INFO] ------------------------------------------------------------------------
2020-09-23T09:03:33.0462857Z [WARNING] The requested profile "wildfly" could not be activated because it does not exist.
2020-09-23T09:03:33.8287982Z [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.2:compile (gwt-compile) on project dashbuilder-webapp: Command failed with status 1 -> [Help 1]
2020-09-23T09:03:33.8343412Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.2:compile (gwt-compile) on project dashbuilder-webapp: Command failed with status 1
2020-09-23T09:03:33.8444603Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2020-09-23T09:03:33.8455430Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-09-23T09:03:33.8458071Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-09-23T09:03:33.8465626Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-09-23T09:03:33.8469062Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2020-09-23T09:03:33.8482527Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2020-09-23T09:03:33.8501449Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2020-09-23T09:03:33.8503174Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2020-09-23T09:03:33.8545414Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2020-09-23T09:03:33.8546962Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2020-09-23T09:03:33.8550970Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
2020-09-23T09:03:33.8552320Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
2020-09-23T09:03:33.8553513Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
2020-09-23T09:03:33.8554920Z     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2020-09-23T09:03:33.8556760Z     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2020-09-23T09:03:33.8565103Z     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2020-09-23T09:03:33.8566689Z     at java.lang.reflect.Method.invoke (Method.java:498)
2020-09-23T09:03:33.8568354Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2020-09-23T09:03:33.8570540Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2020-09-23T09:03:33.8597104Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2020-09-23T09:03:33.8599409Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
investigating which file generates the error

**Comment by mareknovotny** [comment]
closing due maven-gwt-plugin on windows

**Comment by Ginxo** [comment]
let's try

```
 - name: Support longpaths
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
```

**Pull request closed without merging**
