### PR TITLE
AF-930: [Layout Editor] Use dock panels to increase the editor content area

### PR DESCRIPTION
**Pull request by dgutierr**
Work in progress => https://issues.jboss.org/secure/attachment/12429320/12429320_cms-dockpanels.mp4

P.S. Dependent PRs to merge:

https://github.com/kiegroup/kie-wb-common/pull/1335
https://github.com/kiegroup/jbpm-wb/pull/968
https://github.com/kiegroup/kie-wb-distributions/pull/665

### CODE REVIEW

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by dgutierr** [comment]
Ready for review.

@pefernan @jhrcek Can you review/approve please :-)?

**Comment by kkufova** [comment]
@dgutierr, there is a few things I noticed:

Firstly, what is the logic behind the Components item in the panel on the left? When there are no pages, it is not there. If you create a page, it appears. If you close the page, it disappears (which I guess is the correct behavior). If you create a second page, it appears again, but if you open the first page as well (so two pages are opened) and close them both, it stays in the panel. Would it be possible to unify the behavior?

screenshot from 2018-01-12 11-19-30

---
Also, I noticed that the Navigation panel does not use the whole available height, but only a small area (although the area gets bigger after adding items, it is still not really user-friendly):

screenshot from 2018-01-12 11-23-46

---
Adding custom pages to a custom group in the Workbench tree does not work and causes the following error:

screenshot from 2018-01-12 11-30-06

**Comment by dgutierr** [comment]
"...the Navigation panel does not use the whole available height"

Fixed.

"If you create a second page, it appears again, but if you open the first page as well (so two pages are opened) and close them both, it stays in the panel."
"Adding custom pages to a custom group in the Workbench tree does not work and causes the following error:"

I can't reproduce these two ones. Can you please share a video showing the steps please?

**Comment by kkufova** [comment]
@dgutierr, sure, here it is:

1. The Components dock does not disappear even when no pages are opened: https://issues.jboss.org/secure/attachment/12429817/screencast1.webm
2. Adding a custom group to the Workbench tree causes errors:
https://issues.jboss.org/secure/attachment/12429820/screencast2.webm
3. It is not then possible to edit custom trees without errors:
https://issues.jboss.org/secure/attachment/12429821/screencast3.webm

**Comment by ederign** [comment]
@dgutierr sorry for the delay in this review. Just before taking a look at the code I have a suggestion:

Why don't we put the Components in the east dock? For me, the component is a property of an open page. What do you think? That would fix the 'two pages open' confusion.

**Comment by dgutierr** [comment]
@ederign That was a requirement from UXD. The drag action shall be usually performed from the left to right. This is in order to be consistent with other the UX design patterns. Take for example the process designer, where the palette is placed on the left as well.   If you still think this can cause any issues we can discuss it in deep with Matthew :-)

**Comment by dgutierr** [comment]
@kkufova Fixed issue 1).

Unfortunately, I'm not able to reproduce 2) & 3). Can you try again with the latest build please?

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
@dgutierr, could you please rebase your `layouteditor` branch on `master`?

**Comment by dgutierr** [comment]
@kkufova Yes, it is already rebased.

**Comment by kkufova** [comment]
@dgutierr, the CMS perspective is in a really bad shape now. Creating new pages does not work (an error is displayed every time you create a page and its name is not displayed above the layout editor) and the same thing happens if you open a page. Every time you close a page, the following is displayed:

screenshot from 2018-01-23 10-04-34

It also happens that it is not possible to close a page and that the panel with components disappears completely. Adding custom pages and custom trees is also broken. I tried to record all of the bugs in the following video:
https://issues.jboss.org/secure/attachment/12430144/screencast4.webm

**Comment by dgutierr** [comment]
@kkufova Thanks Klara. I was able to reproduce all these issues. Working on the fixes.

**Comment by dgutierr** [comment]
@kkufova Fixed.

**Comment by ederign** [comment]
@pefernan could you please take a look and do a sanity check with forms?

**Comment by dgutierr** [comment]
@manstis Would you mind to merge this along with its other related PRs? Thanx!

kiegroup/kie-wb-common#1335
kiegroup/jbpm-wb#968
kiegroup/kie-wb-distributions#665

**Comment by manstis** [comment]
@dgutierr Sure.. just let me know when they're all approved and all green. 

https://github.com/kiegroup/kie-wb-common/pull/1335 still requires @jhrcek approval and is not green.

**Comment by dgutierr** [comment]
@manstis Klara from QE already approved this kiegroup/kie-wb-common#1335 

The green flag does not show up due to some test issues in jenkins build (see the PR's thread). QE agreed it can be merged.

**Comment by manstis** [comment]
@dgutierr Well.. I'd have thought it customary for @jhrcek to confirm he's happy with the answers to his questions. Just because somebody else has approved the PR does not mean all potential issues, found by others, have been resolved... The only expediting reasons would be if the PR is uber-urgent and the said person is on PTO etc.

The build is also red now..

**Comment by dgutierr** [comment]
@manstis I understand your concerns... let's wait for @jhrcek to approve :-)

**Comment by jhrcek** [comment]
@dgutierr Sorry for the delay, I was on PTO. Thanks for the fixes!
@manstis I consider this is ready for merge.

**Comment by dgutierr** [comment]
@manstis These changes must be included in 7.6.0.final. Can you please merge before the release build is triggered?

**Comment by manstis** [comment]
@dgutierr https://github.com/kiegroup/kie-wb-common/pull/1335 is still red... trying Jenkins again.

**Comment by mareknovotny** [comment]
@manstis @dgutierr there are enforcer failures for duplicated classes look at the log please. You need to fix it first.
```
[INFO] Compiling 4 source files to /home/jenkins/workspace/kie-wb-common-pullrequests/kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-client/target/test-classes

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    javax.el:javax.el-api:jar:3.0.0:provided
    org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.9.Final:provided
```

**Comment by manstis** [comment]
Jenkins please retest this... Jenkins did not complain of enforcer violations; so let's check again!

**Pull request merged**
