### PR TITLE
[7.7.x] AF-1119: "Are you sure you want to discard unsaved data?" Displayed

### PR DESCRIPTION
**Pull request by dgutierr**
@jhrcek Backport from master.

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@dgutierr I'm in the middle of testing this locally. Quick manual check confirms it works. I just need to run regression tests to make sure the whole dashbuilder test suite works fine again. I'll provide feedback tomorrow morning.

**Comment by jhrcek** [comment]
FYI full downstream build failures are unrelated to these changes (some kie-server integration tests). Rebuilding again just for good measure..

**Comment by dgutierr** [comment]
@ederign  Can you please merge?

**Pull request merged**
