### PR TITLE
Upgrade react dependencies pointed by dependency bot

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

JIRA: [AF-2936](https://issues.redhat.com/browse/AF-2936)

**Referenced Pull Requests**:
https://github.com/kiegroup/kie-wb-common/pull/3735

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by tomasdavidorg** [comment]
There is a problem in kie-wb-common, kie-wb-common-library-spaces-screen package:
```
Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:19:17)
```
we should probably also update the react versions also there.

**Comment by RishiRajAnand** [comment]
> There is a problem in kie-wb-common, kie-wb-common-library-spaces-screen package:
> 
> ```
> Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
>       at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:19:17)
> ```
> 
> we should probably also update the react versions also there.

Yeah looks like it. I'll try updating it there as well

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run cdb

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
