### PR TITLE
KOGITO-436: Remove unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**
During KOGITO-436 review some unused dependencies were found, this PR is an effor to eliminate them.

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@karreiro may I ask you for a review?

**Comment by jomarko** [comment]
@karreiro does a rocket mean it is fine to merge? :)

**Comment by karreiro** [comment]
@jomarko No, it means that this is on my to-do list to review :)

**Comment by jomarko** [comment]
@karreiro ok, thank you

**Pull request merged**
