### PR TITLE
AF-2920: Increase jest version to eliminate EBAFD

### PR DESCRIPTION
**Pull request by barboras7**
**JIRA**: [AF-2920](https://issues.redhat.com/browse/AF-2920)

Hi @tiagobento, 
since you seem to be the last person who touched this code, could you please take a look at the changes? The detailed information can be found in the related Jira. Thank you

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute FDB

**Comment by barboras7** [comment]
I'm trying to figure out why the compilation is not working. I'll update the PR once I know the root cause.

**Comment by barboras7** [comment]
Hi @tiagobento, 
could you please review this PR and let me know what you think?

To learn more about the issue, you can check the Jira description of AF-2920. 

My first plan was to increase the `jest` and `ts-jest` version. However, that is not so easy because it is causing compilation issues. I have decided to try to force the correct version of `write-file-atomic`. Based on the discussion in this [jest issue](https://github.com/facebook/jest/issues/7709), it seems that `write-file-atomic 2.4.2` is affected. With resolutions, I am forcing the `2.4.1` version of `write-file-atomic` which should solve our issue. 

Unfortunately, there is no way to properly check if this fix solves our issue because we need productized binaries. This means that once we merge this and receive nightlies from the main branch, we will see the results on our Jenkins.

**Comment by tiagobento** [comment]
@barboras7 Is the CI breaking with related errors?

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins run cdb

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
It seems that those were just random failures. I think we can proceed and merge this.

**Comment by barboras7** [comment]
Could you please approve and merge this @tiagobento?

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
