### PR TITLE
[AF-1634] Social framework removal

### PR DESCRIPTION
**Pull request by caponetto**
Pull requests associated with this change:
- kiegroup/appformer#701
- kiegroup/kie-wb-distributions#923
- kiegroup/kie-wb-common#2646
- kiegroup/drools-wb#1141
- kiegroup/optaplanner-wb#335
- kiegroup/jbpm-wb#1350

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by ederign** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by ederign** [comment]
@domhanak can you please double check that this fixes https://issues.jboss.org/browse/AF-1768 ?

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Testing didn't reveal anything problematic. I will approve as soon as the build has three :heavy_check_mark:

**Comment by caponetto** [comment]
Thanks, @domhanak! We've got 5 test failures in the build.
One of the failed tests is due to a missing test dependency in drools-wb. This dependency became necessary after updating my branches with the latest code. Anyway, I've fixed it. 
Regarding the other 4 test failures, I don't see any relation with the changes.

**Comment by caponetto** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
@caponetto So, there are some tests that fail because business-central takes too long to startup. Any ideas what could be the cause? 
I ll check other PR's and current nightly wars to see if it also happens there.

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by caponetto** [comment]
@domhanak I have no idea, but I've seen the same test failures in other PRs.

**Comment by ederign** [comment]
@domhanak the fails doesn't look related. Can we merge this?

**Comment by ederign** [comment]
@caponetto did you make a rebase of this PR?

**Comment by caponetto** [comment]
@ederign I merged the master branch into this PR's branch yesterday. It was becoming outdated.

**Comment by ederign** [comment]
@caponetto yesterday is more than fine! No need to hurry.

**Comment by domhanak** [comment]
`org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective` this tests fails consistently. I am not yet sure why and if it si related. @caponetto @ederign any ideas? It seems like the loading time of the home screen increased.

**Comment by domhanak** [comment]
@ederign I didn't verify the bug yet. Setting up the environment takes some time...

**Comment by ederign** [comment]
@domhanak I don't think it's related, actually removing social will make stuff faster.

@domhanak when you plan to test the windows bug? I'm asking this because if this will take some time, my suggestion would be to merge this (if the social framework removal is ok to you) and then check later if the bug is gone.  wdyt?

**Comment by domhanak** [comment]
@ederign I agree, let's merge this.

**Pull request merged**
