### PR TITLE
DROOLS-4357 : Two download buttons are in Guided Decision Tables

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-4357

https://github.com/kiegroup/appformer/pull/745
https://github.com/kiegroup/kie-wb-common/pull/2777
https://github.com/kiegroup/drools-wb/pull/1196

### CODE REVIEW

**Comment by Rikkola** [comment]
@Bonuseto one more

**Comment by manstis** [comment]
@Rikkola The FDB looks like a genuine failure.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:compile (default-compile) on project kie-wb-metadata-widget: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/appformer-compile-downstream-build/downstream-repos/kie-wb-common/kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java:[59,51] cannot find symbol
[ERROR]   symbol:   class DownloadMenuItem
[ERROR]   location: package org.uberfire.ext.editor.commons.client.menu
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/appformer-compile-downstream-build/downstream-repos/kie-wb-common/kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java:[96,15] cannot find symbol
[ERROR]   symbol:   class DownloadMenuItem
[ERROR]   location: class org.kie.workbench.common.widgets.metadata.client.KieMultipleDocumentEditor<D>
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/appformer-compile-downstream-build/downstream-repos/kie-wb-common/kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java:[167,53] cannot find symbol
[ERROR]   symbol:   class DownloadMenuItem
[ERROR]   location: class org.kie.workbench.common.widgets.metadata.client.KieMultipleDocumentEditor<D>
[ERROR] -> [Help 1]
```

**Comment by Rikkola** [comment]
Yes just fixed it, did not know this builds downstream.

jenkins please compile downstream build

**Comment by Rikkola** [comment]
jenkins execute compile downstream build

**Pull request merged**
