### PR TITLE
AF-2487: Reuse errai.wildfly property form kie-parent

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/AF-2487

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
if we at the end don't need errai WF distro, we can easily delete it at once ;)

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Pull request merged**
