### PR TITLE
DROOLS-4321: [DMN Designer] Search feature - DMN Data Types must be searchable elements

### PR DESCRIPTION
**Pull request by karreiro**
See: https://issues.jboss.org/browse/DROOLS-4321

---

Part of an ensemble:
- https://github.com/kiegroup/appformer/pull/762
- https://github.com/kiegroup/kie-wb-common/pull/2791
- https://github.com/kiegroup/drools-wb/pull/1207

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please execute full downstream build 🚀

**Comment by karreiro** [comment]
@jomarko @danielzhe Could you please take a look?

**Comment by karreiro** [comment]
Jenkins please execute full downstream build 🥁

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
The broken test is not related to this PR:
```
org.kie.server.springboot.samples.rest.KieServerWithExtraEndpointTest.testExtraEndpoint
```

**Comment by karreiro** [comment]
Jenkins please execute full downstream build 😔

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Broken tests are not related to this PR:
```
org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithInclusiveGateway
org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader
```

**Comment by jomarko** [comment]
@karreiro I think I can fix the last failed test (`StandalonePerspectivesIntegrationTest`), I prepared a PR https://github.com/kiegroup/kie-wb-distributions/pull/956, feel free to have a look.

**Pull request merged**
