### PR TITLE
RHPAM-2865 : Wrong created date on asset list

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Description** :

- Added feature to show corresponding last modification date and creation date for assets in  asset list.

**RHPAM-2865**: https://issues.redhat.com/browse/RHPAM-2865
**AF-2497**: https://issues.redhat.com/browse/AF-2497

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
> @RishiRajAnand thanks for the PR. The solution was to use `getAuthorIdent` instead of `getCommitterIdent`? Why are you creating a new collection just to look for the first and the last one? `fs.getGit().getLastCommit(ref)` and `fs.getGit().getLastCommit(ref)` can not be used?

@adrielparedes when using fs.getGit().getLastCommit(ref), it gives the Last commit of entire git file system rather than the specific file (which was the reason we could see same date for all assets). So, here i am storing the commit history of specific file in a List and then fetching the first and last commit. Thanks

**Comment by barboras7** [comment]
jenkins run fdb

**Review by barboras7 — APPROVED** [review]

**Comment by adrielparedes** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
FDB failures seemed unrelated, rebased and pushed again.

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Review by adrielparedes — APPROVED** [review]

**Review by paulovmr — APPROVED** [review]

**Comment by paulovmr** [comment]
Unrelated test failures

**Pull request merged**
