### PR TITLE
[BXMSPROD-1845] removing the rest of ES references

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1845

Related PRs:

* https://github.com/kiegroup/appformer/pull/1312

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
please @jesuino review it. I removed ES references like a monkey until I had successful build (it worked at the first shot, which scares me even more)

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run cdb

**Comment by Ginxo** [comment]
Java 11 InfinispanPingServiceTest random failure

**Comment by Ginxo** [comment]
@jesuino what do you propose to do with https://github.com/kiegroup/kie-wb-common/blob/7c64eed3b5b4284c5b15b1c3ce86dcce4c107284/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java#L44 ? :thinking:

**Comment by jesuino** [comment]
Hello @Ginxo 

Thank you so much for your hard work on this. I did remove ElasticSearch a few months ago from Kogito Dashbuilder and I also had to modify a lot of classes!

To check if it worked you can run `dashbuilder-webapp` - going to datasets should not see ElasticSearch as a provider anymore. If it works on webapp then it should work on BC. If there's anything wrong then probably Dashbuilder may not render at all with errors on console. It is been a while since I ran this in DEV mode, so I would recommend you to build the WAR and deploy on WF/EAP. Once build is green I can give it a try myself.  (I had a failure trying to build locally, but I will try again today)

Regarding ImpactAnalysisAnalyzerWrapper.java, I would just remove it and the implemented method "getFieldAnalyzer" to see if it works.

**Comment by jesuino** [comment]
Hello @Ginxo

Dashbuilder Webapp seems to be broken. We need a full build to have business-central-webapp and check if elastic search is gone

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by Ginxo** [comment]
I will fix kie-wb-common error from FDB as soon as this PR is ready

**Comment by jesuino** [comment]
This PR should fix Dashbuilder Webapp and allow us to run it with `mvn gwt:run` to confirm that ElasticSearch is gone.



https://github.com/Ginxo/appformer/pull/4

**Comment by Ginxo** [comment]
jenkins execute fdb

**Comment by jesuino** [comment]
Hello @Ginxo 

I tested the dashbuilder-webapp WAR that you built from your branch and deployed it on Widlfly 23.0.2 with JDK 11. Added the user `admin/admin` with role `admin` and using `./standalone.sh`, then going to `localhost:8080/dashbuilder-webapp` I can say that it works and ElasticSearch is gone from the datasets providers list:

image

I also run basic sanity checks with Dashbuilder Webapp  (create dataset, create page and add elements to it) and it works

**Comment by Ginxo** [comment]
many thanks @jesuino 
I'm just worried about https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java
@adrielparedes any idea about it? in case we remove `ElasticSearchAnalyzerWrapper` kie-wb-common compilation will break.

**Review by jesuino — APPROVED** [review]

**Comment by mareknovotny** [comment]
is that module needed then? @adrielparedes @jesuino 

```
[2022-11-23T18:34:25.132Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-wb-common-refactoring-backend: Compilation failure: Compilation failure: 
[2022-11-23T18:34:25.132Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/appformer-main.fdb/bc/kiegroup_kie_wb_common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[33,42] package org.uberfire.ext.metadata.analyzer does not exist
[2022-11-23T18:34:25.132Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/appformer-main.fdb/bc/kiegroup_kie_wb_common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[34,42] package org.uberfire.ext.metadata.analyzer does not exist
[2022-11-23T18:34:25.132Z] [ERROR] /home/jenkins/workspace/KIE/main/fdb/appformer-main.fdb/bc/kiegroup_kie_wb_common/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java:[44,95] cannot find symbol
[2022-11-23T18:34:25.132Z] [ERROR]   symbol: class ElasticSearchAnalyzerWrapper
```

**Comment by mareknovotny** [comment]
quick search says [ImpactAnalyzerWrapper](https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/ImpactAnalysisAnalyzerWrapper.java) is not used anywhere in WB https://github.com/search?q=org%3Akiegroup+ImpactAnalysisAnalyzerWrapper&type=code

**Comment by adrielparedes** [comment]
@mareknovotny @Ginxo thanks for your patience! you can remove that code, everything related to 
 ElasticSearch and org.uberfire.ext.metadata.analyzer is deprecated. The code was already removed and we can remove that too.

**Comment by mareknovotny** [comment]
what about [IndexingTest.java](https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/IndexingTest.java) ? It uses ImpactAnalysisWrapper and there are more testing classe in cascade to use/extend that IndexingTest class @adrielparedes?

**Comment by adrielparedes** [comment]
@RishiRajAnand is going to help you with this. @mareknovotny @Ginxo

**Comment by RishiRajAnand** [comment]
ImpactAnalysisAnalyzerWrapperFactory class is being used to intialise [MetadataConfigBuilder](https://github.com/kiegroup/appformer/blob/cd4dd4b5d457db4a8d81c65dd4c029d774316597/uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/MetadataConfigBuilder.java#L176)  in different contexts in appformer. Removing this could afffect lucene analyzer. I suggest to only remove ElasticSearchAnalyzerWrapper and its abstract method getFieldAnalyzer in  ImpactAnalysisAnalyzerWrapper since its not used anywhere

**Comment by RishiRajAnand** [comment]
@Ginxo could you please make the changes or else let me know if you need me to commit it ? thanks

**Comment by mareknovotny** [comment]
@RishiRajAnand Enrique is on leave, i tried to draft what you suggested here with additional removal of ES and kie-soup-dataset module from the build https://github.com/kiegroup/kie-soup/pull/259

**Comment by Ginxo** [comment]
ok to close @mareknovotny ?

**Comment by mareknovotny** [comment]
yes, i incorporated this change into https://github.com/kiegroup/appformer/commit/98c6ecff723e5b0a7c772dd19e158efd28289eb7

**Pull request closed without merging**
