### PR TITLE
RHPAM-1896: UnexpecterError thrown when editing displayer display properties

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by jhrcek** [comment]
jenkins slave died during build:
```
13:47:00 java.io.EOFException
13:47:00 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
13:47:00 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
13:47:00 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:864)
13:47:00 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:360)
13:47:00 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
13:47:00 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
13:47:00 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
13:47:00 Caused: java.io.IOException: Unexpected termination of the channel
13:47:00 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
13:47:00 Caused: java.io.IOException: Backing channel 'kie-psi-rhel7-xlarge-10877' is disconnected.
13:47:00 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:212)
```
jenkins retest this

**Comment by jhrcek** [comment]
```
14:36:08 # A fatal error has been detected by the Java Runtime Environment:
14:36:08 #
14:36:08 #  SIGSEGV (0xb) at pc=0x00007f831714fa19, pid=21618, tid=0x00007f82f9d7a700
14:36:08 #
14:36:08 # JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
14:36:08 # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode linux-amd64 compressed oops)
14:36:08 # Problematic frame:
14:36:08 # V  [libjvm.so+0xa33a19]  Symbol::as_C_string() const+0x9
14:36:08 #
14:36:08 # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
14:36:08 #
14:36:08 # An error report file with more information is saved as:
14:36:08 # /home/jenkins/workspace/KIE/7.18.x/pullrequest/appformer-pullrequests-7.18.x/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-lienzo/target/apidocs/hs_err_pid21618.log
```
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by ederign** [comment]
fails are not related.

**Pull request merged**
