### PR TITLE
AF-933: UI/UX Settings Improvements

### PR DESCRIPTION
**Pull request by tiagobento**
Opening to trigger Jenkins build.

See: https://issues.jboss.org/browse/AF-933

- Add URL field to the POM model.
- Create infrastructure to enable Promises usage: `Promises.java`
- Create infrastructure to enable testing classes that use Promises: `SyncPromises.java`

Related: 
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/677
- https://github.com/kiegroup/appformer/pull/142
- https://github.com/kiegroup/kie-wb-common/pull/1367
- https://github.com/kiegroup/jbpm-wb/pull/974

### CODE REVIEW

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by domhanak** [comment]
Jenkins please execute full downstream build

**Comment by domhanak** [comment]
@tiagobento Hello, could you please rebase referenced PR's to make downstream build pass? I would like to try and see the changes

**Comment by tiagobento** [comment]
@domhanak I think this PR was incorporated in another PR by @adrielparedes. @adrielparedes can you confirm this? I think it will be the case we close my `UI/UX Settings Improvements` PRs.

**Comment by adrielparedes** [comment]
@domhanak @tiagobento yes I can confirm that is being integrated into AF-913. I'm still working on that.

**Comment by tiagobento** [comment]
@adrielparedes Great, thanks! I think my `AF-933` PRs can all be closed, then.

**Comment by tiagobento** [comment]
Closing because AF-913 has incorporated AF-933.

**Pull request closed without merging**
