### PR TITLE
[AF-1074]: Removed unused OrganizationalUnitManager View that made connected clients crash.

### PR DESCRIPTION
**Pull request by adrielparedes**
I removed the complete _uberfire-organizationalunit-manager_ beacuse it was not being used and it generated the problem between connected clients.

@mbarkley Would you mind to review it?

### CODE REVIEW

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by adrielparedes** [comment]
@mbarkley @ederign Just for the record. I've smoked this on kie-wb-webapp. It looks that the full downstream tests that are failing are not related to this change.

**Comment by mbarkley** [comment]
Yeah, just smoke tested myself and aside from the JQuery issue that just got reverted on master, everything is fine. Going to merge this.

**Pull request merged**
