### PR TITLE
[7.67.x-blue] Update infinispan to 14.0.27.Final.

### PR DESCRIPTION
**Pull request by baldimir**
Updates the version of infinispan to fix several CVEs.

Related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2485

### CODE REVIEW

**Comment by baldimir** [comment]
Looks like the new Infinispan version doesn't work with JDK 8.

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run cdb

**Review by yesamer — APPROVED** [review]

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Pull request merged**
