### PR TITLE
AF-2534 : Dashbuilder Data Transfer feature does not work on Windows

### PR DESCRIPTION
**Pull request by akumar074**
* Fixed URI schemes for file (:///)
 * Fixed windows path by replacing "\\" to "/"

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Srihari1192** [comment]
@akumar074 please find the observation.
Importing Dashbuilder data feature not working in windows, after click on 'import' showing Data import success but while extracting throwing as "No data available on Zip archive" and server error as 

`ERROR [stderr] (default task-3) java.lang.RuntimeException: org.eclipse.jgit.dircache.InvalidPathException: Invalid path: C:/Users/IEUser/AppData/Local/Temp/dashbuilder-data-transfer/dashbuilder/datasets/definitions/6ad3c5f1-18ac-461e-aa97-b99649576677.csv
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.util.commands.CreateDefaultCommitTree.execute(CreateDefaultCommitTree.java:107)
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.util.commands.Commit.execute(Commit.java:113)
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.util.GitImpl.commit(GitImpl.java:433)
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.commit(JGitFileSystemProvider.java:2434)
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.access$400(JGitFileSystemProvider.java:183)
03:57:51,763 ERROR [stderr] (default task-3)    at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider$4.close(JGitFileSystemProvider.java:1177)
03:57:51,769 ERROR [stderr] (default task-3)    at org.uberfire.io.impl.AbstractIOService.write(AbstractIOService.java:681)
03:57:51,770 ERROR [stderr] (default task-3)    at org.uberfire.io.impl.AbstractIOService.write(AbstractIOService.java:511)`

**Comment by akumar074** [comment]
@Srihari1192 Thanks for the review. The issue you mentioned, I'm already looking into it. It seems the windows doesn't support the file name with ":" in it.

**Comment by akumar074** [comment]
Jenkins execute full downstream build

**Comment by akumar074** [comment]
Hi @Srihari1192 @jesuino , I have fixed the issue mentioned by @Srihari1192 . Please go ahead with the review. Thanks.

**Comment by akumar074** [comment]
enkins execute full downstream build

**Comment by akumar074** [comment]
Jenkins execute full downstream build

**Comment by akumar074** [comment]
Jenkins retest this please

**Comment by akumar074** [comment]
Jenkins retest this please this

**Comment by Srihari1192** [comment]
@akumar074 @jesuino observation in windows with EAP 2.7 -> when we click upload button in import page,it's not showing **"file upload success notification"** , getting backend error and upon click on import or further file uploading.. feature works fine..only issue with very first time..
With EAP 3 version , behaviour looks fine.

`00:33:41,919 ERROR [io.undertow.request] (default task-12) UT005023: Exception handling request to /business-central/org.kie.bc.KIEWebapp/defaulteditor/upload: java.lang.IllegalStateException: UT010019: Response already commited
        at io.undertow.servlet.spec.HttpServletResponseImpl.sendError(HttpServletResponseImpl.java:168)
        at io.undertow.servlet.spec.HttpServletResponseImpl.sendError(HttpServletResponseImpl.java:215)
        at org.uberfire.server.FileUploadServlet.finalizeResponse(FileUploadServlet.java:84)
        at org.uberfire.server.FileUploadServlet.doPost(FileUploadServlet.java:54)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.uberfire.ext.security.server.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:110)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

**Comment by akumar074** [comment]
> @akumar074 @jesuino observation in windows with EAP 2.7 -> when we click upload button in import page,it's not showing **"file upload success notification"** , getting backend error and upon click on import or further file uploading.. feature works fine..only issue with very first time..
> With EAP 3 version , behaviour looks fine.  

@Srihari1192 I think the issue is with the compatibility of 7.39.x and WF 14(EAP 7.2 is based on). We have already upgraded all the repos to WF 18 ([JBPM-9044](https://issues.redhat.com/browse/JBPM-9044)). So, there could be some issues due to that. I think we should only test with EAP 7.3. 
@jesuino @ederign wdyt?

**Comment by ederign** [comment]
+1. we are in the middle of upgrade for eap. So I would suggest to test only on wf18 right now.

**Comment by akumar074** [comment]
Jenkins retest this

**Pull request merged**
