### PR TITLE
AF-2411: Added service to consume file system properties

### PR DESCRIPTION
**Pull request by adrielparedes**
Related to:
* https://github.com/kiegroup/appformer/pull/895
* https://github.com/kiegroup/kie-wb-common/pull/3314
* https://github.com/kiegroup/drools-wb/pull/1379
* https://github.com/kiegroup/jbpm-wb/pull/1436
* https://github.com/kiegroup/optaplanner-wb/pull/371
* https://github.com/kiegroup/kie-wb-distributions/pull/1010

### CODE REVIEW

**Comment by rhtevan** [comment]
@adrielparedes  Do we still need this PR?

**Comment by adrielparedes** [comment]
> @adrielparedes Do we still need this PR?

yes we need, it helps to disable some Pages in final build

**Comment by ederign** [comment]
please jenkins retest this

**Comment by ederign** [comment]
please jenkins retest this

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
well for some reason the FDB doesn't exist anymore, I will run it again

**Comment by adrielparedes** [comment]
The failing tests are not related to the changes in this PR

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Pull request merged**
