### PR TITLE
AF-2341 : Not able to restore files where dot file (metadata) has been edited

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/AF-2341

### CODE REVIEW

**Comment by ederign** [comment]
Hi Toni thanks for this help. Today @caponetto was estimating this for our 7.7 scope and found some other issues that could be related.

https://issues.jboss.org/browse/AF-2342
https://issues.jboss.org/browse/AF-2343
https://issues.jboss.org/browse/AF-2344

**Comment by Rikkola** [comment]
Ok. I just went for it since the RHPAM ticket was assigned to me. If this is under control and this fix has issues I'll close this PR.

**Comment by Rikkola** [comment]
@caponetto Ok reopened this and the problem you reported was there, but figured out how to fix it.

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
Failed to publish reports.
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Please merge.

**Comment by manstis** [comment]
@Rikkola Do you need @paulovmr to review?

**Comment by Rikkola** [comment]
@manstis removed Paulo, @caponetto took his place as a reviewer.

**Pull request merged**
