### PR TITLE
DROOLS-2503 Switch Maven repository to repository.jboss.org.

### PR DESCRIPTION
**Pull request by pszubiak**
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

### CODE REVIEW

**Comment by porcelli** [comment]
@pszubiak please could you give us more context about this change?

**Comment by pszubiak** [comment]
@porcelli it's related with jboss.org nexus performance. The problem is that we are skipping load balancers and sending requests direct to nexus web application. According to nexus team this is a reason of recent outages.

**Comment by porcelli** [comment]
@pszubiak thx for the clarification.

**Comment by manstis** [comment]
@pszubiak Do we need to update our local ```settings.xml``` to use the new URLs?

**Comment by pszubiak** [comment]
@manstis Good point! Yes if you have origin-repository.jboss.org repository defined in local settings.xml file it would be good to change it to repository.jboss.org.

**Pull request merged**
