### PR TITLE
AF-1210: Space screen is shown sometimes after an asset is closed

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
@ederign if you could take a look, please. Thanks!

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@tomasdavidorg @jhrcek  or @barboras7  could you please take a look at this tomorrow morning? This is really annoying and we want to try to put this on 7! Thanks.

**Comment by tomasdavidorg** [comment]
@ederign I will look at this.

**Pull request merged**
