### PR TITLE
RHPAM-2647 :[GSS](7.z) Errors when building a project are shown to all users

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**RHPAM-2647**: _https://issues.redhat.com/browse/RHPAM-2647_ 

**Current Behaviour**: Error message in a project was shown to all users, irrespective of the opened project and branch.
**Expected Behaviour** : Error message is only shown to users who are in same project and same branch. This is done since BC projects are shared in nature and users access the same version of a project repository.

Related PR:
 https://github.com/kiegroup/kie-wb-common/pull/3546
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by Srihari1192** [comment]
@RishiRajAnand Now we are isolating all the errors/warning alerts with respect to the project.
How about the information of newly added projects.

Screenshot from 2021-02-24 19-58-50

**Comment by Srihari1192** [comment]
@RishiRajAnand Please find the observation
1.Error/Warning Alerts is listing incorrectly in case user navigate from different project after facing Build errors/warning in different project.

Steps:
-   Perform error/warning alerts in project A 
-   Navigate to project B and click view Alerts 
-   check whether Alerts is belongs to same project

Screenshot from 2021-03-01 18-12-39

2.With the above scenario, In some cases different project Alerts is not clearing even though after Build and Deploy.
  User has to clear Alerts and proceed Build , when user wish to not to be seen different Project Alerts.
Screenshot from 2021-03-01 18-22-22

**Comment by RishiRajAnand** [comment]
> @RishiRajAnand Now we are isolating all the errors/warning alerts with respect to the project.
> How about the information of newly added projects.
> 
> Screenshot from 2021-02-24 19-58-50

Hello Srihari, IMO Information on newly added projects could be available to all users since this activity happens once and other users could be intimidated about it, post that rest error/warnings should be isolated. @porcelli @ederign any thoughts ??

**Comment by Srihari1192** [comment]
@RishiRajAnand Any updates for reported observations. Are we good to finish today , as today is cut-off for 7.10.1 CR1.

**Comment by RishiRajAnand** [comment]
> @RishiRajAnand Any updates for reported observations. Are we good to finish today , as today is cut-off for 7.10.1 CR1.

Hi @Srihari1192 , Thanks for your analysis. I think we'll need to postpone this to 7.11 since we have identified some edge cases to this that causes unconsistent behavior of alert sometimes. we'll fix this and merge this for 7.11 maybe after a through testing.

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Hello @Srihari1192 , I have pushed new changes now. Some points to help you with your testing
1. Only errors/warnings related to a project are shown only to user working on same project.
2. When user navigates to a projects, initially it shows last shown error on console. Error console changes when user either builds the project again or some other user initiates a build.

**Comment by Srihari1192** [comment]
Jenkins run fdb

**Comment by Srihari1192** [comment]
jenkins do fdb

**Comment by ederign** [comment]
@adrielparedes can you please review this?

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Review by adrielparedes — APPROVED** [review]

**Comment by adrielparedes** [comment]
@RishiRajAnand once QE Approves I will ping @ederign to merge this. Good job

**Review by Srihari1192 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Pull request merged**
