### PR TITLE
KOGITO-866: Cover ONLINE, VSCODE, DEFAULT on Context Editor unit Testing

### PR DESCRIPTION
**Pull request by jesuino**
Adding test coverage for all channels.

### CODE REVIEW

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
please jenkins retest this

**Pull request merged**
