### PR TITLE
migrated kie-soup-bom and uberfire-bom to droolsjbpm-build-distribition

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/980
https://github.com/kiegroup/kie-soup/pull/100
https://github.com/kiegroup/appformer/pull/735

**Comment by mbiarnes** [comment]
@manstis @danielezonca @gitgabrio this iss failing because of failing tests in uberfire. The build itself says successful. But it is yellow (USTABLE) due to faling tests in uberfire.

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@mbiarnes 
I asked jenkins for a rebuild because I have not error compiling master locally.
Btw if you are blocked by that I think we can also merge because it could be a random failure

**Comment by gitgabrio** [comment]
@danielezonca @mbiarnes @manstis 
Does the build with error happened using the PR "mbiarnes:bomMigration" for all the three repo involved?
If so, using this PR for the current repo (appformer) and master for the others may lead to different results then jenkins

**Comment by danielezonca** [comment]
@mbiarnes 
Ok now is green, so it was a random failure :)

**Comment by mbiarnes** [comment]
Jenkins execute compile downstream build

**Comment by mbiarnes** [comment]
@manstis @danielezonca @krisv 
compile downstream build failure in kie-wb-distributions because:
17:46:55 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project business-monitoring: Failed to install artifact org.kie:business-monitoring:war:wildfly14:7.24.0-SNAPSHOT: No space left on device
This is a jenkins problem - not code.
Can anyone please merge these PRs?

**Comment by manstis** [comment]
@mbiarnes It looks like @gitgabrio raised a couple of questions.

Should these be addressed before we merge!? Gabriele is a _reviewer_ after all.

**Comment by mbiarnes** [comment]
Jenkins execute compile downstream build

**Comment by mbiarnes** [comment]
Jenkins execute compile downstream build

**Comment by danielezonca** [comment]
@gitgabrio 
What do you mean?
This PR is based on master that already contains the bom migration (and all the other repo too).

**Comment by mbiarnes** [comment]
the same commit is in #737

**Comment by gitgabrio** [comment]
> @gitgabrio
> What do you mean?
> This PR is based on master that already contains the bom migration (and all the other repo too).

@danielezonca 
On jenkins all the linked PRs are built together, while on local machine we have to built them one by one. So, in local machine, the first built is using "master" for all the others, and so on. That may lead to a different overall environment and - then - test results.

**Pull request closed without merging**
