### PR TITLE
[docs] fixed typos and minor language issues

### PR DESCRIPTION
**Pull request by jstastny-cz**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished. 5032 tests run, 11 skipped, 0 failed.

**Comment by jstastny-cz** [comment]
Hello @ederign, I've just read through the docs. I will try running the tutorial and showcase.

**Comment by jstastny-cz** [comment]
@ederign I wasn't able to run the showcase because of AF-1740. So this PR can't be extended until that one is resolved.

**Comment by ederign** [comment]
I'm closing this PR due to inactivity. If necessary and I'll reopen it again, just let me know.

**Pull request closed without merging**
