### PR TITLE
DBACLD-145641: upgrade jgit to address important CVEs

### PR DESCRIPTION
**Pull request by porcelli**
related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2480

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Comment by ederign** [comment]
LGTM as soon as the tests are green. (looks like an external issue)

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins retest it

**Comment by yesamer** [comment]
Jenkins retest

**Comment by yesamer** [comment]
Jenkins retest

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by baldimir** [comment]
Looks like the newer jgit requires at least Java 11.

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Review by yesamer — APPROVED** [review]

**Pull request merged**
