### PR TITLE
AF-2066: Project is not visible after more projects are created at the same time

### PR DESCRIPTION
**Pull request by pefernan**
Looks like some operations, like adding a repo were not added into a batch, so when multiple repos were added at same time SpaceInfo was being overwritten instead of updated.

@adrielparedes @tomasdavidorg could you please take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@pefernan let's wait for tests. Also I will include this in a branch that will contain all commits that are not in master yet but need to be tested in HA mode.

**Comment by pefernan** [comment]
@adrielparedes do you want me to send a PR to your fork as we did before?

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by adrielparedes** [comment]
> @adrielparedes do you want me to send a PR to your fork as we did before?

@pefernan no, is not necessary, I can do it. Thanks!

**Comment by tomasdavidorg** [comment]
Please do not merge. We need to first check the fixes on the latest OpenShift images.

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Pull request merged**
