### PR TITLE
AF-2637: Implement SVG backend Service for Kie Server

### PR DESCRIPTION
**Pull request by jesuino**
[AF-2637](https://issues.redhat.com/browse/AF-2637)

Part of an ensemble, merge with:

https://github.com/kiegroup/jbpm-wb/pull/1467

--------------------------------------------------------------------------------
This PR:

* Extends components functions (AF-2636) to backend;
* Add a function to retrieve a process SVG.

The way it was implemented was using a proxy mechanism. The class BackendFunctionLoaderService is responsible to look for backend functions, then the class BackendFunctionLoader calls the service to list the registered functions and register it on client side and also proxy calls to backend funcions.

Along with this we created ProcessSVGFunction, it uses Kie Server API to retrieve a process SVG. Notice it requires two parameters: containerId, process Id. It is also possible to define a serverTemplateId, where user can set a server template to look for the Kie server to retrieve the SVG. If a server template is not used then the function uses the first one available or a default server template, configured using system property `dashbuilder.kieserver.defaultServerTemplate`.

Since the way to access Kie Server in DB is different of how it is done in BC, we implemented a specific function for BC. It has the same name and support the same parameters, so we should be fine when exporting dashboards that uses this function from BC to DB.

https://github.com/kiegroup/jbpm-wb/pull/1467

To test the changes use the component I created called process_svg. Just copy the following folder into your components directory. In BC you create a new page and drag the component, make sure you have Kie Server containers running and a process with SVG (the sample evaluation has SVG) then you create a container, drag the component, set the values corresponding values and it should work, see an example:

process_svg_comp

 If you just import the evaluation example and deploy, then these values in component config should be okay:

Container: evaluation_1.0.0-SNAPSHOT
Process: evaluation
Server template: sample-server   

image

Process SVG component:
https://github.com/jesuino/dashbuilder-components/tree/master/process_svg

### CODE REVIEW

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by sthundat** [comment]
@jesuino ,
Thanks for adding me as a reviewer.can you please correct the link for Process SVG component that you have provided in the PR.
Regards,
Savitha

**Comment by jesuino** [comment]
Thank you, Savitha, I just corrected the link: https://github.com/jesuino/dashbuilder-components/tree/master/process_svg

**Comment by caponetto** [comment]
Hi @jesuino, 
I see that there are some issues raised by SonaCloud that are easy to get rid of. 
Can you please take a look? :)

**Review by caponetto — COMMENTED** [review]
Hi @jesuino, thanks for the PR!
I've left some comments, please check if they make sense.

**Comment by jesuino** [comment]
Hello @caponetto 

Thanks for the great review as always, I commented inline and made the suggested changes. Let me know if you have any question.

**Review by caponetto — APPROVED** [review]

**Comment by sthundat** [comment]
jenkins execute fdb

**Comment by sthundat** [comment]
@jesuino ,
Please find my comments below,
1.I would prefer all user operation to be together, the submit(OK) and cancel buttons to be  down under server template ID. 
Currently user needs to move mouse far and it is ambiguous for a user to understand the OK/Cancel button are for this form.

2.Put *(in red color) prior to mandatory fields, this helps user to understand what all are mandatory fields.

3.I would prefer the error messages also should be in the same area down under "Components properties." And error has to display post to the submit(/ok) operation.

4.The form appears in a smaller area and majority of the space is kept unused. Is that reserved for something else?
please let me know your thoughts.
Regards,
Savitha

**Comment by jesuino** [comment]
Hello @sthundat, 

Thanks for your comment, I really appreciate.

Kindly notice that the functionality isn't about the component itself, but about the SVG function running in backend. In future, if we redesign the component, we could do 1.

3 is possible to make a proper error screen, using the warning feature, see, but as I said this is just a test component to retrieve the SVG!
configuration_issue_new


For 2 I made a JIRA and PR, see https://github.com/kiegroup/appformer/pull/1071 - It is a preliminary work, but later we can improve it or when we redesign components configuration fields.

Thanks!

**Comment by sthundat** [comment]
Hi @jesuino ,
Whatever i have suggested are only UX improvements.Functionality works fine.Its all about reducing the mouse movement and meaningful placement of components.
Thanks for creating Jira for supporting component mandatory fields .
Approving the PR
Regards,
Savitha

**Review by sthundat — APPROVED** [review]

**Comment by jesuino** [comment]
Test failure is unrelated

org.kie.hacep.LocalStorageStreamingKieSessionTest.getCommandsTest

**Review by ederign — APPROVED** [review]

**Pull request merged**
