### PR TITLE
[7.26.x]  AF-2252 : File download does not work with & character

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 43c5eeca5eb2c41d17dc761e3d83193777ad948b)

https://issues.jboss.org/browse/AF-2252

https://github.com/kiegroup/appformer/pull/826
https://github.com/kiegroup/kie-wb-common/pull/2975

### CODE REVIEW

**Comment by Rikkola** [comment]
Made this just to run into any trouble ASAP. The PRs for master are not in yet.

**Comment by Rikkola** [comment]
@sthundat FYI the same changes for 7.26.x

**Comment by Rikkola** [comment]
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Closing as this was moved from targeting 7.26.x branch

**Pull request closed without merging**
