### PR TITLE
KOGITO-7181 : Remove default password on Uberfire's CredentialsClientFactory.java

### PR DESCRIPTION
**Pull request by Rikkola**
[KOGITO-7181](https://issues.redhat.com/browse/KOGITO-7181)

[ZIP](https://drive.google.com/file/d/1r3eyVTQLlbsV7i03ymDQESZ4S0_YLZkT/view?usp=sharing)

[war](https://drive.google.com/file/d/1NVju-ZTJcRJJcOrAlEBT_RftA-WleSHy/view?usp=sharing)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
`[org.jbpm.workitem.springboot.samples.KafkaProxySampleTest.testKafkaWIHNoConnection[0: SINGLETON]](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/appformer-main.fdb/150/testReport/junit/org.jbpm.workitem.springboot.samples/KafkaProxySampleTest/testKafkaWIHNoConnection_0__SINGLETON_/)`

Jenkins run fdb

**Comment by Rikkola** [comment]
`[org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingServiceTest.testPingSuccess](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/appformer-main.fdb/151/testReport/junit/org.uberfire.ext.metadata.backend.infinispan.provider/InfinispanPingServiceTest/testPingSuccess/)`

Jenkins run fdb

**Comment by Rikkola** [comment]
`org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3`
And address already in use issues.

Jenkins run fdb

**Comment by Rikkola** [comment]
@tomasdavidorg I'll change the message to something more meaningful. The war should still be fine

**Review by tomasdavidorg — APPROVED** [review]

**Comment by Rikkola** [comment]
@RishiRajAnand If you could give this too a quick look.

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
