### PR TITLE
AF-2446: Dashbuilder Map Displayer support latitude,longitude

### PR DESCRIPTION
**Pull request by jesuino**
This is support for location columns in map.

Right now the map displayer only supports countries names and codes. It does not support location, meaning that the user dataset must contain country name or code. The country name is complicated because it may change according to policies and language. The country code does not cover if a location is inside a country.

The way that location is support is using a text column with value "latitude,longitude". The map displayer will try to identify if the column contains such value and then use it as location. Otherwise will use the value as country code/name.

This PR also cover AF-2446, Colors support in maps. For this issue the following option was added:

image

This allow users to change the color scheme used by the Map component.

### CODE REVIEW

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
@barboras7 Hello Barbora, do you know who could please review this? These are dashboard issues and you used to verify them.

In this PR I am targeting two issues at once, please see description.

**Comment by barboras7** [comment]
Hi @jesuino,
@sthundat will take a look at this PR :slightly_smiling_face:

**Comment by sthundat** [comment]
Jenkins execute full downstream build

**Comment by sthundat** [comment]
if I selected latitude,longitude value under groups ,this information ( latitude,longitude) is not displaying in the map tooltip.Instead of location information country name is displaying in the tooltip now.please see the attachment
location1

**Comment by sthundat** [comment]
see below the sample dataset(countryLoc.csv) file
samplecsv

**Comment by jesuino** [comment]
Hello Savitha,

Thanks for the feedback and sorry for the late feedback.

I can't change by location because there may be the case where multiple locations match the same geography polygon, for example, in [1] we have locations from the same country, hence why all matching location for a country are grouped.

If we change the change the map polygon to use countries with state we could have the state name, for example. To address such behavior we could:

* Support point location for bubble map displayer - we could create a JIRA for this;
* Allow users to upload their own geo polygons, so they could have more precise geo information.

[1] https://github.com/jesuino/dashbuilder-data/blob/master/covid19/covid19_deaths.csv

**Comment by sthundat** [comment]
Hi William,
I can explain you with some real data.Please ref covid.csv for dataset I have used.
here  for India I have selected( 10.8505,76.2711 ) as location.This is the location information of one state in india(kerala)and there covid death count is 0.but that doesn't mean that the death count in India is 0.But map is telling different story.if i hover India it is telling there death count is 0.
That means we are passing wrong information to the user .
covid.csv
************
'Country code';'Country name';'latitude,longitude';'Total deaths'
CHN;'China';'30.583332,114.3055';2592
IND;'India';'10.8505,76.2711';0
ITA;'Italy';'141.8719,12.5674';7503
ESP;'Spain';'40.4637,3.7492';4089
IRN;'Iran';'32.4279,53.6880';2234
CAN;'Canada';'56.1304,106.3468';36
BRA;'Brazil';'14.2350,51.9253';60
JPN;'Japan';'36.2048,138.2529';45
CZE;'Czech Republic';'49.8175,15.4730';6
RUS;'Russia';'61.5240,105.3188';3
AUS;'Australia';'25.2744,133.7751';13

**Comment by sthundat** [comment]
below is the another issue:
 some country is not rendering correctly on  map.for example  i used Canada in my dataset and groups by latitude,longitude on settings.On map Russia is highlighted/colored instead of Canada.

**Comment by jesuino** [comment]
Hello @sthundat ,

Thanks for your feedback. I could not reproduce both issues:

* The count 0 for India is accurate because in the dataset you pointed for testing actually has only one record for India and the value is indeed 0;
* Although the data says that the lat-long is for Canada, I see that it is actually showing as Russia in Google Maps, see:

https://www.google.com/maps/search/56.1304,106.3468?sa=X&ved=2ahUKEwiKmIjv8rroAhVBDrkGHbVeB4UQ8gEwAHoECAwQAQ

I think the long is negative, hence the confusion. It works correctly when I use:

56.1303673, -106.3467712


Thanks!

**Comment by sthundat** [comment]
Based on the discussion with William,
The way colored map work is by highlight areas on the map based on the location.The default geometry we are using is world countries,so all locations for a country is summed and the map is colored accordingly.So Based on this approach functionality is working fine on map displayer.

Also with 56.1303673, -106.3467712 (lat,long)location values ,Canada is displaying correctly.Thanks for the help.

Hence approving this PR.

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
jenkins retest this

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
@jesuino please let me know when the build is green.

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
@ederign the test failure seems to be unrelated, but let's try one more time
```
org.jbpm.test.functional.timer.ConcurrentGlobalTimerServiceTest.testSessionPerProcessInstance
```

**Comment by jesuino** [comment]
jenkins retest this

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
jenkins retest this

**Comment by ederign** [comment]
FDB green : https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/appformer-downstream-pullrequests/494/

**Comment by ederign** [comment]
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/appformer-pullrequests/680/

org.dashbuilder.displayer.client.widgets.DisplayerSettingsEditorTest.testChangeAttributes
org.dashbuilder.displayer.client.widgets.DisplayerSettingsEditorTest.testMeterValidator

**Comment by ederign** [comment]
jenkins retest this

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Pull request merged**
