### PR TITLE
AF-1080: New project with the same name as another project in different space disappear after server restarts

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/723
* https://github.com/kiegroup/appformer/pull/251
* https://github.com/kiegroup/kie-wb-common/pull/1520

### CODE REVIEW

**Comment by jhrcek** [comment]
We would like to test this locally. Jenkins execute full downstream build
We'll provide feedback tomorrow.

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Pull request merged**
