### PR TITLE
AF-1674: Role-based access to branches in the Workbench

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/665
* https://github.com/kiegroup/kie-wb-common/pull/2538
* https://github.com/kiegroup/drools-wb/pull/1095
* https://github.com/kiegroup/jbpm-designer/pull/843
* https://github.com/kiegroup/jbpm-wb/pull/1319
* https://github.com/kiegroup/optaplanner-wb/pull/330

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@adrielparedes @barboras7 could you please take a look on this?

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @paulovmr, 
I'll share my initial review also here so that the other reviewers can see what I found:

#### Bugs:

1. It is not possible to add contributors to default space _(Start an empty business central, open "MySpace" and click "Contributors" tab - the "Add Contributor" button is there, but it is not visible)_
2. Branch settings get lost when you switch between branches _(In Settings -> Branch management - change some settings for branch1, do not save these settings and switch to branch2 -> when you switch back to the branch1, the settings are in the initial state not in the state you set)_
3. No “Add Contributor” button is available in sample projects in MySpace _(Go into MySpace (default space),  click Try Samples and choose some project; when you go to the Contributors tab, there is no “Add Contributor” button)_
4. Some buttons in asset editors are duplicated _(Open MySpace -> create some project -> create a data object -> you can see the button “Download” twice (also happens for other asset types and multiple buttons) - applies to default editor as well (for example when you click Import asset and choose some text file))_

#### UX issues:
1. Some tooltips explaining what read, write, etc. in Branch Management mean would be useful
2. Branches in the dropdown in Branch Management are not ordered alphabetically
3. The order of roles in Branch Management changes based on the currently set access rights (This could be confusing as it is easy to overlook that the order of roles changed)

#### Questions:
1. Should the newly created branch inherit access settings of its base branch? (As a user, I would expect that the access settings on the newly created branch are inherited from the base branch)
2. What do the different types of role access mean? (For example, setting "read" for Contributor - what is granted by that? Is it related to all files in the project on the selected branch?)
3. Is there a use case where "write" makes sense without "read"? (Also some other combinations may come up) I believe that it would be good to disable buttons in some combinations

**Comment by barboras7** [comment]
Adding one more bug to the list:
5. When you open kmodule.xml file, no menu is available (Create a DRL file, expand the Project explorer, switch to the Repository view, then navigate to src/main/resources/META-INF and open the kmodule.xml file -> There is no menu to e.g. save changes, etc.)

Also, I believe that the best approach would be to check the code once the issues are fixed because many things in the code will be probably changed by the fixes.

**Comment by paulovmr** [comment]
@barboras7 Thanks for the review! I fixed all the issues, could you check again?

jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@sterobin this will require some docs. Paulo will work on this as soon as we get this merged.

**Comment by sterobin** [comment]
@ederign, thanks. @csherrar is your man. He's the writer assigned to the AppFormer team. Clifton, just FYI.

**Comment by csherrar** [comment]
@ederign @sterobin ack thanks

**Comment by barboras7** [comment]
@paulovmr thanks for the fixes, see the comment in my docs. I think there will be no major updates to code anymore, so I'll finish the code review for by tomorrow EOD.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unrelated build failure

**Pull request merged**
