### PR TITLE
AF-2209: Remove yarn.lock files from kiegroup projects

### PR DESCRIPTION
**Pull request by tiagobento**
See description on JIRA.

Related:
https://github.com/kiegroup/appformer/pull/813
https://github.com/kiegroup/kie-wb-common/pull/2933
https://github.com/kiegroup/kogito-tooling/pull/20

### CODE REVIEW

**Comment by tiagobento** [comment]
@mareknovotny Could you please confirm that this PR (and also the related PRs) will solve the issue to configure different registries on our CI environment? Thanks!

**Comment by mareknovotny** [comment]
@Ginxo @almope please check and review all PRs related to removal of lock files.
I think we are still missing some repositories which uses it. But this is good start

**Comment by domhanak** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
@mareknovotny https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1072 from BXMSPROD-477 will remove every yarn.lock and package-lock.json files for every project

**Comment by tiagobento** [comment]
@Ginxo @mareknovotny Should we move forward with these PRs even with kiegroup/droolsjbpm-build-bootstrap#1072?

**Comment by Ginxo** [comment]
@tiagobento thanks to kiegroup/droolsjbpm-build-bootstrap#1072 the build process won't be affected by this PR, so I would move it forward yes. @mareknovotny @almope wdyt?

**Comment by mareknovotny** [comment]
keeping kiegroup/kogito-tooling#20 for later, now only kiegroup PRs

**Pull request merged**
