### PR TITLE
AF-2283: Cannot open standalone perspective in Firefox

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@paulovmr @ederign IDK for sure, but if the test started failed recently could it be down to https://github.com/kiegroup/appformer/pull/796 that now prompts the User before closing the window? Please feel free to ignore me.

**Comment by paulovmr** [comment]
@manstis Based on the behaviour I saw, the problem was indeed caused by  https://github.com/kiegroup/appformer/pull/796 , but not because of the prompt. It was because the `workbenchCloseHandler` started to be called by the `Window.addCloseHandler` instead of the `Window.addWindowClosingHandler` (that now shows the prompt). Apparently Firefox calls the close handler when the url is changed manually in the browser, and not only when the window is closed, like Chrome does, which causes the problem.

**Comment by caponetto** [comment]
Thanks for this, @paulovmr!
I'll include the changes in https://github.com/kiegroup/appformer/pull/800 as well.

**Pull request merged**
