### PR TITLE
AF-2581: Maps tooltip is gone

### PR DESCRIPTION
**Pull request by jesuino**
This is a quick fix for an issue I found which would impact a demo I am working on.

With this fix:

* Tooltips will be displayed again;
* There's the option to hide the bad legend

### CODE REVIEW

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
failed tests are not related

org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:46062/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort

**Pull request merged**
