### PR TITLE
AF-2604: Infinispan version upgraded to 9.4.19

### PR DESCRIPTION
**Pull request by adrielparedes**
**Description**
ISPN version upgraded to match RHDG 7.3.6

**JIRA**: 
* https://issues.redhat.com/browse/AF-2604
* https://issues.redhat.com/browse/RHPAM-3089

**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1444
* https://github.com/kiegroup/appformer/pull/1031

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Review by sutaakar — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
jenkins do fdb

**Comment by adrielparedes** [comment]
Jenkins do fdb

**Comment by adrielparedes** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Comment by adrielparedes** [comment]
@mareknovotny the error is not related to the change. Are we ready to merge?

**Pull request merged**
