### PR TITLE
[7.59.x] AF-2904: Cloning repository from BC with SSH does not work

### PR DESCRIPTION
**Pull request by Rikkola**
**Thank you for submitting this pull request**

**JIRA**:
[AF-2904](https://issues.redhat.com/browse/AF-2904)
[AF-2905](https://issues.redhat.com/browse/AF-2905)
[AF-2911](https://issues.redhat.com/browse/AF-2911)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
```[2021-10-14T12:59:50.864Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) on project appformer-js: Could not download Node.js: Got error code 502 from the server. -> [Help 1]
[2021-10-14T12:59:50.864Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) on project appformer-js: Could not download Node.js: Got error code 502 from the server.```

Jenkins run fdb

**Comment by mareknovotny** [comment]
GHA jdk 8 was failing famous InfinispanPingTest and GHA JDK 11 stopped on `2021-10-15T15:09:03.9771254Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.9.0:compile (gwt-compile) on project dashbuilder-webapp: Command failed with status 137`

**Comment by Rikkola** [comment]
Another time out 
jenkins retest this please

**Comment by Rikkola** [comment]
@mareknovotny Code coverage is up. PR build and CDB passed.

**Pull request merged**
