### PR TITLE
JBPM-6825 - Allow appending an html element as popover content

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@cristianonicolai should we wait for a full downstream build? Jenkins has no left space on device.

**Comment by cristianonicolai** [comment]
@ederign I've been trying for days now... 
@mbiarnes any chances you could have a look on Jenkins?

**Comment by ederign** [comment]
@cristianonicolai two days ago I've fixed the other issue related to maven wf11 profile. This is another thing.

If you build everything locally and did a sanity check in kie-wb I'm good to do.

**Comment by cristianonicolai** [comment]
@ederign +1, locally it all works fine.

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
changed node - Jenkins retest this please

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@mbiarnes same error, _No space left on device_ :/

**Pull request merged**
