### PR TITLE
[RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

### PR DESCRIPTION
**Pull request by rhtevan**
Keep insync with the system property name change

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

### CODE REVIEW

**Comment by kie-ci10** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by rhtevan** [comment]
@adrielparedes A minor but important change. Take a look and help merge it. Thanks

**Comment by mbiarnes** [comment]
ok to test

**Comment by rhtevan** [comment]
@adrielparedes @mbiarnes The failure looks like a timeout, not related to the PR.

**Comment by adrielparedes** [comment]
@rhtevan@mbiarnes yes, you are right the error is not related. The failing test is a ping to infinispan server. Probably infinispan is not up before the test starts. Could be related to a slow server, but not to this PR.

**Comment by adrielparedes** [comment]
@ederign @paulovmr this should be ready to be merged

**Pull request merged**
