### PR TITLE
Data set editor fixes

### PR DESCRIPTION
**Pull request by dgutierr**
Fixes + tests

=> Depends on https://github.com/kiegroup/kie-soup/pull/37

@kkufova @romartin Can you verify please?

### CODE REVIEW

**Comment by kkufova** [comment]
@dgutierr, the fix for [AF-1048](https://issues.jboss.org/browse/AF-1048) is not working (it is still possible to discard unsaved data). Could you please double check the fix? If it works for you, I can try building the PR again.

Regarding the [AF-1047](https://issues.jboss.org/browse/AF-1047): the button **New Data Set** works, but I noticed that the same problem as reported in AF-1048 appears here: if you start creating a new data set and then click the button, all the unsaved changes are discarded. Can we maybe deal with this issue here as well?

**Comment by dgutierr** [comment]
@kkufova please make sure you also build kiegroup/kie-soup#37

I tested it again and both should work fine.

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
@dgutierr, I tried to build it again. I can see that the fix for AF-1047 works very well; every time something is already filled, clicking **New Data Set** opens a warning. However, the same thing does not apply for clicking the **Back** button (unsaved changes are lost). Is this the correct behavior?

**Comment by dgutierr** [comment]
@kkufova Good point. I also added support for the Back button to the new data set wizard. 

Please have a look :-)

**Comment by kkufova** [comment]
@dgutierr, did you push the changes? :-)

**Comment by dgutierr** [comment]
@kkufova Done.

**Pull request merged**
