### PR TITLE
AF-1791: Update Elemental2 version to 1.0.0-RC1

### PR DESCRIPTION
**Pull request by jesuino**
Related to:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/913
https://github.com/errai/errai/pull/372
https://github.com/kiegroup/kie-wb-common/pull/2402

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins execute fulldownstream build

**Comment by jesuino** [comment]
please jenkins execute fulldownstream build

**Comment by jesuino** [comment]
Looks like I will have to also update jsinterop base to 1.0.0-RC1.

Let me try a local build and then I submit a new commit

**Comment by jesuino** [comment]
please jenkins execute fulldownstream build

**Comment by jesuino** [comment]
please jenkins execute fulldownstream build

**Comment by jesuino** [comment]
please jenkins execute fulldownstream build

**Comment by jesuino** [comment]
please jenkins execute fulldownstream build

**Comment by jhrcek** [comment]
@jesuino your command was not recognized as you're missing space between "full" and "downstream". Triggering the FDB again:
Jenkins execute full downstream build

**Comment by jesuino** [comment]
> @jesuino your command was not recognized as you're missing space between "full" and "downstream". Triggering the FDB again:
> Jenkins execute full downstream build

Thanks, Jan :)

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
jenkins execute full downstream build

**Pull request closed without merging**
