### PR TITLE
[7.26.x] AF-1768: Errors on Windows when login user account contains special character

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/appformer/pull/824

 @tomasdavidorg @paulovmr could you please take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
there are unrelated test failures

**Comment by mareknovotny** [comment]
@paulovmr   @tomasdavidorg please review this

**Comment by paulovmr** [comment]
Closing this as the target release was moved to 7.6.0.

**Pull request closed without merging**
