### PR TITLE
AF-2760 :Permission configured in business-central is not applied when doing git clone from outside of BC

### PR DESCRIPTION
**Pull request by RishiRajAnand**
- Applied Contributor permissions for Projects and security permissions check while cloning projects

**Thank you for submitting this pull request**

**AF-2760**: _https://issues.redhat.com/browse/AF-2760_ 

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/kie-wb-common/pull/3666
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by adrielparedes** [comment]
@RishiRajAnand code looks fine, will approve once QE approves and tests are green. Good job

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Review by Srihari1192 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
FDB failiures unrelated.

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingServiceTest.testPingSuccess(InfinispanPingServiceTest.java:48)

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Ensemble PR https://github.com/kiegroup/kie-wb-distributions/pull/1125

**Pull request merged**
