### PR TITLE
AF-2936: dependabot upgrades on appformer

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

JIRA: [AF-2936](https://issues.redhat.com/browse/AF-2936)

This PR will upgrade following dependancies :
[Bump https-proxy-agent from 2.2.1 to 2.2.4](https://github.com/kiegroup/appformer/pull/1271/commits/0ed5d0cd339e16151768c3b5ae4a87b3618bb90b)
[Bump acorn from 5.7.3 to 5.7.4 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/a66b61e3c5d24cea28e41bc66092327277fa6571)
[Bump ini from 1.3.5 to 1.3.8 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/cba3aa75ab96984fddc98e87cb46aec079570b32)
[Bump mixin-deep from 1.3.1 to 1.3.2 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/80a101be9dae2e679a0a81f7c80eef75e7a7368b)
[Bump lodash.template from 4.4.0 to 4.5.0 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/50a951bdc8f022721396bd8c3ba27cb1e1952fcc)
[Bump elliptic from 6.5.3 to 6.5.4 in /appformer-js-monaco](https://github.com/kiegroup/appformer/pull/1271/commits/97d2fb20313df79b990ebd08b34ff63cd2afe8c9)
[Bump js-yaml from 3.12.2 to 3.14.1 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/085ca2c134498771c278d92e66147417149d468b)
[Bump trim-off-newlines from 1.0.1 to 1.0.3 in /appformer-js](https://github.com/kiegroup/appformer/pull/1271/commits/8332a344b482dfd0061a2f8145c9dbf3211c93fc)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
unrelated fdb failures

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Review by barboras7 — APPROVED** [review]

**Pull request merged**
