### PR TITLE
JBPM-8523: access to the component column layout drag component

### PR DESCRIPTION
**Pull request by jesuino**
Part of an ensemble:

https://github.com/kiegroup/kie-wb-common/pull/2709

This PR goal is allow access to a component column layout drag component.

### CODE REVIEW

**Comment by jesuino** [comment]
Hello @pefernan here I added a new method to search the layout component on a given layout template.

**Comment by barboras7** [comment]
Hi @ederign,
I'd say it's the reporter of the issue (@jstastny-cz), but he's going to a conference Mon - Wed next week (me as well). If it's urgent you can try to reach out to Dominik I'd guess.

**Comment by ederign** [comment]
thanks! @domhanak who can take a look at this? Or should we wait for @jstastny-cz  ?

**Comment by barboras7** [comment]
Hi @ederign,
@jstastny-cz will be on PTO starting this Thursday (right after the conference). I'll verify this when I am back from conference on Thursday/Friday

**Comment by ederign** [comment]
@pefernan can you please take a look at this?

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by jesuino** [comment]
thanks @barboras7 I removed the space!

**Pull request merged**
