### PR TITLE
[7.7.x] AF-1412 : Kie WB REST getJob randomly return 410 Gone after previous REST call

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 58e73ea749ee9acbfd3cf165fdc81f4aaa53f861)

### CODE REVIEW

**Comment by Rikkola** [comment]
@jhrcek The one for 7.7.x

**Comment by Rikkola** [comment]
jenkins please test this.

Does this work or was this already in queue.

**Comment by Rikkola** [comment]
Ah. Refresh was not enough, had to reopen the page to see the "Some checks haven't completed yet"

**Comment by jhrcek** [comment]
@ederign Grün, let's merge this, please

**Comment by mareknovotny** [comment]
@jhrcek even the PR for master is not merged yet?

**Comment by jhrcek** [comment]
@mareknovotny I think this is safe to merge. The only significant change in this PR is addition of line that was accidently deleted by Toni during migration to project-oriented. This will only fix some issues and should not break anything.

**Pull request merged**
