### PR TITLE
[AF-1715-migration-import]: Migrated project cannot be imported to the workbench

### PR DESCRIPTION
**Pull request by adrielparedes**
## Description

With @pefernan found that after clone (in migration process), origin was not removed, so was impossible to import into workbench because origin don't exist.

## Related to:
* https://github.com/kiegroup/appformer/pull/545
* https://github.com/kiegroup/kie-wb-common/pull/2305

@pefernan @ederign would you mind to review?

### CODE REVIEW

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@adrielparedes @pefernan great work.

I just tested locally and worked nice: 

https://drive.google.com/drive/u/0/folders/1Kw0NtsSMn35I8c55Rjk8wETsdeH164ZG contains the war and also the migration tool that I've built locally. (if someone wants to manually build @adrielparedes branches, kie-wb-common needs a cherry pick for https://github.com/kiegroup/kie-wb-common/commit/1b3812931ef81e8deb66aa37784b5fe43d55417b) 

What I've tested on the war:

Import a project, Import a project with authentication, and the migration process:

Create 2 projects in a space in RHDM 7.0.0
Clone the space repository
git clone .niogit/dora-myrepo.git
image

Run migration tool on the cloned repo
./migration-tool.sh -bt [path_to_cloned_repo]
image
Imported each project for wb:
/tmp/temp/dora-myrepo/a.git
/tmp/temp/dora-myrepo/b.git
End result:
image

**Comment by mbiarnes** [comment]
@tomasdavidorg Please let me know when this was tested and we can merge this.

**Comment by tomasdavidorg** [comment]
@pefernan @adrielparedes Thanks.
I also tested this locally and it works great.

Just one note: Please reformat the code with the current codestyle, i see some codestyle issues ('*' import, missing space after comma, ...)

@ederign Nice Dora repo :smile: :dog:

**Pull request merged**
