### PR TITLE
[7.5.1] [AF-2214] User confirmation when closing the workbench with unsaved stuff

### PR DESCRIPTION
**Pull request by caponetto**
Same code: https://github.com/kiegroup/appformer/pull/796

JIRA task: [AF-2214](https://issues.jboss.org/browse/AF-2214)

If the user has unsaved changes and closes the browser, then they lost all changes without being warned about. Thus, as a last resort, in this PR the browser will ask the user for confirmation when closing the tab, closing the browser or refreshing the page.

**DEMO**
AF-2214-2019-09-10

### CODE REVIEW

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by caponetto** [comment]
https://github.com/kiegroup/appformer/pull/819 included

Can you guys take a look, please?
@paulovmr 
@barboras7 
@tomasdavidorg

**Comment by caponetto** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hi @caponetto, I discovered one issue which is caused by this change. https://issues.jboss.org/browse/AF-2305

**Comment by caponetto** [comment]
Thanks, @tomasdavidorg. I'll take a look.

**Pull request merged**
