### PR TITLE
ERRAI-1042: Moving ErraiApp.properties to META-INF dir

### PR DESCRIPTION
**Pull request by tiagobento**
https://issues.jboss.org/browse/ERRAI-1042

### CODE REVIEW

**Comment by ederign** [comment]
This should be merged after this. https://github.com/kiegroup/appformer/pull/96

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Pull request merged**
