### PR TITLE
Fix Windows specific issues

### PR DESCRIPTION
**Pull request by mackaypeter**
Fixing some of the Windows specific issues.
This was originally AppFormer/uberfire#878

### CODE REVIEW

**Comment by mackaypeter** [comment]
Hi,
I added another commit fixing more windows unit tests failures.
As these are mostly simple fixes, after consulting with @baldimir, we decided to add them to this PR, rather than open a new one.

**Comment by jhrcek** [comment]
@porcelli @ederign could you please merge this soon? This stabilization is necessary so QE can run community tests on windows.

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by jhrcek** [comment]
Last downstream build failure was due to related PR in kie-wb-common not being mergeable. Now it's rebase. 
Jenkins execute full downstream build again

**Comment by jhrcek** [comment]
For some unknown reason the full downstream build got frozen for 4 hours in this step
```
09:04:07 [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jbpm-remote-ejb-test-suite ---
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/target/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT.jar
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT.pom
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/target/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-tests.jar to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-tests.jar
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/target/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-sources.jar to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-sources.jar
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/target/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-test-sources.jar to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-test-sources.jar
09:04:07 [INFO] Installing /home/jenkins/workspace/appformer-downstream-pullrequests/downstream-repos/jbpm/jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/target/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-javadoc.jar to /home/jenkins/.m2/repository/org/jbpm/jbpm-remote-ejb-test-suite/7.6.0-SNAPSHOT/jbpm-remote-ejb-test-suite-7.6.0-SNAPSHOT-javadoc.jar
```

Aborting build and trying again.
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build after the freeze issue [has been fixed](https://github.com/kiegroup/jbpm/pull/1107) (Thanks @baldimir!)

**Comment by porcelli** [comment]
@jhrcek mind check the build fail? I'm out of vpn =/

**Comment by jhrcek** [comment]
@porcelli The full downstream build finished successfully with just 4 test failures (+1 related setup method failure). Based on failure history data http://janhrcek.cz/random-failures I can confirm that none of them are related to changes in this PR ansamble:

2 indexing test failures that are failing very often

2 failures caused probably by the fact that the tests are running in parallel:
org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithCloneTest
org.kie.workbench.common.services.backend.validation.asset.ValidatorTest.testFilterMessageWhenMessageIsInvalid

```
org.uberfire.java.nio.IOException: java.io.IOException: Failed to open server socket for /127.0.0.1:9418
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.uberfire.java.nio.fs.jgit.daemon.git.Daemon.start(Daemon.java:295)
```


I think this is safe to merge now

**Comment by jhrcek** [comment]
Please make sure to merge with https://github.com/kiegroup/kie-wb-common/pull/1204
@baldimir I'm not sure if there are more repos involved in this windows tests stabilization. Can you confirm if it concerns just appformer and kie-wb-common or list more PRs like this if there are any?

**Comment by baldimir** [comment]
@jhrcek I don't know about any other repos.

**Comment by jhrcek** [comment]
@porcelli @ederign based on my comment about full downstr. build above I think this can be merged.

**Pull request merged**
