### PR TITLE
RHPAM-3021: Gradual Export shows internal datasources

### PR DESCRIPTION
**Pull request by jesuino**
RHPAM-3021: Gradual Export shows internal datasources

Backport of AF-2561. With this change internal datasources won't be displayed in Gradual Export.

Thanks.

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
don'ŧ merge this until it is a blocker for this target branch, the jira https://issues.redhat.com/browse/RHPAM-3021 doesn't show blocker priority.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by jesuino** [comment]
@barboras7 @mareknovotny could this be merged so it will be in 7.8.1 ? 

Thanks!

**Comment by barboras7** [comment]
@jesuino I think that the issue should be acked to be merged into 7.8 branch. I already provided QE ack, so let's merge when all acks are in.

**Pull request merged**
