### PR TITLE
RHPAM-2984 :RHPAM with RHSSO shows reserved roles as a groups as well in business central

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

**RHPAM-2984**: https://issues.redhat.com/browse/RHPAM-2984

How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tomasdavidorg — APPROVED** [review]
Tested locally. Looks good to me. Just the unused import. Thanks :slightly_smiling_face:

**Comment by paulovmr** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
