### PR TITLE
AppFormer outdated code clean up

### PR DESCRIPTION
**Pull request by ederign**
Removed: archetypes, os scripts de release, docs, uberfire showcase client e o uberfire distro wars, and uberfire-dynamic

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins compile downstream

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by porcelli** [comment]
+1 as long fdb is green

**Comment by ederign** [comment]
please jenkins retest this

**Comment by ederign** [comment]
@mbiarnes @mareknovotny while I fight with the build, do you think that removing those modules will have impact on prod build?

**Comment by ederign** [comment]
please jenkins retest this

**Comment by mareknovotny** [comment]
@ederign if the FDB passes green light I think all should be ok

**Comment by ederign** [comment]
please jenkins retest this

**Comment by mareknovotny** [comment]
@ederign you have still declared uberfire-distro at https://github.com/kiegroup/appformer/blob/fd129c5bd955762f45f7d4b09a20710fe129d19e/pom.xml#L677 in full profile

**Comment by ederign** [comment]
@mareknovotny  I've removed the profile. This is not used on any script right?

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by ederign** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
the new Linux - Compile Downstream Build (***)  is green so all is ok
I can see that FDB failed on an error in kie-server-integration-common due a maven-plugin-failsafe was not able to shutdown testing container.

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by porcelli** [comment]
can we revamp this? @ederign ?

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@porcelli looks like the failures are not related: 

org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:43180/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testConversationIdHandling[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerStatusOnContainerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScannerScanNow[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testGetServerInfo[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.KieServerIntegrationTest.testScanner[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
org.kie.server.springboot.samples.KieServerMigrationTest.testProcessStartAndAbort

**Pull request merged**
