### PR TITLE
AF-2587: Indexes are removed when project is deleted

### PR DESCRIPTION
**Pull request by adrielparedes**
@RishiRajAnand @ederign 

The change is simple, I'm resolving a single path for the project to be deleted. The deletion already exist, I just did a small change to resolve the Path before the physical directory is deleted.

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
@RishiRajAnand please, could you test BC once the FDB is finished?

**Comment by RishiRajAnand** [comment]
jenkins execute full downstream build

**Comment by RishiRajAnand** [comment]
Thanks @adrielparedes  I tested the fix on my local. It fixes the issue with wrong asset number (AF-2587 ) and also AF-2540. Lets wait for FDB to finish.

**Comment by adrielparedes** [comment]
@ederign @RishiRajAnand failing tests are not related to the fix

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
> Adriel, could you please improve the coverage?

done! I upload a test to check if the deletion work

**Comment by adrielparedes** [comment]
Failing tests are not related to the changes introduced

**Pull request merged**
